### ISSUE TITLE
After manual install on SLES 15, the redirect fail on bookstack/login with error 404 - Object not found

### ISSUE THREAD

**Issue by Flemming-H** [BookStackApp/BookStack#1006] opened 2018-09-13 23:05 UTC
**Describe the bug**
Bookstack has been manually installed on SLES 15 with no errors, in a subdirectory called "/srv/www/htdocs/BookStack". Configures with redirect, and .htaccess file in public removed.

**Screenshots**
![error01](https://user-images.githubusercontent.com/27860465/45520484-dc709a80-b7b9-11e8-8a0a-14aebec701e6.PNG)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version = v0.23.2
 - PHP Version = 7.2.5
 - Hosting Method (Nginx/Apache/Docker) = Apache: 

**Additional context**
snip from .env:

> APP_URL=http://bookstack.domname.org

Full text from "/etc/apache2/conf.d/bookstack.conf":
```
<VirtualHost 10.0.0.15:80>
 ServerName bookstack.domname.org
 ServerAdmin webmaster@domname.org
 DocumentRoot /srv/www/htdocs/BookStack/public
 <Directory /srv/www/htdocs/BookStack/public>
  AllowOverride None
  Require all granted
  #Options +Indexes
<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
</Directory>
 ErrorLog /var/log/apache2/bookstack-error.log
 CustomLog /var/log/apache2/bookstack-access.log combined
</VirtualHost>
```

No errors reported in error-log, and normal entries in access-log - and the firewall has been disabled during tests.

Best regards

**Comment by Flemming-H** [comment] 2018-09-14 07:09
After reviewing the apache conf. files I found an error (misspelling) - thanks anyway

**Comment by Abijeet** [comment] 2018-09-16 05:14
Hi @Flemming-H 

Glad to hear that the issue is now sorted. Where was the spelling mistake? I can't seem to notice it.

If your problem is resolved, can you please close the issue?

**Comment by ssddanbrown** [comment] 2019-05-18 10:02
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Closed by ssddanbrown** 2019-05-18 10:02 UTC
Labels: :dog2: Support

**Comment by tacerus** [comment] 2022-09-02 22:06
My search query led me here - the author of this issue seems to have solved it by correcting a typo, but in case someone else stumbles across a `/login` 404 on SLES/openSUSE, the rewrite module is not loaded by default, and since the example config ships with `<IfModule mod_rewrite.c>`, the whole redirection block to BookStack is silently being skipped.

```
# apachectl -t -D DUMP_MODULES|grep rewr 
< no output, module is not loaded >
# a2enmod rewrite
# rcapache2 restart
# apachectl -t -D DUMP_MODULES|grep rewr
 rewrite_module (shared)
```
