### ISSUE TITLE
Make 'changes' view more visual to highlight specific differences between edits

### ISSUE THREAD

**Issue by samtuke** [BookStackApp/BookStack#1565] opened 2019-08-01 12:26 UTC
**Describe the feature you'd like**
On the default view of BookStack v0.26.3 for changes between edits, the changes are unclear because they are not highlighted or use visual conventions communicate what changed.

For example in the screenshot provided, it is unclear what changed, if anything, in the content displayed.

![Selection_617](https://user-images.githubusercontent.com/695422/62293247-6ffd9900-b468-11e9-899a-330a0294efb7.png)

Wordpress, Meld, and etherpad are three examples of applications that use clearer visual signs to show what changed.

This functionality is important for managing spam and hunting down small undesirable edits from spammers.

**Describe the benefits this feature would bring to BookStack users**
Users would be able to understand at a glance what has changed and whether it should be reverted. This is part of the necessary collaboration and content management of a manual with a large community and open registration.

**Comment by ssddanbrown** [comment] 2019-08-03 14:32
The changes view does have some level of visual aid for changes:

![image](https://user-images.githubusercontent.com/8343178/62413096-a885aa00-b603-11e9-8f24-98745893a9d9.png)

There are changes, content and situations that the system has troubling diffing & visualising though. I'm sure some improvements can be made to this.

**Comment by bensulli** [comment] 2019-10-25 19:48
Actually I think there's an underlying bug here. Looking at @samtuke 's screenshot, I see the same thing, where the formatting is all weird and only the first few characters of each line are shown.

I can't get it to show the full text with changes like in @ssddanbrown 's screenshot. So I think this might just be a bug with revision display.

Eg, this is a page I did revisions on.
![image](https://user-images.githubusercontent.com/6107886/67599845-c86dcb00-f725-11e9-843c-9988cd612b05.png)

**Comment by samtuke** [comment] 2019-10-26 10:49
Is it to do with PHP server version?

**Comment by bensulli** [comment] 2019-10-28 23:51
Could be? I'm just using Bookstack in docker (https://github.com/linuxserver/docker-bookstack) which I would've thought was a common use case.

PHP 7.2.18 (cli) (built: May  4 2019 16:25:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by setpill** [comment] 2020-04-10 16:12
The diff view is still quite poor in clarity sometimes.

An example is [this demo revision](https://demo.bookstackapp.com/books/lorem-ipsum-dolor/page/my-lorem-ipsum-book/revisions/127/changes). Or [any revision of the examples of different content page](https://demo.bookstackapp.com/books/bookstack-user-guide/page/examples-of-different-content/revisions) is really hard to see because there are so many other things going on.

One option would be to mark changed/deleted/added lines in the margin so that the actual content of the page cannot interfere.

**Comment by ssddanbrown** [comment] 2021-02-12 22:31
Coming back to this, I think the original issue was due to a bug within the php-tidy extension on some systems as discussed here: #1553

The latest release of BookStack no longer uses `php-tidy` so the original issue experienced should no longer be apparent so will therefore close this.

**Closed by ssddanbrown** 2021-02-12 22:31 UTC

**Comment by bensulli** [comment] 2021-02-12 22:33
Confirmed this is fixed in the latest build we're using! Thanks!

**Comment by setpill** [comment] 2021-02-22 08:16
Is the demo up to date? Because in the examples I gave it still is very hard to see what changed/how.
