### ISSUE TITLE
tinymce error in console log

### ISSUE THREAD

**Issue by FredFu0234** [BookStackApp/BookStack#2461] opened 2021-01-07 10:21 UTC
**Describe the bug**
In JS Console I receive an error when editing a page on a fres installed bookstack instance.
The editor seems to be working. But I have no clue if maybe some features are not working.

**Steps To Reproduce**
Install a new Bookstack - login as administrator - create a new page - look into the javascript console.

**Expected behavior**
No errors in the js console.

**Your Configuration (please complete the following information):**
 - Browser: newest Firefox in Ubuntu 20.04
 - Exact BookStack Version: BookStack v0.31.1 
 - PHP Version: 7.4.3
 - Hosting Method: Nginx on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/77101192/103881431-b71a9f80-50da-11eb-83d5-de2719bf30ca.png)

**Comment by ssddanbrown** [comment] 2021-01-09 19:24
Thanks for reporting this @FredFu0234.

I'm having trouble though re-producing this. Do you get this error consistently?
Do you also get this on the demo site? (https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site)

**Comment by FredFu0234** [comment] 2021-01-10 10:16
Yes, it is reproduceable. I think it is related to images. The error comes as soon as I inserted an image.


![image](https://user-images.githubusercontent.com/77101192/104120198-46bb8a80-5335-11eb-9bad-1b4187c1aa64.png)

**Comment by nderambure** [comment] 2021-04-12 22:53
Same error for me : I can't see the Wysiwyg editor when trying to edit a page.

Fresh install of 21.04 locally on PHP 7.4 and MySQL 8.0.23.
I've just created a shelve, then a book and when creating a page, Wysiwyg does not boot.
There is also some 404 alert which are not seen has it in network dev panel of Firefox.

![error_tinymce_bookstack](https://user-images.githubusercontent.com/1145642/114472496-9b9bc500-9bf2-11eb-85d4-cd6cd37f4630.png)

**Comment by ssddanbrown** [comment] 2021-04-12 23:02
Hi @nderambure,
Do you also get this issue on the demo site?: https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site

**Comment by nderambure** [comment] 2021-04-14 02:04
Hello @ssddanbrown : nope the demo works fine !
I really do only a proper install as described in the doc, no fancy stuff.

**Comment by FredFu0234** [comment] 2021-04-20 11:10
Now, the demo is working fine. No errors in the console anymore.

**Comment by ssddanbrown** [comment] 2021-04-20 19:00
Any errors on your own instance? When on the latest version?

I tried to replicate but I've been unable to reproduce the mentioned errors so far.

**Comment by nderambure** [comment] 2021-04-20 22:25
I've just installed the last release 21.04.1 and now I can see and edit with Tinymce, but there is still some problems.

Just to be sure, my vhost is : 

```
<VirtualHost *:80>

        ServerName      test-bookstack.localdev
        ServerAlias     www.test-bookstack.localdev

        DocumentRoot "/Users/nico/www/test-bookstack/test-bookstack.localdev/public"

        <Directory /Users/nico/www/test-bookstack/test-bookstack.localdev/public>
                Options -Indexes +FollowSymLinks +MultiViews
                Require all granted
                AllowOverride All
        </Directory>

        ErrorLog /var/log/apache2/boostack.error.log
        LogLevel error
        CustomLog /var/log/apache2/bookstack.access.log vhost_combined

</VirtualHost>
```

Mod rewrite is up. Then I've ran the install commands in my main folder : 

```
git clone https://github.com/BookStackApp/BookStack.git test-bookstack.localdev --branch release --single-branch
cd test-bookstack.localdev
php artisan key:generate
```

Then fill the .env file and `php artisan migrate`.

Logged in, create a shelve, a book and then a page with the dev tools opened on my Firefox 80.0 (tested in 79 too) on a Mac M1 with PHP 7.4 and MySQL 8.0.23 (via brew).

Randomly, when reloading (without cache) the wysiwyg editor page, I got the same error than before, but it still works somehow.
Note that I also get the error when clicking save and the back to editor, but really less often.

So I've tested in Chrome 90 too, and I get the same behaviour, but not the same error. Here is the Chrome dev tools error : 

![chrome_error](https://user-images.githubusercontent.com/1145642/115469808-96172e00-a235-11eb-9b21-37e19c0afd21.png)

But it still works, which was not the case with 21.04.

I've also noticed another problem with url rewriting, but I'll make another ticket for this.

**Comment by ssddanbrown** [comment] 2022-02-08 20:33
I found this was intermittent in testing as it was timing based (Attempted focus before editor loaded). 
Should now be patched as of current dev branch, and should no longer be an issue from next feature release. Will therefore close this off. Thanks all for your input.

**Closed by ssddanbrown** 2022-02-08 20:33 UTC
Labels: :bug: Bug, :computer: Front-End, :memo: WYSIWYG Editor
