### ISSUE TITLE
Remember me error

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3835] opened 2022-11-08 05:52 UTC
### Describe the Bug

When you authorize and check the "Remember me" checkbox, the authorization flies the next day. Prompt with what it can be connected? The problem appeared a long time ago, but in earlier versions there was no such problem. Where to dig? Cache and cookies are not cleared, the problem is with all users.

### Steps to Reproduce

1. Login and remeber me

### Expected Behaviour

-

### Browser Details

Chrome

### Exact BookStack Version

22.07.01

### PHP Version

8.1

### Hosting Environment

WinServer 2019

**Comment by ssddanbrown** [comment] 2022-11-08 09:03
Hi @Statium, This may be the same scenario as reported in #2985,
Are you also logging into BookStack, using the "Remember me" option, using another device/browser at all?

**Comment by Statium** [comment] 2022-11-10 04:10
@ssddanbrown yes, and the problem is not solved by setting SESSION_LIFETIME

**Comment by ssddanbrown** [comment] 2022-11-10 09:10
Thanks for confirming, I'll therefore close this off as a duplicate of #2985.
The `SESSION_LIFETIME` won't help if using the remember me option, but should provide the ability to stay logged in longer **specifically when not** using the remember me option.

**Closed as completed by ssddanbrown** 2022-11-10 09:10 UTC
Labels: :bug: Bug, :cat2::cat2: Possible duplicate
