### ISSUE TITLE
Chrome autofill tries to fill the page editor with address info

### ISSUE THREAD

**Issue by Isaacntk** [BookStackApp/BookStack#3939] opened 2022-12-30 20:44 UTC
### Describe the Bug

When editing any page, chrome tries to autofill the editor with address info

![image](https://user-images.githubusercontent.com/1376191/210109560-8e39d3e0-5f19-4973-a1fd-64655b710057.png)

### Steps to Reproduce

1. Make sure chrome has address info saved
2. Using markdown page editor
3. Create a new document
4. Click on the Editor area

Autofill pops up in chrome

Additional notes:
- Clicking on the autofill fills the page title with First name and the page with the first letter of last name
- The title input also triggers this behavior

### Expected Behaviour

There should not be an autofill prompt with addresses when clicked

### Browser Details

Chrome Version 108.0.5359.125

### Exact BookStack Version

v22.11

### PHP Version

PHP 7.4.3

### Hosting Environment

Running on an ubuntu VM behind a HTTPS reverse proxy (Bookstack is HTTP only)

**Comment by ssddanbrown** [comment] 2023-02-23 18:03
Just been testing this, but have not been able to get this to reproduce.
Nor can I find report of address autofill occurring in code-mirror inputs like is happening here, nor do we specifically enable any kind of auto-fill for the inputs used here.
I have also not seen any other reports for this.

I can only guess maybe it's a bug in that version of chrome, or maybe there's been an address form-fill in the past for that address autofill entry, that had overly generic names which are also used as input names by BookStack.

**Comment by ssddanbrown** [comment] 2023-03-06 11:41
Since this has been unreproducable, and since I have not had other reports of this, I'll go ahead and close this off.

**Closed as completed by ssddanbrown** 2023-03-06 11:41 UTC
Labels: :bug: Bug

**Comment by Isaacntk** [comment] 2023-03-06 20:06
Hi, sorry to revive this thread, as I didn't notice the previous reply.

I'm pretty sure this isn't chrome version specific as I often update it. I recently updated bookstack as well, which deprecated support for PHP 7.4 so I am now on PHP 8.2

The issue seems to no longer be present for the editor field, but is still present on the title field.

I went ahead and tested this with both Edge and a fresh Chrome profile, before and after adding an address, and they both produce the same result:
- Edge: https://imgur.com/pbuTTf6
- Chrome: https://imgur.com/KE4ioF6

I'm using imgur because github's video compression dropped almost everything useful from the recording
