### ISSUE TITLE
Subscription to sides and enable Email-notifications

### ISSUE THREAD

**Issue by kdagutat** [BookStackApp/BookStack#3834] opened 2022-11-07 16:21 UTC
### Describe the feature you'd like

I want to subscribe a page and get Email-Notifications when ever this side is modified. The same would be create for Books and Shelves.

I found older request of this feature, but they are still open and I couldn't find any solution to it.

When using webhooks its only possible to notify every one about any changes, isn't it?

### Describe the benefits this would bring to existing BookStack users

It would be easier to track changes in topics you care about.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment] 2022-11-07 17:03
Thanks for the request but I'm going to close this off as a duplicate of #241.

> When using webhooks its only possible to notify every one about any changes, isn't it?

Kind of, it really depends on how they're handled. They're not sent from BookStack in a user specific way so any user-specific alerting would need to be done within your own logic/handling.

**Closed as completed by ssddanbrown** 2022-11-07 17:03 UTC
Labels: :cat2::cat2: Possible duplicate
