### ISSUE TITLE
Autosave of the draft does not work after editing the diagram Draw.io

### ISSUE THREAD

**Issue by DimS1872** [BookStackApp/BookStack#3682] opened 2022-08-29 07:35 UTC
### Describe the Bug

If you'll change something on the page, at least one letter, then autosave occurs after 30 seconds.

However, if a Draw.io diagram is embedded on the page, system does not notice changes in it, and autosave does not occur automatically.

The problem is that if the diagram has changed and the page has not been saved, then when the session ends, all changes in the diagram will be lost.

### Steps to Reproduce

1. Open your browser's developer tools, Network tab. 
2. Start editing the existing page containing the diagram draw.io.
3. Double-click on the diagram (Draw.io editor opened). 
4. Edit the diagram.
5. Click the Save button in the diagram editor.
6. In developer tools, expect a "save-draft" request within a few minutes without making changes to the draft.

### Expected Behaviour

After 30 seconds, a "save-draft" request appeared in the browser developer tools

### Browser Details

Firefox 104.0 (64-bit) for Ubuntu 20.04

### Exact BookStack Version

BookStack v22.07.3 

### Hosting Environment

Ubuntu 20.04.4 LTS

**Comment by ssddanbrown** [comment] 2022-08-29 12:19
Hi @DimS1872,
Thanks for reporting but I have not been able to re-produce this.
I have tested with both the WYSIWYG and Markdown page editor.
Are you able to re-produce this on our [demo site](https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site)?

**Comment by DimS1872** [comment] 2022-08-29 12:28
Hi @ssddanbrown,
Yes, this is reproduced on the demo site.

**Comment by ssddanbrown** [comment] 2022-08-29 12:42
Strange. Updated Firefox to 104, to be on the same version, and tested this on our demo site. The draft saved as expected after image edit.

Not really sure where to take this since I have not been able to reproduce the issue.

**Comment by DimS1872** [comment] 2022-08-29 18:49
I will pay attention once again:
Step 5 Click Save in the Chart editor.
After that, the diagram is saved in the draft of the page.
We don't save the draft.
We are waiting for the end of the session.
Log in again.
Open draft editing again.
We will see that the updated diagram is lost, the previous version of the diagram has been restored.
If you look at the folder .../uploads/images/drawio/2022-08/ on the server, then there is a file with a saved diagram. But there is an old version of the diagram on the page.

**Comment by ssddanbrown** [comment] 2022-08-29 18:56
Hi @DimS1872,
Do you have to wait for the session to expire? If so, were you definitely able to re-produce this on our demo site?
I ask because you generally wouldn't have been able to wait for the session to end during the demo reset time, therefore I don't understand how you reproduced the issue on our demo site.

**Comment by DimS1872** [comment] 2022-08-30 07:16
Hi @ssddanbrown ,
After logging into an account on a demo site, you need to open another browser tab with a demo site. It will have the same session.
Edit and save the diagram (but not save the draft) in the first tab.
Wait a minute in the hope that a "save-draft" request will be sent. (But this will not happen)
Go to the second tab and log out of the account in it. The session will end for both the first and second tabs.

**Comment by ssddanbrown** [comment] 2022-08-30 12:20
Hi @DimS1872,
I'm still not able to reproduce this on our demo site.
The "save-draft" request always gets sent after saving the diagram.

- Do you see any errors in the developer console log after editing the diagram and waiting?
- Is the "save-draft" request sent if you add some text after saving the diagram?

**Comment by DimS1872** [comment] 2022-08-30 13:33
Hi @ssddanbrown ,
There are 2 errors in the developer console after editing the diagram and waiting.
The "save draft" request is sent if I add some text after saving the diagram.

I made a video saving the diagram (in a .zip attachment)..
Transcript:
0:20 - Saving the diagram after editing
Next, I'm waiting for the "save-draft" request to be sent
at 1:30 .. 1:55 - viewing the developer console, 2 errors are visible.
There is still no "save-draft" request.
1:59 - entered 1 character from the keyboard into the draft text.
2:07 - the "save-draft" request appeared
[vokoscreenNG-2022-08-30_16-07-24.zip](https://github.com/BookStackApp/BookStack/files/9453218/vokoscreenNG-2022-08-30_16-07-24.zip)

**Comment by ssddanbrown** [comment] 2022-08-30 13:45
@DimS1872 Thanks for confirming, and thanks for the video, it allowed me to follow your exact usage.

Can confirm reproduction. I noticed that even just clicking or moving the cursor in the editor would trigger a draft save, I think I was clicking an empty area instinctively when performing my previous tests.

**Comment by ssddanbrown** [comment] 2022-09-05 14:08
Just committed b698bb0e07689feeb7b80e958bfffa5cf4602423 which should address this issue based upon my testing.
Will be part of the next feature release.

**Closed as completed by ssddanbrown** 2022-09-05 14:08 UTC
Labels: :bug: Bug, :computer: Front-End, :memo: WYSIWYG Editor
