### ISSUE TITLE
Right to Left direction does not affect the collapsible block

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#5135] opened 2024-07-20 07:52 UTC
### Describe the Bug

The block is rendered in LTR direction; its icon is on the left. Also, when defining its label, the strings are translated but rendered in LTR direction.

### Steps to Reproduce

1. Create a collapsible block in the RTL context.
2. The block is in LTR.
3. The labels are LTR.

### Expected Behaviour

I expect the collapsible block to be rendered accordingly.

### Screenshots or Additional Context

The collapsible block icon is on the left:

![1](https://github.com/user-attachments/assets/6bce620e-d548-4e17-a5dc-190fde1a5c58)

The label is in LTR direction:

![2](https://github.com/user-attachments/assets/69072f5d-690d-4cf5-9f72-c88c1ab4c7f9)

### Exact BookStack Version

v24.05.1

**Comment by okaeiz** [comment] 2024-08-18 08:00
@ssddanbrown  Hey there! I noticed the same problem exists when adding hyperlinks. The panel that is opened for editing the hyperlink is neither RTL nor translated. The translation is on our end but I think the RTL should be applied according to the language.
Is it necessary to raise an issue or you will address it the nex milestone?

**Comment by ssddanbrown** [comment] 2024-08-27 13:33
Hi @okaeiz,

Thanks for reporting but I'm unable to reproduce this one, the label and arror render RTL as expected:

![image](https://github.com/user-attachments/assets/e3c30685-596b-49d2-9361-9b596c8a85bc)

I've tested in a variety of browsers (Firefox/Chrome/GnomeWeb).
We are using browser's native rendering here, so I'd be surprised if there are issues but display may depend on browser.

Is this something you can still reproduce? If so, can you confirm which browser you're using?

> Also, when defining its label, the strings are translated but rendered in LTR direction.

Yeah, much of the existing editor controls are not built for RTL presentation.
I'm not going to address these though since this has always been the case, and since I'm currently [working on a new editor](https://github.com/BookStackApp/BookStack/pull/5058) which does aim to have RTL presentation for controls.

**Comment by ssddanbrown** [comment] 2024-11-28 14:14
Since there's been no further follow-up I'll go ahead and close this off.

**Closed as completed by ssddanbrown** 2024-11-28 14:14 UTC
Labels: :bug: Bug
