### ISSUE TITLE
Error when editing an existing page

### ISSUE THREAD

**Issue by ciehanski** [BookStackApp/BookStack#275] opened 2017-01-17 06:40 UTC
### For Bug Reports

* BookStack Version: 0.13.1
* PHP Version: 7.0
* MySQL Version: 5.7.16
* OS: Ubuntu 16.04. I installed using the automated install script from your docs.

##### Expected Behavior
A page that has been edited successfully.

##### Actual Behavior
This error occurs: https://imgur.com/a/mX7e9

If you need any logs/more info just let me know and I will be glad to provide it.

**Comment by ssddanbrown** [comment] 2017-01-17 07:06
Hi @moonjazzz, Sorry to hear you are having issues with pages.

Yeah, Some details of the error would be great. Information on how to see debug messages and/or find logs can be found [here](https://www.bookstackapp.com/docs/admin/debugging/).

**Comment by moonjazzz** [comment] 2017-01-17 07:19
TokenMismatchException in compiled.php line 3153:
`in compiled.php line 3153
at VerifyCsrfToken->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13464
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11907
at StartSession->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13210
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13147
at EncryptCookies->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 9855
at Pipeline->then(object(Closure)) in compiled.php line 8148
at Router->runRouteWithinStack(object(Route), object(Request)) in compiled.php line 8139
at Router->dispatchToRoute(object(Request)) in compiled.php line 8130
at Router->dispatch(object(Request)) in compiled.php line 2472
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3213
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in compiled.php line 9870
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 9855
at Pipeline->then(object(Closure)) in compiled.php line 2416
at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2400
at Kernel->handle(object(Request)) in index.php line 53`

**Comment by moonjazzz** [comment] 2017-01-17 07:20
If it helps, I am serving Bookstack over HTTPS but revieve mixed content errors. However the site loads perfectly and I have not seen any other issues than this one.

**Comment by lommes** [comment] 2017-01-17 10:05
I had similar problems with another laravel app. It there was related to my system and the selected session driver. Maybe any advice mentioned [here](https://github.com/laravel/framework/issues/8172) helps

**Comment by moonjazzz** [comment] 2017-01-17 18:35
@lommes oh wow, that was a hefty read....I'm using the defaults which is file caching.

**Comment by ssddanbrown** [comment] 2017-01-17 18:42
Hey @moonjazzz, Could you post which links are getting mixed content errors? There should be no mixed content errors so the cause of those could be the cause of the session issue.

If you're not sure how to bring up the devtools console to show the errors let me know and I'll guide you through it.

**Comment by ssddanbrown** [comment] 2018-05-12 09:15
Thank you for opening this issue. As part of an issue clean-up we're closing off older support issues that may be outdated or irrelevant so therefore I am closing this issue.

If the issue remains and it is one you are still seeking to actively solve please ensure it is still not apparent on the latest version of BookStack then open up a new issue referencing this one.

Sorry if we were not able to solve your original request.

**Closed by ssddanbrown** 2018-05-12 09:15 UTC
Labels: Type: Instance Issue / Support
