### ISSUE TITLE
PDF Export issue

### ISSUE THREAD

**Issue by Dav31** [BookStackApp/BookStack#392] opened 2017-05-11 12:56 UTC
* BookStack Version: 0.16.2
* PHP Version: 5.6.30
* MySQL Version: 5.5.52-MariaDB

Hi,
Firstly, thank's a lot for this tool.
Secondly, I have an issue with PDF exports.
When I try to export an article as PDF, all images are missing from the file created.

I tried to use WKHTMLTOPDF instead, but without success.

**Comment by ssddanbrown** [comment] 2017-05-28 10:31
Hi @Dav31, Sorry for my late reply. Were the images uploaded via BookStack or are the referencing another website? What OS is your BookStack instance running on? How large are the images?

**Comment by Dav31** [comment] 2017-05-29 12:27
Hi Dan,

No problem for the late.
Yes, the images are on the server where Bookstack is hosted.
My instance is running on a CentOS server vith Ngnix webserver installed.
For the images, this is variable as no images are displayed on the PDF export, whatever how large they are.

**Comment by the4ndy** [comment] 2017-05-31 18:12
I am also experiencing this issue....i have been since starting using Book Stack almost 1 year ago....i, until recently, thought this was just the natural behavior of the PDF export feature (and was actually coming here to request that feature be added).  
  
I am running the latest version of book stack (just updated today) 0.16.2. I am running it on Ubuntu 16.04 (up to date) with an Nginx webserver
php --version = 7.0.18
mysql --version = 14.14 distrib 5.7.18

**Comment by vladime** [comment] 2017-08-04 10:16
Same issue here... Running as a docker container.
Ubuntu 16.04
Docker 17.06.0-ce
Nginx
mysql 5.7.12

**Comment by Alwaysin** [comment] 2017-08-04 10:27
Same here!

Debian 9
PHP 7.0.19-1
10.1.23-MariaDB-9+deb9u1
apache2 2.4.25-3+deb9u2

**Comment by pabloalbrecht** [comment] 2017-08-05 12:42
Same here... also if you export to HTML 
Debian 14, Debian 16
PHP 7 / Nginx

**Comment by ssddanbrown** [comment] 2017-08-06 12:29
Hi @vladime, Are you using the popular solidnerd/docker-bookstack setup for docker or a different setup? A docker setup with this issue would be ideal for me to try to replicate the issue.

**Comment by vladime** [comment] 2017-08-06 15:17
Hi Dan, yes, I am using solidnerd docker with BS 0.17.1. One detail which is might be important: I am using Ngnix, so the whole path looks like this domain.com/wiki/restofthebookstackpath/

**Comment by julienmmm** [comment] 2017-08-21 05:40
Hello,

I am also facing the same issue with the pdf exporter (Install on Fedora 25).

Also note that I have the same issue with the "Web contained file" exporter.

**Comment by Dav31** [comment] 2017-09-07 14:59
Hello,

I just updated to 0.17.4 version.
The issue still occurs.
It seems to be directly linked to NGinx.

Regards.

**Comment by jacksonp2008** [comment] 2017-09-08 13:53
Yes, must be NGINX related.  I see this on behavior on a system that is using NGINX,  but it works fine on the latest docker container without NGINX.

**Comment by nblenkhorn** [comment] 2017-09-11 13:15
I am also seeing this behaviour on Apache. I'm using v0.17.4 as well.

**Comment by megamorf** [comment] 2017-09-12 02:45
I'm also seeing this issue, running https://github.com/solidnerd/docker-bookstack behind Traefik as SSL terminating reverse proxy.

**Comment by ssddanbrown** [comment] 2017-09-23 08:56
Hey everyone, Can someone (That has this issue) please confirm if the 'Contained HTML File' export works for them with images?

Need to know if the issue is in the document creation or PDF rendering code...

**Comment by julienmmm** [comment] 2017-09-23 13:34
Hello,

I am facing the same issue with the self contained html export.

Julien

**Comment by megamorf** [comment] 2017-09-24 14:53
Can confirm, images are also missing with the html export.

**Comment by Dav31** [comment] 2017-09-25 07:36
Hi Dan,

I can confirm this too.
The HTML export doesn't provide us the images.

David

**Comment by ssddanbrown** [comment] 2017-10-06 20:11
Hi all, I've just deployed version v0.18.3 to specifically target this issue. I have an idea at what the problem could be but I'm not sure until it's tested by a few different people but hopefully this patch will get things working. 

I did test this in a local dev container setup where images did not work before but there may be a different issue at play here.

Please let me know how it goes after updating.

**Comment by megamorf** [comment] 2017-10-07 02:06
@ssddanbrown Nice, I'm going to test this tomorrow and let you know 👍

**Comment by megamorf** [comment] 2017-10-07 20:10
@ssddanbrown Getting a `Whoops, looks like something went wrong.` error when replacing ExportService.php with your version. The error log only shows an 500 error for the `GET /books/playground/page/new-page/export/pdf` request.

I hope some other folks can chime in as the addition of docker with a reverse proxy certainly increases complexity.

**Comment by Alwaysin** [comment] 2017-10-08 14:24
It works for me, but I think a previous release already fixed it.

**Comment by julienmmm** [comment] 2017-10-09 06:14
Hello,

After the upgrade to the latest version, all the images in all the documents appear as Broken link images:
![image](https://user-images.githubusercontent.com/24657335/31326350-a31f9320-acc6-11e7-9033-4f41672ce104.png)

But after editing the page and re-uploaded the images, they were correctly displayed and exported in the PDF.

Regarding the upload of images, I've been forced to upload them via the "insert image" button while I was used to do a copy/paste from a screenshot tool before. Now the copy paste does not work and BookStack displays a general error message when trying to upload images this way.
![image](https://user-images.githubusercontent.com/24657335/31326693-ce738ab0-acc9-11e7-8b02-8d7a1ef20b4b.png)

But I suppose it can be the subject of another issue.

**Comment by Dav31** [comment] 2017-10-13 08:30
Hi Dan,

I just updated my BookStack installation, and the PDF export runs just fine now.
Thank you very much for your support.

David

**Comment by aljawaid** [comment] 2017-11-26 12:03
Hello I had the same problem on 0.18.0.  I updated to 0.18.5 and the export to pdf **now works but as per below:**
- you must use uploaded images only
- ctrl+c results in an unknown error, so it doesn't work anymore.
- existing images wont work

**Comment by aljawaid** [comment] 2017-11-29 11:43
Hello,

The only problem now is that the image does not stay (on pdf) in the position it is meant to.

**Comment by adrie-tc** [comment] 2018-01-18 14:11
I am faced with image issues as well, using the export to PDF function.
It produces results as shown by @julienmmm having broken images.
These are with freshly uloaded images however.
Using docker and a reverse proxy (nginx).
The issue (or rather solution) is still unresolved i take it?

**Comment by adrie-tc** [comment] 2018-02-20 12:50
FYI, [beta release v0.20.0](https://www.bookstackapp.com/blog/beta-release-v0-20-0/) seems to have fixed it.
Testing a random sample of PDF exports containing media does not show any issues regarding images anymore.

**Comment by ssddanbrown** [comment] 2018-03-05 20:10
Happy to hear this has been resolved for a good number of instances. Still looks like we're getting bugs though so I'll keep his open for continued discussions.

**Comment by adrie-tc** [comment] 2018-03-06 08:08
I noticed the images coming from the new draw.io integration do not show up in the pdfs.
Instead they get replaced by a crossed out block image.

Normal view and HTML export are fine ofcourse.

**Comment by filipemarinheiro** [comment] 2018-04-05 17:52
Hi, will this work if images are secure, i mean by using the "local_secure_setting"?

**Comment by alexmannuk** [comment] 2020-08-24 20:01
Appears to be fixed in all recent versions on both Apache and Nginx, no updates to the issue since 2018 so can likely be closed.

**Comment by ssddanbrown** [comment] 2021-05-04 20:01
Thanks @alexmannuk.

I'll close this off since the original issue creator expressed that their issue has been since solved.

**Closed by ssddanbrown** 2021-05-04 20:01 UTC
Labels: :bug: Bug
