### ISSUE TITLE
Include Tag Popup Does Not Appear

### ISSUE THREAD

**Issue by bhsmither** [BookStackApp/BookStack#3738] opened 2022-09-20 20:58 UTC
### Describe the Bug

According to:
```
https://www.bookstackapp.com/docs/user/reusing-page-content/
```
there should be a popup. I do not get that action.

### Steps to Reproduce

1. Have the browser's Developer Tools, Console tab open.
2. View any page.
3. Note the error shown on the Console tab.
4. Swipe some text on the page.

### Expected Behaviour

The popup appears.

### Screenshots or Additional Context

The browser console reports:
```
13:20:22.234 Failed to create component TypeError: document.querySelector(...) is null
    importVersioned /dist/app.js?version=v22.09:49
    Do /dist/app.js?version=v22.09:31
    kd /dist/app.js?version=v22.09:49
    ag /dist/app.js?version=v22.09:49
    Id /dist/app.js?version=v22.09:49
    <anonymous> /dist/app.js?version=v22.09:49
 page-display 
<div class="page-content clearfix" page-display="66">
app.js:49:3769
```

### Browser Details

Firefox 104.0.2 Win7-64bit

### Exact BookStack Version

22.09

### PHP Version

8.1.5

### Hosting Environment

Linux Mint 19.3 (Tricia from Bionic)

**Comment by ssddanbrown** [comment] 2022-09-20 21:11
Hi @bhsmither,
Do you experience the same on our demo site?:

https://demo.bookstackapp.com/books/it-department/page/member-onboarding-guide

**Comment by bhsmither** [comment] 2022-09-20 21:30
Visual inspection of the code reveals:
```
let e=document.querySelector('link[href*="/dist/styles.css?version="]')
```
I have put a copy of base.blade.php in the /themes/`my_theme`/layouts folder.

(Being a noob) I used `{{ versioned_asset('dist/customstyles.css') }}` on line 20.

The javascript code here suggests the use of a _quick and dirty_ way to get the apps version value so to populate a querystring for a following `import()` argument.

I will remove the blade file from the /theme/ and make another test.

The demo site works as expected.

**Comment by bhsmither** [comment] 2022-09-20 21:49
Tests show that was the problem.

Line 20 is restored to stock code.

Instead, I created a `custom-styles` language entry for the theme.

**Comment by ssddanbrown** [comment] 2022-09-21 08:50
Happy to hear you found the cause, will therefore close this off.

**Closed as completed by ssddanbrown** 2022-09-21 08:50 UTC
Labels: :bug: Bug
