### ISSUE TITLE
"Override permissions for role" Not Working

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [BookStackApp/BookStack#5034] opened 2024-05-25 15:16 UTC
### Describe the Bug

When attempting to set override permissions per role, the dropdown does not function (displays grey hash lines when role is selected).

### Steps to Reproduce

1. Open Book
2. Select "Permissions" at right side
3. Select a role from the "Override permissions for role" dropdown

### Expected Behaviour

Dropdown should allow role selection so that permissions can be set.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/6394811/89025d98-38e8-44e1-a3a8-3288db7f7938)

### Browser Details

Chrome v125.0.6422.61

### Exact BookStack Version

v24.05.1

**Comment by ssddanbrown** [comment] 2024-05-26 09:49
Hi @MichelfrancisBustillos,
This would indicate an error is occuring on your instance when attempting to select a role.

Are you familiar with browser development tools?
Is so, please open the "console" of the development tools, and then re-create the issue, then share back any messages that appear in the console when attempting to select a role.

**Comment by MichelfrancisBustillos** [comment] 2024-05-26 19:27
I found the issue. HTTP vs HTTPS. Console info below if you still wanted it but I'd say this can be marked as close. Thank you!!

> Failed to load resource: net::ERR_NAME_NOT_RESOLVED		permissions:1 
> 
> Mixed Content: The page at 'https://knowledge.katoteros.org/books/meeting-notes/permissions' was loaded over HTTPS, but requested an insecure element 'http://knowledge.katoteros.org/uploads/images/system/2024-05/6TSamerican-black-bear-ursus-americanus-close-up.webp'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html		permissions:1 
> 
> Error while trying to use the following icon from the Manifest: http://knowledge.katoteros.org/uploads/images/system/202405/6TSamerican-black-bear-ursus-americanus-close-up.webp (Resource size is not correct - typo in the Manifest?)
> app.js?version=v24.05.1:3 Mixed Content: The page at 'https://knowledge.katoteros.org/books/meeting-notes/permissions' was loaded over HTTPS, but requested an insecure resource 'http://knowledge.katoteros.org/permissions/form-row/book/2'. This request has been blocked; the content must be served over HTTPS.Yn @ app.js?version=v24.05.1:3
> app.js?version=v24.05.1:3 
>         
>        Uncaught (in promise) TypeError: Failed to fetch
>     at Yn (app.js?version=v24.05.1:3:1317)
>     at Object.Io (app.js?version=v24.05.1:3:1824)
>     at si.addRoleRow (app.js?version=v24.05.1:4:66290)
>     at HTMLSelectElement.<anonymous> (app.js?version=v24.05.1:4:66127)

**Comment by ssddanbrown** [comment] 2024-05-26 21:16
Good to hear you found the cause! Will therefore close this off.

**Closed as completed by ssddanbrown** 2024-05-26 21:16 UTC
Labels: :bug: Bug
