### ISSUE TITLE
Fresh install and "An unknown error occurred"

### ISSUE THREAD

**Issue by p6002** [BookStackApp/BookStack#4164] opened 2023-04-08 18:48 UTC
### Describe the Bug

I installed the tool using the official docker compose file and documentation. When entering the default password, I get an error:
"An unknown error occurred"

### Steps to Reproduce

Deploy official docker compose

### Expected Behaviour

Running tool

### Screenshots or Additional Context

Screenshot:
https://i.ibb.co/FKPT31B/2023-04-08-204622.png
Compose:
https://pastebin.com/KLtwFv9U

### Browser Details

Latest Edge and Win 11

### Exact BookStack Version

latest

### Hosting Environment

Ubuntu 22 server, docker.

**Comment by ssddanbrown** [comment] 2023-04-08 20:27
> I installed the tool using the official docker compose file and documentation

Just to confirm, there is no "official" docker compose file, or docker image, for release/production use.
The docker images we reference are external community-supported options.

Please follow my video from about 7:28 here to get error detail from the `laravel.log` file: https://youtu.be/6A8hLuQTkKQ?t=448

You'll want to look at the latest logs, after reproducing the error, at the bottom of the file.

**Comment by ssddanbrown** [comment] 2023-04-17 15:38
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.

**Closed as completed by ssddanbrown** 2023-04-17 15:38 UTC
Labels: :bug: Bug
