### ISSUE TITLE
Toggling details sometimes causes snippets to flash and disappear

### ISSUE THREAD

**Issue by trwnh** [BookStackApp/BookStack#1208] opened 2019-01-07 06:06 UTC
**Describe the bug**
Pressing "Toggle Details" on the main page causes snippets to appear and disappear, but sometimes individual snippets disappear immediately after appearing.

**Steps To Reproduce**
1. Click "Toggle Details" to show snippets successfully.
2. Click "Toggle Details" to hide snippets again.
3. Click "Toggle Details" to show snippets again; some of them may flash and disappear.
4. Repeat Steps 2-3.

**Expected behavior**
Showing the snippets should cause them to stay visible; they should not disappear immediately after the animation concludes.

**Screenshots**
![image](https://user-images.githubusercontent.com/10606431/50751502-a7c49b00-120f-11e9-8c82-27c87f32fc54.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.24.3
 - PHP Version: 7.3.0
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
It seems that waiting for a long time in the "hidden" position causes the next click to show the snippets successfully; clicking faster or slower can cause the behavior to become even more unpredictable. I would assume some kind of race condition is causing this bug.

**Comment by ssddanbrown** [comment] 2019-01-12 23:58
Thanks for reporting @trwnh.

Is this only when repeatedly spamming the button? If so, I'm not sure it's worth too much investigation since it's really going to be an infrequent edge-case and the fallout of the issue occurring is minimal.

**Comment by trwnh** [comment] 2019-01-13 00:03
@ssddanbrown Yes, but "repeatedly spamming" can include "clicking to open, then up to 10 seconds later, clicking to close". The exact interval is a bit hard to identify.

**Comment by ssddanbrown** [comment] 2022-01-30 17:03
Just come across this while looking through issues. Tested on current FireFox/Chrome (On Fedora 35) and could not reproduce so I'm assume something may have become more stable in the meantime so I'll close this off. Feel free to re-report with browser specifics if still reproducible though.

**Closed by ssddanbrown** 2022-01-30 17:03 UTC
Labels: :bug: Bug, :computer: Front-End
