### ISSUE TITLE
links created to http targets are automatically converted to https on page save

### ISSUE THREAD

**Issue by jediblair** [BookStackApp/BookStack#3681] opened 2022-08-28 23:04 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

Using the wysiwig tinymce editor, when editing a page and adding a link to a http:// target, upon saving the page, the link is automatically converted to a https:// target. 

Just wondering if there is any way to configure this behavior to turn it off?

I'm assuming this is one of the tinymce plugins but I'm not familiar enough with bookstack to figure out how to edit/disable which plugins are included or not. 

### Exact BookStack Version

v22.07.3

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04, Apache 2.4.52

**Comment by ssddanbrown** [comment] 2022-08-29 12:23
Hi @jediblair,
I have not been able to re-produce this scenario.

- Does this occur for all links? For example, does it occur for `http://example.com`?
- Do you have any browser plugins installed or perhaps any browser features enabled that may force use of https? This is quite common in privacy-focused extensions/browsers.

**Comment by jediblair** [comment] 2022-08-29 12:34
Yeah, seems to happen for all links.
Initially when you add the link it shows as http:// , even in the source code view. 
When the page is saved it changes to https. Have tried on various browsers, same issue, no plugins. 
FWIW I've just recently upgraded from 0.31 , it was happening back on that old version also. so I may try a clean install of 22.07.3 and see if that helps.

**Comment by ssddanbrown** [comment] 2022-08-29 12:39
A clean vs non-clean instance shouldn't really affect things, unless core app files have been edited.
You could test this on [our demo site](https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site) and see if the issue occurs there too.

**Comment by ssddanbrown** [comment] 2022-09-05 12:12
Since there's been no follow-up I'm going to close this. If this is clearly reproducible on our demo instance feel free to provide reproduction steps and this can be re-opened if needed.

**Closed as completed by ssddanbrown** 2022-09-05 12:12 UTC
Labels: :dog2: Support
