### ISSUE TITLE
[Feature Request]: Adding related documents

### ISSUE THREAD

**Issue by mfsid** [BookStackApp/BookStack#3075] opened 2021-11-24 06:49 UTC
### Describe the feature you'd like

I would like an option on a document, preferably below Book Navigation pages, to Add related documents.

Also, the option to insert meta of other pages is ambiguous as I don't know the page ID of every page.

### Describe the benefits this feature would bring to BookStack users

This will help us relate all the documents related to single topic which is already done through Chapters. This option will help users cut down additional noise and only add documents that are related to that specific topic.

**Comment by ssddanbrown** [comment] 2021-11-24 13:01
Thanks for the request @mfsid. I'm going to close this off as I'd consider it a duplicate of #982.

**Closed by ssddanbrown** 2021-11-24 13:01 UTC
Labels: :hammer: Feature Request
