### ISSUE TITLE
set the width of content area with a max, min or dynamic value

### ISSUE THREAD

**Issue by libroc** [BookStackApp/BookStack#3408] opened 2022-05-02 22:49 UTC
### Describe the feature you'd like

- Since people are using more and more large 4k screens/widescreens, it would be nice to be able to set the width of the content area in the middle of the page with a max, min, default or dynamic value (images/tables would scale up).
- Could also be set for the "Page Navigation" column on the left and "Details" column on the right (but not that important).
- Kinda like the online retailer Galaxus/Digitec announced for their shop (https://www.digitec.ch/en/page/galaxus-and-digitec-now-for-widescreen-23475).

### Describe the benefits this would bring to existing BookStack users

- Content better readable.
- More shelves and books displayable.
- Optimized for high resolutions.
- Optimal use of space (reduction of unused space in between).

### Can the goal of this request already be achieved via other means?

- By modification of the CSS files probably.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment] 2022-05-02 23:28
Thanks for the input @libroc.
To be honest, like most design decisions, this can very much come down to preference. 
I prefer to keep the main content within BookStack to a fixed-maxed-width since it somewhat aligns with common print widths and has a read length that most find comfortable, while working to the "Page" paradigm and giving us a fixed with to work to in other aspects (Such as generating full-width image sizes). Although high resolution screens are becoming more popular, in most instances they are scaled up to be equivilent to 1080/1440 sizing.

This was previously discussed in #1757 and you can find some workarounds in there which can be applied without altering any core application files.

**Comment by libroc** [comment] 2022-05-02 23:39
fair enough, but then again, what about to implement just 2 layout setting options for the middle content part: "default" (like now) and "dynamic" (experimental)?

**Comment by ssddanbrown** [comment] 2022-05-03 01:22
Because its not just the effort of adding the option, We are then beholden to support that wider view going forward if added to core, in terms of making other features work with it, handling related support request & feature ideas and in terms of having an extra layout possibilities to support if making design changes in the future. Having a defined max width gives us a something tangable to work to & support. We provide the methods of customization/overriding for such scenarios where tweaks are desired (With expectation of being "experimental") without placing extra burden on the project.

**Comment by ssddanbrown** [comment] 2022-05-09 00:48
Since conversation has come to a close I will close this issue off.

**Closed as completed by ssddanbrown** 2022-05-09 00:48 UTC
Labels: :hammer: Feature Request

**Comment by TonBits** [comment] 2025-10-17 13:44
I think this feature needs to be reconsidered.

I don't know what the primary objective of BookStack was originally if it was designed for creating books and printing it out, which would make sense to keep the width fix.

But if the objective is for online collaboration more than creating a book or to provide alternative to Confluence, then it might be a good idea to revisit this issue (in my opinion)

People seldom print pages, I could be wrong (I rarely print confluence pages for reading) but I am 100% certain that a lot of the users will read content on screen.

With 4k monitors and even wider screen resolutions being the norm, It doesn't really help consuming content with 2/3 of the space not use effectively for reading.
<img width="3840" height="2120" alt="Image" src="https://github.com/user-attachments/assets/deba15e4-6a6e-4308-ab41-b162669ac17b" />

I understand the challenge to support fluid width as a developer myself. But it feels like not able to support fluid width makes it a little bit outdated. Fluid and responsive are kind of a norm when it comes to web. Modern CSS like Bootstrap, Tailwind, supported them out of the box.

I see BookStack as promising alternative to Confluence. But I feel like migrating to BookStack, I will be outdated faster and will be looking for another alternative if it does not keep the pace on modern web designs. 

I will stick with Confluence for now.
