### ISSUE TITLE
Some keywords cannot be searched

### ISSUE THREAD

**Issue by joyhu** [BookStackApp/BookStack#4806] opened 2024-01-26 08:37 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am using the BookStack v23.12 version deployed by docker. When searching, I found that some keywords cannot be searched, as shown in the figure below
![image](https://github.com/BookStackApp/BookStack/assets/608110/b8355430-a46e-469f-857f-b7d3c1d7bed7)

### Exact BookStack Version

23.12

### Hosting Environment

linuxserver/bookstack dcoker image

**Comment by ssddanbrown** [comment] 2024-01-29 18:23
Thanks for raising @joyhu, but I'd consider this a duplicate of existing issue #778 so I'm going to therefore close this off.

**Closed as completed by ssddanbrown** 2024-01-29 18:23 UTC
Labels: :dog2: Support, :cat2::cat2: Possible duplicate
