### ISSUE TITLE
PHP install script for shared hosting

### ISSUE THREAD

**Issue by sangue18** [BookStackApp/BookStack#787] opened 2018-04-09 10:24 UTC
Hi
On our shared hosting, I keep bumping my head while installing, using a subdomaine, and a hosting-given  (maria-)DB.  Since composer is not available and although i can configure .env, the manual install process is pretty unusable for me.
Installing locally and copy to shared hosting is not an option. 
Is there any other way to get this whole thing going or is the (pretty strict) installation process something that comes from the dependency on laravel?

**Comment by ssddanbrown** [comment] 2018-04-21 12:37
Hi @sangue18,
Sorry for the late reply.

I'm afraid it's just the way an app like this is structured, Mostly due to the framework, and the limitations of shared hosting that make this difficult. 

I've posted some more info in a more recent issue #794. 
I'm going to close this one since it's effectively a duplicate of that one. Feel free to respond or add to the conversation on that issue.

**Closed by ssddanbrown** 2018-04-21 12:37 UTC
