### ISSUE TITLE
Update 21.04 -> 21.08 : InvalidArgumentException View [auth.forms.login.standard] not found. (View: /var/www/BookStack/resources/views/auth/login.blade.php) 

### ISSUE THREAD

**Issue by siSSSou** [BookStackApp/BookStack#2909] opened 2021-09-01 16:48 UTC
**Describe the bug**
After update from v21.04 to v21.08, I am unable to log in : 

```
InvalidArgumentException
View [auth.forms.login.standard] not found. (View: /var/www/BookStack/resources/views/auth/login.blade.php) 

auth.forms.login.standard was not found.
Are you sure the view exists and is a .blade.php file?
```
I'm the only user on my instance.
I followed the update documentation (https://www.bookstackapp.com/docs/admin/updates/).

**Expected behavior**
After clearing cache, I expected to be able to log in

**Your Configuration (please complete the following information):**
Environment information
 - Exact BookStack Version (Found in settings): v21.08
 - PHP Version: 7.3.29-1~deb10u1
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by siSSSou** [comment] 2021-09-01 20:31
Hi !
Thanks for your help !

Your instance files do not align with the actual release files (Run git status to check for potential changes) :
```
/var/www/BookStack# git status
Sur la branche release
Votre branche est à jour avec 'origin/release'.

rien à valider, la copie de travail est propre
```
The error does not go away after `php artisan view:clear`.
File /var/www/BookStack/resources/views/auth/login.blade.php exists : 
```
cat /var/www/BookStack/resources/views/auth/login.blade.php
@extends('layouts.simple')

@section('content')

    <div class="container very-small">

        <div class="my-l">&nbsp;</div>

        <div class="card content-wrap auto-height">
            <h1 class="list-heading">{{ Str::title(trans('auth.log_in')) }}</h1>

            @include('auth.parts.login-form-' . $authMethod)

            @if(count($socialDrivers) > 0)
                <hr class="my-l">
                @foreach($socialDrivers as $driver => $name)
                    <div>
                        <a id="social-login-{{$driver}}" class="button outline svg" href="{{ url("/login/service/" . $driver) }}">
                            @icon('auth/' . $driver)
                            <span>{{ trans('auth.log_in_with', ['socialDriver' => $name]) }}</span>
                        </a>
                    </div>
                @endforeach
            @endif

            @if(setting('registration-enabled') && config('auth.method') === 'standard')
                <div class="text-center pb-s">
                    <hr class="my-l">
                    <a href="{{ url('/register') }}">{{ trans('auth.dont_have_account') }}</a>
                </div>
            @endif
        </div>
    </div>

@stop
```

**Comment by ssddanbrown** [comment] 2021-09-01 21:11
@siSSSou Could remain cached due to permissions. You could try deleting any files with a `.php` extension from the `storage/framework/views` directory within your BookStack installation.

**Comment by siSSSou** [comment] 2021-09-01 22:13
@ssddanbrown : deleted all php files in storage/framework/views : no change.
Manually erased all folders in storage/framework/cache : no change
;-(

**Comment by ssddanbrown** [comment] 2021-09-02 19:45
@siSSSou Very odd, I really don't know where that view reference in your originally posted error is coming from then. 

Does the error page/log provide any more context about exactly where the error is arising from?

**Comment by T1ct4c** [comment] 2021-09-04 17:41
I think i´ve got an similar issue:

After updating from 21.04.06 to 21.08 occurs an error after login that an unknown error occurred.

I could not update via git so I copied the new files in the BookStackApp directory.

After changing APP_DEBUG=true in .env file:

> (Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'usr_p470969_7.mfa_values' doesn't exist (SQL: select exists(select * from `mfa_values` where `mfa_values`.`user_id` = 5 and `mfa_values`.`user_id` is not null) as `exists`) in file /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 669

>#0 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('select exists(s...', Array, Object(Closure))
#1 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run('select exists(s...', Array, Object(Closure))
#2 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2419): Illuminate\Database\Connection->select('select exists(s...', Array, true)
#3 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1385): Illuminate\Database\Query\Builder->exists()
#4 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call('exists', Array)
#5 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(385): Illuminate\Database\Eloquent\Relations\Relation->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'exists', Array)
#6 /html/BookStackApp/app/Auth/Access/Mfa/MfaSession.php(15): Illuminate\Database\Eloquent\Relations\Relation->__call('exists', Array)
#7 /html/BookStackApp/app/Auth/Access/LoginService.php(134): BookStack\Auth\Access\Mfa\MfaSession->isRequiredForUser(Object(BookStack\Auth\User))
#8 /html/BookStackApp/app/Auth/Access/LoginService.php(37): BookStack\Auth\Access\LoginService->needsMfaVerification(Object(BookStack\Auth\User))
#9 /html/BookStackApp/app/Auth/Access/LoginService.php(159): BookStack\Auth\Access\LoginService->login(Object(BookStack\Auth\User), 'standard', false)
#10 /html/BookStackApp/app/Http/Controllers/Auth/LoginController.php(150): BookStack\Auth\Access\LoginService->attempt(Array, 'standard', false)
#11 /html/BookStackApp/app/Http/Controllers/Auth/LoginController.php(119): BookStack\Http\Controllers\Auth\LoginController->attemptLogin(Object(BookStack\Http\Request))
#12 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): BookStack\Http\Controllers\Auth\LoginController->login(Object(BookStack\Http\Request))
#13 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('login', Array)
#14 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(BookStack\Http\Controllers\Auth\LoginController), 'login')
#15 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#16 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#17 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(BookStack\Http\Request))
#18 /html/BookStackApp/app/Http/Middleware/CheckGuard.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#19 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\CheckGuard->handle(Object(BookStack\Http\Request), Object(Closure), 'standard', 'ldap')
#20 /html/BookStackApp/app/Http/Middleware/RedirectIfAuthenticated.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#21 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\RedirectIfAuthenticated->handle(Object(BookStack\Http\Request), Object(Closure))
#22 /html/BookStackApp/app/Http/Middleware/Localization.php(80): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#23 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\Localization->handle(Object(BookStack\Http\Request), Object(Closure))
#24 /html/BookStackApp/app/Http/Middleware/RunThemeActions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#25 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\RunThemeActions->handle(Object(BookStack\Http\Request), Object(Closure))
#26 /html/BookStackApp/app/Http/Middleware/CheckEmailConfirmed.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#27 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\CheckEmailConfirmed->handle(Object(BookStack\Http\Request), Object(Closure))
#28 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#29 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(BookStack\Http\Request), Object(Closure))
#30 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#31 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(BookStack\Http\Request), Object(Closure))
#32 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#33 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(BookStack\Http\Request), Object(Closure))
#34 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#35 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(BookStack\Http\Request), Object(Closure))
#36 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#37 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(BookStack\Http\Request), Object(Closure))
#38 /html/BookStackApp/app/Http/Middleware/ApplyCspRules.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#39 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\ApplyCspRules->handle(Object(BookStack\Http\Request), Object(Closure))
#40 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#41 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(BookStack\Http\Request))
#43 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(BookStack\Http\Request), Object(Illuminate\Routing\Route))
#44 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(BookStack\Http\Request))
#45 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(BookStack\Http\Request))
#46 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(BookStack\Http\Request))
#47 /html/BookStackApp/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#48 /html/BookStackApp/app/Http/Middleware/TrustProxies.php(41): Fideloper\Proxy\TrustProxies->handle(Object(BookStack\Http\Request), Object(Closure))
#49 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\Http\Middleware\TrustProxies->handle(Object(BookStack\Http\Request), Object(Closure))
#50 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#51 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(BookStack\Http\Request), Object(Closure))
#52 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#53 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(BookStack\Http\Request), Object(Closure))
#54 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#55 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(BookStack\Http\Request), Object(Closure))
#56 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#57 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#58 /html/BookStackApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(BookStack\Http\Request))
#59 /html/BookStackApp/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(BookStack\Http\Request))
#60 {main})

**Comment by ssddanbrown** [comment] 2021-09-05 13:18
@T1ct4c That error seems to state you're missing one of the new tables. You either havn't copied in the latest files in the `database/migrations` folder or you haven't run the migration command after updating the files.

**Comment by T1ct4c** [comment] 2021-09-05 13:45
Thank you @ssddanbrown, it was the missing migration command.

**Comment by ssddanbrown** [comment] 2021-09-18 20:43
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Closed by ssddanbrown** 2021-09-18 20:43 UTC
