### ISSUE TITLE
Add an extra summary field for pages

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1169] opened 2018-12-10 10:27 UTC
Currently there is an automated preview of page content that is shown in the list view, but this does not always provide the best informations (see also #498) because its just an extract from the first X letters and so does not represent the whole content.

With an extra summary field, page authors could describe in their own words what this page (should) imply. The summary could also be shown beneath the title headline, this would be best optin/optout with an extra checkbox.

**Comment by ezzra** [comment] 2018-12-10 11:41
there is a very similar request in #1169

**Comment by ssddanbrown** [comment] 2018-12-10 12:41
Thanks for the suggestion @ezzra.

I'll close this as a duplicate of #1126 and I'll update the title of the remaining issue to be more generic.

**Closed by ssddanbrown** 2018-12-10 12:41 UTC
