### ISSUE TITLE
Create relative (not absolute) URLs in image linking and wiki type internal linking

### ISSUE THREAD

**Issue by kdamianakis** [BookStackApp/BookStack#5141] opened 2024-07-27 20:40 UTC
### Describe the feature you'd like

At the moment both images and internal links are described by a full domain name URL - this is potentially problematic if the domain of the bookstack deployment changes as there is no easy way (unless changing things in the database) to update all of the relative links.

### Describe the benefits this would bring to existing BookStack users

Assist considerably in changing the fully qualified domain name of the installaiton, which some times needs to happen when changing servers or when the domain name no longer describes correctly the new state of the bookstack entries.

### Can the goal of this request already be achieved via other means?

The database can be manually altered but that requires scripts that may miss data dependencies.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment] 2024-07-27 22:15
Thanks for raising @kdamianakis, but I'm closing this off as a duplicate of existing issues #1137 and #1342.

> Assist considerably in changing the fully qualified domain name of the installaiton, which some times needs to happen when changing servers or when the domain name no longer describes correctly the new state of the bookstack entries.

We specifically cater for this scenario with the "Update System URL" command detailed here: https://www.bookstackapp.com/docs/admin/commands/#update-system-url
This will update all references in table columns where URLs may exist.

**Closed as completed by ssddanbrown** 2024-07-27 22:15 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
