### ISSUE TITLE
Page not found when "|" is saved

### ISSUE THREAD

**Issue by alvaropc** [BookStackApp/BookStack#2192] opened 2020-07-20 07:52 UTC
Hi!
I am currently in v0.28.3 and I found a bug today.
When saving a page where I wrote "|" (with double quotes, literally "|") the page is not saved and I am redirected to a page not found error:
![image](https://user-images.githubusercontent.com/25221111/87912818-51742180-ca6e-11ea-92a1-6f6137164bbe.png)

**Steps To Reproduce**
1. Create a new page
2. Type: "|"
3. Try to save the page

I can not give you further details about the configuration of BookStack because I am just an user, but if you want to know something I can try to ask to the project admins!

Thank you very much!

**Comment by mateja82** [comment] 2020-07-20 08:09
Hey, same happened to me a few days ago!

I discovered this a few days ago, and it doesn't really happen in all documents, just some. So far, it seems pretty random, it tends to happen in the pages where there is some code.

**Comment by ssddanbrown** [comment] 2020-07-25 09:16
Thanks for reporting and confirming this both!

Unfortunately, I have not been able to replicate this on my dev instance. Just to confirm a few things:

- On step 2 of the "Steps to Reproduce", Where are you typing that?
- What editor are you using? The standard WYSIWYG editor or the Markdown editor?

**Comment by alvaropc** [comment] 2020-08-06 06:59
Hi again!
Sorry for the delay! 

I write the "|" thing in the text editor as you can see in the image:
![image](https://user-images.githubusercontent.com/25221111/89498751-27856380-d7bf-11ea-98f6-89fbd62b33ec.png)

When I click in the "save page" button it redirects me to the "Page not found" page I showed before.

About the editor, we are using the Markdown editor.

Hope it helps!

Thank you!

**Comment by ssddanbrown** [comment] 2020-08-06 21:12
Thanks for the extra information @alvaropc.

Unfortunately, I'm still unable to replicate this, even if I go back to v0.28.2. 
Can you provide any details regarding your setup? PHP Version? Webserver? Operating System that BookStack is running on?

**Comment by alvaropc** [comment] 2020-08-10 10:00
Hi!
I am sorry but the admin of the bookstack instance I am using will not be available until 24th of august.

I will try to get the info you need but if I can not we should have to wait until then.

Sorry because of the inconvenience!

**Comment by alexmannuk** [comment] 2020-08-24 16:57
Unable to reproduce in v0.28.3 using Apache on Ubuntu 18.04 with PHP 7.2.24.

**Comment by ssddanbrown** [comment] 2020-12-10 23:12
I'm going to close this off for now but if anyone is able to re-produce consistently (and ideally on the demo.bookstackapp.com site) feel free to open a new issue, referencing this one, so we can take a deeper look.

**Closed by ssddanbrown** 2020-12-10 23:12 UTC
Labels: :mag: Testing required
