### ISSUE TITLE
Recent user activity does not show deleted items

### ISSUE THREAD

**Issue by Venkinovec** [BookStackApp/BookStack#2102] opened 2020-05-06 09:26 UTC
**Describe the bug**
I cannot see items that I deleted on my user profile.
Instead of showing the delete action, it removes the action of my created page, like it never existed.

**Steps To Reproduce**
1. Create book
2. Check history
3. Delete book
4. Check history
5. Not showing delete action

**Expected behavior**
Show delete action on my user profile.

**Screenshots**
![Image](https://user-images.githubusercontent.com/25304952/81160988-2019a880-8f8b-11ea-8518-caed2e6023e1.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.29.2

**Additional context**
I tried it with bookshelves, books, pages, chapters. All delete actions not showed.

**Comment by ssddanbrown** [comment] 2020-05-14 22:52
Hi @Venkinovec,
This is kind of by design. Since the items are no longer there we can no longer calculate permissions on them so we don't show those activities, to avoid exposing potentially private information.

The activity is still within the database though. More detail about this can be found in #1167. Since this is effectively a duplicate of #1167 I will close this.

**Closed by ssddanbrown** 2020-05-14 22:52 UTC
Labels: :cat2::cat2: Possible duplicate
