### ISSUE TITLE
v0.27.0 baseUrl -> url function issue

### ISSUE THREAD

**Issue by neoty** [BookStackApp/BookStack#1613] opened 2019-09-01 04:37 UTC
**Describe the bug**
All links on the web page have been changed to http

**Steps To Reproduce**
1. Clone release branch (or download release archive 0.27.0)
2. Server on nginx(https) -> docker(http) proxy
3. when access to home page, all links changed to http 
browser warning https site but load http resource

**Expected behavior**
all resource load fine

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.0
 - 443 - nginx -> 80 nginx+php-fpm docker

**Additional context**
Previously, the way to get url was to call baseUrl. In this distribution, it is changed to url function. It seems to be related to this.

.env content
APP_URL=https://wiki.seq.kr

<img width="810" alt="스크린샷 2019-09-01 오후 1 33 30" src="https://user-images.githubusercontent.com/19975402/64071886-3f0ac100-ccbf-11e9-8fae-b39549335857.png">

**Comment by neoty** [comment] 2019-09-01 04:40
<img width="810" alt="스크린샷 2019-09-01 오후 1 33 30" src="https://user-images.githubusercontent.com/19975402/64071847-11714800-ccbe-11e9-826d-f9f696a64762.png">

**Comment by ssddanbrown** [comment] 2019-09-01 09:21
Hi @neoty, 
Did you manage to resolve this one? Your site seems to be using the https links as expected right now.

**Comment by neoty** [comment] 2019-09-01 10:44
@ssddanbrown 
Yes I solved
But that's temporary.


`
cd /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation
vi helpers.php

line 934
before -> return app(UrlGenerator::class)->to($path, $parameters, $secure);
after -> return app(UrlGenerator::class)->to($path, $parameters, true);

and it works.

`

**Comment by ssddanbrown** [comment] 2019-09-01 11:18
@neoty Thanks for the details and thanks for originally reporting. 

I've pretty sure I've managed to find the cause of this and have updated BookStack with a fix and test to cover:
7a4425473b61007f6eee51a3f794f5908cd2ccd8

I've just deployed v0.27.2 to include this. Would you be able to revert your change, update & let me know if this release solves the issue for you?

**Comment by neoty** [comment] 2019-09-01 11:40
@ssddanbrown 

I applied to v0.27.2 and the issue seems to be resolved on my site.
Thank you for your hard work.

**Comment by ssddanbrown** [comment] 2019-09-01 11:43
Awesome, Thanks for checking! Will therefore close this.

**Closed by ssddanbrown** 2019-09-01 11:43 UTC
Labels: :bug: Bug
