### ISSUE TITLE
[Bug Report]: Search function isn't finding Japanese characters

### ISSUE THREAD

**Issue by EscoNomad** [BookStackApp/BookStack#3178] opened 2022-01-19 07:45 UTC
### Describe the Bug

Hi there, I recently set up a BookStack for my bi-lingual company which is based in Japan. I absolutely love the software so far, and will definitely support it- it's exactly what a remote team needs!

After putting up some sample pages, I've been testing the features and have encountered an issue where some Japanese character strings (both individual words and sentences) can be found with search (full titles, words at the beginning of sentences), but other character strings yield no results (other words which are in the article, including words after punctuation).

This occurs even when copying and pasting individual characters and/or sentence pieces directly from the article.

This is not the case with any of the english searches I have tried.

I am able to provide a login to our BookStack for testing if needed. Any help is appreciated!

### Steps to Reproduce

1. Enter a search term that is a word that appears within a sentence in a Japanese page.
2. No results are found.

### Expected Behaviour

The search is able to produce the relevant results.

### Screenshots or Additional Context

<img width="1275" alt="Screen Shot 2022-01-19 at 16 39 51" src="https://user-images.githubusercontent.com/98012886/150085806-05a0d587-43fb-4495-b6ac-76d5f086b2d3.png">
<img width="1269" alt="Screen Shot 2022-01-19 at 16 39 42" src="https://user-images.githubusercontent.com/98012886/150085819-5299b60f-6b64-4a1c-9f1b-57b0b49d0f46.png">
<img width="1271" alt="Screen Shot 2022-01-19 at 16 39 21" src="https://user-images.githubusercontent.com/98012886/150085826-d41f9f6f-12cd-422f-9446-42b2d5b8f5a9.png">
<img width="1273" alt="Screen Shot 2022-01-19 at 16 39 12" src="https://user-images.githubusercontent.com/98012886/150085829-7da0325f-a99a-412d-a3de-4fb5f5e80f1a.png">

### Exact BookStack Version

v21.12.2

### PHP Version

7.4

### Hosting Environment

Dreamhost VPS Debian GNU/Linux 10

**Comment by ssddanbrown** [comment] 2022-01-19 10:38
Thanks for reporting @EscoNomad.
I'd consider this a duplicate of #778 and  #1037. Will therefore close this off.
My comment here provides insight as to why this currently occurs: https://github.com/BookStackApp/BookStack/issues/778#issuecomment-564754535

**Closed by ssddanbrown** 2022-01-19 10:38 UTC
Labels: :bug: Bug
