### ISSUE TITLE
Error parsing MD Text

### ISSUE THREAD

**Issue by KarstenHahn** [BookStackApp/BookStack#4820] opened 2024-01-31 14:35 UTC
### Describe the Bug

Hello,
if I enter some special text in the MD Editor, a white screen appears. No log information is available.

I also tried it on your demo-bookstack Instance an can reproduce the error

### Steps to Reproduce

* Edit a page
* Enter this:
#### Steps:
1. Download agent 
```bash
wget https://abc
```
as an example
* save page
* white screen appears.

### Expected Behaviour

saving with no errors will be done

### Browser Details

Edge, Firefox

### Exact BookStack Version

BookStack v23.12.1

**Comment by KarstenHahn** [comment] 2024-01-31 14:39
In addition: I've seen that the problematic MD text will be rendered in GITHUB issue, I've added the MD as an attachment
[md.txt](https://github.com/BookStackApp/BookStack/files/14113016/md.txt)

**Comment by ssddanbrown** [comment] 2024-01-31 14:47
Hi @KarstenHahn,
Thanks for raising.
Strange though, I cannot reproduce this on my dev instance, nor our demo instance; All works fine.

Tested via both creating and updating a page, in both Firefox and Chrome.

**Comment by KarstenHahn** [comment] 2024-01-31 14:56
Hello,
mysterious. I have tested it again, it works on my instance and on the demo instance.
Maybe a problem with the character set when copying from the clipboard? 
Never mind. Now it works. 
Thanks for the quick response and best regards, Karsten

**Comment by ssddanbrown** [comment] 2024-01-31 15:07
Good to hear it's now working.
I'll therefore close this off.

**Closed as completed by ssddanbrown** 2024-01-31 15:07 UTC
Labels: :bug: Bug
