### ISSUE TITLE
Dotted outline when clicking on a button/link

### ISSUE THREAD

**Issue by clafee** [BookStackApp/BookStack#1738] opened 2019-10-23 10:30 UTC
Hello, 

First of all thank you for this wonderful application !

**Describe the bug**
I upgraded from 0.26.4 to 0.27.5, and now I have a dotted outline when I click on anything clickable. The outline disappears after the content has loaded

**Steps To Reproduce**
1. Click on any clickable button, for example the logo at the top left
2. When clicking, a dotted outline will appear around the button that's been clicked
3. After the page is loaded, the outline disappears.

**Expected behavior**
No outline when clicking on anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/56917624/67383725-0b963580-f590-11e9-8542-ade859812372.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.5
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache (used pre-made script on Ubuntu 18)

Thanks !

**Comment by james-geiger** [comment] 2019-10-23 15:38
Duplicate of #1678 

Hi @clafee --

This was an intentional change made between v 0.26.x and v 0.27.x outlined in the issue I mentioned.

It was done to increase accessibility.

**Comment by ssddanbrown** [comment] 2019-10-23 18:23
Hi @clafee,
As suggested above there were some intentional changes in v0.27 to increase accessibility of the platform. That said, The sizing of the outline shown in the screenshot is much larger than I'd expect.

Could you confirm the following:

- Please confirm your exact browser and operating system version.
- Please confirm if you also see the same focus style on the [demo site](https://demo.bookstackapp.com/).

**Comment by clafee** [comment] 2019-10-24 06:26
Sorry, I tried to search before posting, guess it wasn't enough.

Here are your answers @ssddanbrown 

**Please confirm your exact browser and operating system version.** I tried on Firefox 69.0.3, Microsoft Edge 42.17134.1.0, Vivaldi 2.2.1388.34 (I haven't updated this one in a while). All of that on Windows 10
What I didn't notice is the outline that is a different size between the first two browsers and Vivaldi.

**Please confirm if you also see the same focus style on the demo site.**
Here's what I have on Firefox 69.0.3 on the demo site:
![image](https://user-images.githubusercontent.com/56917624/67458925-a5fd8400-f637-11e9-95c8-9d7e660725bd.png)

And here's what I have on Vivaldi 2.2.1388.34:
![image](https://user-images.githubusercontent.com/56917624/67458866-8a927900-f637-11e9-8613-9f8f5088346b.png)

Based on what you said, I believe it all looks normal, sorry for wasting you time, and thanks again for this great software !

**Comment by dannyhanes** [comment] 2019-11-25 18:08
Adding on to this, I am all for supporting accessibility, but perhaps there could be a toggle within the settings to enable / disable accessibility features. For me it looks a little silly. 

<img width="833" alt="Screen Shot 2019-11-25 at 1 07 26 PM" src="https://user-images.githubusercontent.com/3778687/69566215-9b127800-0f84-11ea-8c6a-b8f55c4d7fe3.png">

**Comment by rohithb** [comment] 2019-11-26 15:11
If you want to turn it off, just add 
```
<style>
*:focus {
    outline-style: none;
}
</style>
```
in **Custom HTML Head Content** under settings.

**Comment by dannyhanes** [comment] 2019-11-26 15:20
@rohithb Well that was easy enough, thanks!!

**Comment by ssddanbrown** [comment] 2019-12-16 13:20
Thanks @james-geiger for the suggestion. I've applied some sensible default values in commit a9634b6b6625c98448cd1a1927b9b7d6b1609757. These will be part of the next release (v0.28) which is targeted for release at the end of the year. 

If anyone would like to disable outlines completely please follow the suggestion from @rohithb above but please keep in mind that outlines may be important for some of your users, both those with visual impairments and also those that like to navigate by keyboard.

**Closed by ssddanbrown** 2019-12-16 13:20 UTC
Labels: :art: Design, :computer: Front-End, :hammer_and_wrench: Enhancement
