### ISSUE TITLE
No Scrollbar in the Attachments

### ISSUE THREAD

**Issue by CrackedBatch** [BookStackApp/BookStack#3913] opened 2022-12-12 17:35 UTC
### Describe the Bug

We are having the same issue as described in issue #3789 (https://github.com/BookStackApp/BookStack/issues/3789).
We have a lot attachments that have been added and the scrollbar is not working. Using the scroll wheel on the mouse does not work either.

I have attempted to apply the custom html, but I have not able to make it work with any chrome based browsers or Firefox.

### Steps to Reproduce

1. Go to Page
2. Click Edit
3. Click on the "Paper Clip" button
4. See the list of attachments, but can not scroll down, to see the rest of the items.

### Expected Behaviour

1. Go to Page
2. Click Edit
3. Click on the "Paper Clip" button
4. See the list of attachments.
5. Able to scroll through uploaded items.

### Browser Details

Google Chrome Version 108.0.5359.99 (Official Build) (64-bit) on Windows 10

### Exact BookStack Version

22.11

### PHP Version

PHP 8.1.2

### Hosting Environment

Ubuntu Server 22.04.1 LTS on VMWare ESXi 7.3

**Comment by mannydaniel** [comment] 2022-12-16 16:52
This happed to us as well. The scenario can be reproduced at the demo page for Bookstack.  Items on the side panel couldn't be scrolled. Testing v22.11 before deployment and this so far has been a hurdle. It was working fine on v22.09.

**Comment by ssddanbrown** [comment] 2022-12-16 23:00
Thanks for reporting, but I'm going to close this off as a duplicate of existing issue #2887.

**Closed as completed by ssddanbrown** 2022-12-16 23:00 UTC
Labels: :bug: Bug, :cat2::cat2: Possible duplicate
