### ISSUE TITLE
Mail sendinng fails with exim

### ISSUE THREAD

**Issue by bash-stack** [BookStackApp/BookStack#2384] opened 2020-11-23 00:14 UTC
**Describe the bug**
fails to send via exim4

**Steps To Reproduce**
console , install recent version ,
enable smtp in env file

send test mail under settings>maintainance

4. See error on top right

` Error thrown when sending a test email: Expected response code 250 but got code "501", with message "501 Syntactically invalid HELO argument(s) "`

**Expected behavior**
SEND MAIL

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.30.4 
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): docker->nginx->nginx

**Additional context**

**Comment by ssddanbrown** [comment] 2020-11-25 22:53
Hi @bash-stack,
Unfortunately I don't have much experiencing with exim. 
Looks like this is a fairly common issue there.
Might be worth going through the causes listed here for validation: https://confluence.atlassian.com/confkb/getting-501-syntactically-invalid-helo-argument-error-when-sending-mail-from-confluence-226790155.html

- Do you have other services using exim to confirm if this is a specific issue to your BookStack instance? 
- What host/container is exim located in relation to bookstack?
- Can you share all possible, non-private, mail configuration set?

**Comment by ssddanbrown** [comment] 2021-02-11 23:21
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Closed by ssddanbrown** 2021-02-11 23:21 UTC
Labels: :dog2: Support
