### ISSUE TITLE
Webhook for user search and API endpoint for user search requests

### ISSUE THREAD

**Issue by MrLeaw** [BookStackApp/BookStack#5304] opened 2024-11-03 09:06 UTC
### Describe the feature you'd like

1. It would be nice to have a webhook that fires on every search request made by a user, and/or an API endpoint which responds with all search requests in a given timespan (last 24 hours, ...)

### Describe the benefits this would bring to existing BookStack users

We would like to check what our employees are looking for, and use this data to analyze how we can improve the layout of the wiki, which keywords we could add to pages 

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment] 2024-11-03 12:57
Thanks for the request @MrLeaw, but I'm going to close this off as a duplicate of existing issue #1000 since I feel the fundamental request (insight into search terms) is much the same and this would be an extension of supporting that.

> Can the goal of this request already be achieved via other means?
> no

As some other ways this could be achieved:

- You could scan/extract this from webserver access logs, extract the query parameters from the URL of search requests.
- You could use an external analytics solution (plausible, Google Analytics, Fathom etc...) to track/record this info.

**Closed as completed by ssddanbrown** 2024-11-03 12:57 UTC
Labels: :cat2::cat2: Possible duplicate
