### ISSUE TITLE
Per page Public flag

### ISSUE THREAD

**Issue by Vicvinegar0** [BookStackApp/BookStack#979] opened 2018-08-21 23:37 UTC
Sorry I did not see any submissions regarding this, if it's already been brought up.

I wanted to suggest having an option for each page to make it public/private, instead of making the whole site public or requiring a public user login.

**Comment by ssddanbrown** [comment] 2018-08-23 19:04
Hi @Vicvinegar0,

Is is kind of possible to do this. Non-logged-in visitors receive the `Public` role. You can make the whole site public but then adjust permissions for this role. Removing the 'View' permissions on items should prevent them seeing anything by default.

For items you do want them to see you can then set custom permissions per book, chapter or page to allow the 'public' role to view. Permissions to trickle down from Books > Chapters > Pages.

The only annoying thing at the moment is that when you select custom permissions on a book/chapter/page you have to set them for all roles (Apart from admins) but this is something I want to improve in the future.

**Comment by thomasmoors** [comment] 2022-06-10 05:50
Hi, could it be this feature is no longer working as intended? I have 2 pages that have public viewing assigned, but are still not visible without logging in.

**Comment by ssddanbrown** [comment] 2022-06-10 12:14
@thomasmoors Is public access enabled in your BookStack settings?:

![image](https://user-images.githubusercontent.com/8343178/173062056-853a2e17-6633-42d6-9ee9-17d0039bbb82.png)

**Comment by thomasmoors** [comment] 2022-06-13 10:18
> @thomasmoors Is public access enabled in your BookStack settings?:

But then everything is public, so maybe I misunderstood? I would like to create "opt-in" public pages. Not opt-out.

**Comment by ssddanbrown** [comment] 2022-06-13 11:14
@thomasmoors Yes, but the public access can be controlled via the Guest user as per the message shown for the option. Please see my original 2018 comment above for achieving an opt-in style public setup.

**Comment by thomasmoors** [comment] 2022-06-14 07:52
Thank you for your awesome work and active support, I know it's not "nothing".

**Comment by ssddanbrown** [comment] 2022-11-08 11:02
I'm going to go ahead and close this off since there's been relatively little demand since opening.
I still intend to implement #288 in the future. Between that and the above explained setups, I think that can cover most use-cases.

**Closed by ssddanbrown** 2022-11-08 11:02 UTC
Labels: :factory: Back-End, :hammer: Feature Request
