### ISSUE TITLE
[ISSUE] Move & Copy Pages are missing newly added books and chapters

### ISSUE THREAD

**Issue by boonduck** [BookStackApp/BookStack#2504] opened 2021-01-21 20:42 UTC
It's probably me, but I am have trouble moving pages. When I try to move or copy a page, newly added books do not show up in the Move Page or Copy Page. They are missing from the list of possible destinations to move or copy the page to. 
They do show up when navigating Shelves and Books in the top menu bar.
I noticed that if I create a new book or chapter on the [BookStack Demo Site](https://www.bookstackapp.com/#demo), the newly created book or chapter IMMEDIATELY SHOWS UP in the Move Copy or Copy Page. 
So the cause of the issue must be related to my specific configuration. 
That made me upgrade to latest version v0.31.4, without luck: I still do not see newly added book, chapters and even some existing chapters in existing books.
I am using a clean install of BookStack v0.30.4 (now upgraded to v0.31.4) running under Ubuntu 18.04 with Apache 2.4.29, PHP 
7.4.14 and MySQL 5.7.32. 
I tried:
- clearing the cache and view
- switching from MEMCACHED to REDIS to store sessions and cache
- regenerating the search index
- restarting Apache2
all to no avail.

Does anybody has a clue to what is going on?

--boonduck

**Comment by ssddanbrown** [comment] 2021-01-21 22:51
Hi @boonduck,

By default, when no search term is provided, that interface will show the 20 most popular items of relevant type. On the demo site there's only a few books and shelves hence newly added items will tend to show up.

Could it be that you may many more items in your instance hence there's always 20 items more popular than the newly create book/chapter?

**Comment by boonduck** [comment] 2021-01-21 23:01
What a coincidence :) I just read in the online documentation on BookStackApp.com > Documentation > Common Functions > Searching Content > Move & Link selection > **When choosing to move a page/chapter** or when selecting a page/chapter/book to link to within the editor **the most popular items are shown** but you also have the ability to search. 
You bet that I have waaaaaayyy more shelves, books, and chapters then the demo has. The documentation is right: typing a few characters is enough to bring up the books and chapters I am looking for. That explains it. Thanks, Dan!

**Comment by ssddanbrown** [comment] 2021-02-02 00:38
Since the behavior here was confirmed I'll close this off.

**Closed by ssddanbrown** 2021-02-02 00:38 UTC
