### ISSUE TITLE
Shelf is deleting when set individual rights

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2903] opened 2021-08-31 11:04 UTC
**Describe the bug**
When I create a new shelf and save it, the shelf is there. If I set custom rights on it and click safe there comes a message that shelf is not there. After reloading I look on all shelfes and it is away ...  

**Steps To Reproduce**
1. New shelf -> save it
2. Edit Right and set custom rights
3. Click Save
4. Shelf is not avaible

**Screenshots**
![2021-08-31 13_02_41-Window](https://user-images.githubusercontent.com/67209365/131491602-d318f349-9a45-4b9a-afde-49e1dedfad32.png)
![2021-08-31 13_02_18-Window](https://user-images.githubusercontent.com/67209365/131491644-ed1063d7-ebbc-4226-8578-af10d16c2df4.png)
![2021-08-31 12_58_18-Window](https://user-images.githubusercontent.com/67209365/131491657-6bd397a5-fb71-44bf-a3ab-690728f9acb4.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.05.4
 - PHP Version: php8.0
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Additional context**

**Comment by ssddanbrown** [comment] 2021-09-01 21:20
Hi @pboatone,
When setting permissions are you ensuring that your own user account will have permission afterwards? What you've described could occur if you're updating permissions in a way that will hide it for your current user.

Otherwise, Are you using a system-level admin account? (Not a custom admin-like role)

**Comment by pboatone** [comment] 2021-09-02 09:09
Hi @ssddanbrown,

I am using an admin account and have the permissions too.

**Comment by ssddanbrown** [comment] 2021-09-02 20:04
@pboatone  Odd, Does the same occur when you set permissions on books?

**Comment by pboatone** [comment] 2021-09-02 20:41
> @pboatone Odd, Does the same occur when you set permissions on books?

I didn't tried on existing books, in new shelfes which have the ownership of me it works ... I don't want to try it on existing books because they are not recoverable from the settings/cleanup

**Comment by ssddanbrown** [comment] 2022-10-15 14:28
I am going to close this off since, after testing again, I am not able to reproduce at all.
I can only assume that it's specific to the roles/permission at play in the original scenario. 
Happy to address if a specific issue can be detected, or can reopen if this can be reproduced on our demo instance.

**Closed by ssddanbrown** 2022-10-15 14:28 UTC
