### ISSUE TITLE
504 Gateway Time-out Error after login to Bookstack portal

### ISSUE THREAD

**Issue by sachinvishwakarma26** [BookStackApp/BookStack#4057] opened 2023-02-21 11:09 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

We have implemented Bookstack on Amazon Linux2 OS platform and we are able to login portal using local username and password. Also we have configured LDAP after LDAP configuration we are unable to login to poral using our domain username and password its giving error 504 Gateway Time-out.

Could you please advise to fix this problem.

Note: We are using Nginx web service for bookstack.

### Exact BookStack Version

v22.11.1

### PHP Version

7.4

### Hosting Environment

Amazon Linux 2

**Comment by ssddanbrown** [comment] 2023-02-21 15:58
> Also we have configured LDAP after LDAP configuration we are unable to login to poral using our domain username and password its giving error 504 Gateway Time-out.

When does the error occur? Is it upon submitting the login form within BookStack or does it occur when simply attempting to load the login form or homepage?

> PHP Version: 7.4

Just a note, the next release will be dropping PHP7.4 support so you'd need to upgrade that before upgrading to the any future releases.

**Comment by sachinvishwakarma26** [comment] 2023-02-22 08:55
@ssddanbrown After login bookstack portal its giving error.

![image](https://user-images.githubusercontent.com/43565381/220570492-b40e9f26-d8e9-4efd-80c0-a65d44d62d9f.png)

**Comment by ssddanbrown** [comment] 2023-02-22 10:46
@sachinvishwakarma26 When you say "After login", does that mean you see the login form beforehand and this error shows on submit?
Or does this error show on first access (You never see the form)?

**Comment by sachinvishwakarma26** [comment] 2023-02-22 11:12
@ssddanbrown  Yes this error giving on after click on submit option.

**Comment by ssddanbrown** [comment] 2023-02-22 11:52
Okay, in that case I'd look at the nginx error logs, for messages logged around the same time as when the error shows.

**Comment by sachinvishwakarma26** [comment] 2023-02-23 08:30
@ssddanbrown Please find the attached logs files.

**Comment by sachinvishwakarma26** [comment] 2023-02-23 08:36
[bookstack_2.zip](https://github.com/BookStackApp/BookStack/files/10811649/bookstack_2.zip)

**Comment by ssddanbrown** [comment] 2023-02-23 10:56
Can't see anything specific regarding that error in those logs. It may be that the error has not occurred in the time range of the logs, or it's not clear if there may be another http layer at play.
Ideally you need to reproduce the error then find the error logs for that specific time that the error occurred for.

**Comment by sachinvishwakarma26** [comment] 2023-02-23 11:33
@ssddanbrown If possible shall i go and schedule a call with you.

**Comment by ssddanbrown** [comment] 2023-02-23 12:43
@sachinvishwakarma26 That is not something I'm willing to do on this free support channel.

**Comment by sachinvishwakarma26** [comment] 2023-03-06 09:11
@ssddanbrown Its seems gateway error due to not able to reach the bookstack using AD Authentication. Can please help us setting up reverse proxy(Redirection) for bookstack running on nginx.

**Comment by ssddanbrown** [comment] 2023-03-06 11:00
@sachinvishwakarma26 I can try to assist on the BookStack side of things but from the above I'm not convinced requests are reaching your server upon that error message being shown.

How are you handling HTTPS? When you see the BookStack login form, is the page loaded over http or https?

**Comment by sachinvishwakarma26** [comment] 2023-03-06 15:17
@ssddanbrown 

We are using https.

**Comment by ssddanbrown** [comment] 2023-03-06 16:33
@sachinvishwakarma26 How are you handling HTTPS? How exactly have you set it up in relation to the server that BookStack is used on?

**Comment by sachinvishwakarma26** [comment] 2023-03-06 16:56
@ssddanbrown  We have followed the below blog to set it up Bookstack and nginx configuration fine we have made listen port 443.

https://www.howtoforge.com/tutorial/centos-bookstack-nginx/

**Comment by ssddanbrown** [comment] 2023-03-06 17:14
Okay, setting 443 alone does not enable valid https.

By going to your URL, I can see it's on HTTPS with a valid amazon certificate, so I presume there's some level of AWS proxy system at play handling HTTPS. 
That proxy is probably the origin of the error shown above (but not the cause).

If I had to guess what the error is, I'd say the configured `LDAP_SERVER` is inaccessible or does not resolve from the server system.
Check that you can `ping` the domain for your `LDAP_SERVER` from the host system.

Errors should be logged to the `/var/log/nginx/bookstack_error.log` file, but you'd need to watch/check that file right after getting the error to show.

**Comment by ssddanbrown** [comment] 2023-04-28 18:39
Since there's been no follow-up I'm going to close this off.

**Closed as completed by ssddanbrown** 2023-04-28 18:39 UTC
Labels: :dog2: Support
