### ISSUE TITLE
CSS is not loaded in release branch 

### ISSUE THREAD

**Issue by T3-RnD** [BookStackApp/BookStack#3522] opened 2022-06-23 13:12 UTC
### Describe the Bug

I downloaded the master branch and it seems that it has the CSS issue, then I searched for a solution and I found this

https://github.com/BookStackApp/BookStack/issues/496

But in my case, I have downloaded the release branch and then I had the same issue, any reason why?

### Steps to Reproduce

after running the server php artisan serve the 

### Expected Behaviour

running the server with the main layout working

### Browser Details

chrome in mac os 

### Exact BookStack Version

22.04.2

### PHP Version

7.4

### Hosting Environment

Mac OS using MAMP server

**Comment by ssddanbrown** [comment] 2022-06-23 13:18
Hi @T3-RnD,
It's probably worth following our debugging guidance for this specific issue here:
https://www.bookstackapp.com/docs/admin/debugging/#no-styles-and-large-icons-on-access

If those don't help, please confirm if the files exist on your filesystem when accessing the `public/dist` directory in your BookStack folder.

**Comment by T3-RnD** [comment] 2022-06-23 13:35
Hi @ssddanbrown 

I appreciate your quick reply, I have checked this already 
in my .env file is the following:

APP_URL=http://127.0.0.1
# Database details
DB_HOST=127.0.0.1
DB_PORT=8889
DB_DATABASE=t3_books
DB_USERNAME=root
DB_PASSWORD=root

Regarding the release, I already mentioned that I followed one of your solutions to use the release branch, and also the files I have checked them, and all files are there

but it is worth mentioning that I have this URL with the version number as a variable "http://127.0.0.1/dist/styles.css?version=v22.04.2"

**Comment by T3-RnD** [comment] 2022-06-23 13:40
Hi again

sorry I forgot to add the port so it should be like 127.0.0.1:8001

But, I have a weird view now its split into 2 as shown in the image below

![image](https://user-images.githubusercontent.com/104494713/175312917-39216984-955d-4622-945d-1f39814185c6.png)

**Comment by ssddanbrown** [comment] 2022-06-23 13:41
@T3-RnD 

Check the [error log file](https://www.bookstackapp.com/docs/admin/debugging/#error-log-file) to see the cause of that message.

**Comment by T3-RnD** [comment] 2022-06-23 13:52
There is no error in the log regarding this issue, the last log was the migration something about "conection.php" doesn't exist but I solved it already.

I there any other solution? Thanks in advance

**Comment by T3-RnD** [comment] 2022-06-23 14:05
I enabled the debug mode and here is the result

![image](https://user-images.githubusercontent.com/104494713/175318668-aad8fb9b-1cd4-49e9-8c6e-42b36c030731.png)

Any Ideas

**Comment by ssddanbrown** [comment] 2022-06-23 14:05
Did you run the `php artisan key:generate` install step?

**Comment by T3-RnD** [comment] 2022-06-23 14:11
It's working now

I already did this before but for some reason it wasn't generated so I generated it again

Thanks for your help @ssddanbrown

**Comment by ssddanbrown** [comment] 2022-06-23 14:17
Good to hear!, I'll therefore close this off.

**Closed as completed by ssddanbrown** 2022-06-23 14:17 UTC
Labels: :bug: Bug
