### ISSUE TITLE
Support For All DataBases (Postgres, SQL Server...)

### ISSUE THREAD

**Issue by Scemist** [BookStackApp/BookStack#4149] opened 2023-03-31 20:36 UTC
## Is not far to make the project support all DBMS

Laravel has an amazing ORM, Eloquent, the developers really work hard to make possible we use any DBMS in a Laravel Application.

Today I setup and ran the migrations, the first 29 migrations ran successfully. The only problem that muddle is the raw queries, and here is the major work.

Altought it would be a huge jump to the project, I'm sure that we can help with this, but the specialists has to confirm the possibility, due the businness rule.

Is there any plan for this standardization to Laravel's Eloquent?

### Describe the benefits this would bring to existing BookStack users

It is a headache to companies to setup another DBMS, and sometimes it doesn't looks makes sense. So the possibility of use any DBMS is too convenient, and it is not a far plan for this project.

### Can the goal of this request already be achieved via other means?

This goal is possible by refactoring the migrations and certifying the existing model queries is using Eloquent instead raw queries. I would like to read more about you opinion and know if the obstacles is bigger than we can handle with.

### Have you searched for an existing open/closed issue?

- [ ] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

The existent discussion is locked. 🙂

**Comment by ssddanbrown** [comment] 2023-03-31 21:20
Hi @Scemist,
Thanks for the offer of assistance but, as I mentioned multiple times in #76, it's not the technical/implementation side that's stopping this, that is of course achievable, but instead it's the social/support side of things.  For more information, please see my comments in that locked thread, specifically [from this comment onwards](https://github.com/BookStackApp/BookStack/issues/76#issuecomment-494956958).

Since this is essentially a duplicate of #49 / #367, I'm going to close this off but you can continue to comment if required.

**Closed as completed by ssddanbrown** 2023-03-31 21:20 UTC
Labels: :hammer: Feature Request
