### ISSUE TITLE
Includes on the specific homepage are not being rendered

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1179] opened 2018-12-12 14:00 UTC
**Describe the bug**
When the specific application homepage includes content from another page, that include is not being rendered

![screenshot_2018-12-12_14-58-34](https://user-images.githubusercontent.com/37742522/49874390-a5dd0700-fe1e-11e8-8054-159e9e71e8f2.png)

**Comment by geins** [comment] 2021-04-03 18:16
I have exactly the same problem. When I view the page with content 
`Schwarzes Brett Intensivstation
{{@94}}

Schwarzes Brett Anästhesiologie
{{@106}}`
it renders perfectly fine with reused content.

But when I set the exact page as homepage, the include isn't rendered.
That's quite a bit strange for me.

Thank You!

**Comment by C0rn3j** [comment] 2021-12-26 14:24
Duplicate of #2279, can be closed 
@ssddanbrown

**Comment by ssddanbrown** [comment] 2022-01-30 13:14
Thanks @C0rn3j, Will therefore close.

**Closed by ssddanbrown** 2022-01-30 13:14 UTC
Labels: :coffee: Open to discussion
