### ISSUE TITLE
Define color sheme for shelves, books etc. separately for Dark Mode.

### ISSUE THREAD

**Issue by Flight777** [BookStackApp/BookStack#2314] opened 2020-10-08 15:07 UTC
After the quick response on my last feature request, here is something else I found:

When switching to dark mode, Bookstack retains the shelves/books colors etc. as defined in the settings. However, if using a darker color for one of these, it will obviously not work well in dark mode :P While on a light/white background (normal mode) you tend to use darker colors to have better contrast with the white.

Would it be possible to define colors separately for light mode and dark mode in the Settings page for a future version?

**Comment by skeith** [comment] 2020-11-05 02:27
I second this. The "Recent activity" links are hard too read and some text color is not bright enough on dark mode.

**Comment by ssddanbrown** [comment] 2020-12-09 21:19
Just a note on this, If you did want to override any colors specifically for dark mode you could do so by overriding the variables bookstack uses by adding something like the below in the "Custom HTML Head Content" setting:

```html
<style>
	html.dark-mode {
	    --color-primary: #206ea7;
	    --color-primary-light: rgba(32,110,167,0.15);
	    --color-bookshelf: #a94747;
	    --color-book: #077b70;
	    --color-chapter: #af4d0d;
	    --color-page: #206ea7;
	    --color-page-draft: #7e50b1;
	}
</style>
```

**Comment by eizedev** [comment] 2021-02-15 10:08
i support this. We are using a dark grey primary color. The problem is, that all links on pages are also using this primary color. So it is hard to read and identify the hyperlinks (black and black). Due to our corporate design, we cannot change the primary color.
I added a style using the custom html head content and set `a:link` and `a:hover` to another color. It is working but also all urls that have not been visited on other site elements like the page details etc. are now in the color defined in `a:link`.

It would be great, if you could make the color for links (inside pages) configurable. They should not depend on the primary color. 

I didn't want to open a new issue since it was already mentioned in issue #2400 and referenced here.

**Comment by posta246** [comment] 2022-01-27 14:28
Hi Dan, do you think to introduce different color and/or something to manage them in the future release? Just to know how organize myself.
I've seen the html/css solution you propose, may you give us the code for modifying only the color of the chars? For me infact the book, page etc "background" color could be ok if I can modify the color of the text. Using the image of #3203, the color of the name of the books (green on green...) in yellow section 2 is very difficult to read, but just changing it to white for example could be a solution, without changing the color of the book items... 
Hope I explained myself!!!
Thx!

![immagine](https://user-images.githubusercontent.com/80681065/151378191-47aea532-2d11-4234-8125-ce80758950a6.png)

**Comment by adriangalbincea** [comment] 2022-12-01 15:35
Will be good to have separate colour customization for the Dark mode because is very difficult to match a colour scheme to look good/readable in both themes.

**Comment by ssddanbrown** [comment] 2023-01-28 18:02
This has now been added as part of #4002 and will be part of the next feature release.

**Closed by ssddanbrown** 2023-01-28 18:02 UTC
Labels: :art: Design, :hammer: Feature Request
