### ISSUE TITLE
Pasting from excel produces image instead of table

### ISSUE THREAD

**Issue by Vicvinegar0** [BookStackApp/BookStack#987] opened 2018-08-24 21:10 UTC
I noticed that pasting from Excel, either into a blank space in Bookstack or table, uploads an image of the cells. Is this the intended behavior? I tried the same thing into a TinyMCE demo on their website, and that instead produces a table like you'd expect

**Comment by TBK** [comment] 2018-08-24 22:31
BookStack is using TinyMCE 4.7.9, the latest version i 4.8.2.

I think the issue you experienced is related to this bug _"fixed a bug in the Table Plugin where some table cell styles were not correctly added to the content html."_ which was fixed in version 4.7.10 - https://www.tiny.cloud/docs/changelog/#version4710april32018

**Comment by ssddanbrown** [comment] 2018-08-25 11:50
Hmm, Not the intended behaviour. 
In BookStack we do have a custom paste listener to check the clipboard for images, so we can handle paste-image uploads, then prevent further action. Can only image Excel now adds screenshot-style image data to the clipboard along with the standard data. Will have a deeper look.

If possible please confirm your OS and Excel version.

**Comment by yamss** [comment] 2019-03-26 18:27
Just to confirm, I have the same issue in Linux Mint 19 and LibreOffice Calc 5.1.6.2 . Using Google docs or ONLYOFFICE works as a work around.

**Comment by Technik-J** [comment] 2019-05-14 17:18
Have the same problem on Excel and LibreOffice.

**Closed** 2019-05-15 19:24 UTC
Labels: :bug: Bug, :memo: WYSIWYG Editor, > Markdown Editor

**Comment by ssddanbrown** [comment] 2019-05-15 19:26
Thanks everyone above for the details. Potential fix now applied in master, Will be in the next release. Fix tested on ubuntu+Libre office. Should be the same result in excel.

If this is still not fixed fro you after upgrading to v0.26.2 (once it's released) please let me know and I'll investigate further.
