### ISSUE TITLE
Default permissions on public-directories giving white screen

### ISSUE THREAD

**Issue by memetoec** [BookStackApp/BookStack#4568] opened 2023-09-20 12:40 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I had a todo upgrading BookStack from v23.01.1 to v23.08.3. While doing so I had to solve some issues regarding composer and PHP version, when that was in place everything seemed to go well. 

When all routines was done and I was ready to check the application, I was met with a white screen. I checked the logs for php-fpm and got this error message:

<details><summary>Details</summary>
<p>

```
#21 {main}
  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 190
[20-Sep-2023 13:09:01 Europe/Oslo] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190
Stack trace:
#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()
#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(185): Illuminate\Filesystem\Filesystem->put()
#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(62): Illuminate\View\Compilers\BladeCompiler->compile()
#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\View\View->getContents()
#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\View\View->renderContents()
#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()
#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()
#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\Http\Response->__construct()
#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\Routing\ResponseFactory->make()
#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(626): Illuminate\Routing\ResponseFactory->view()
#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse()
#16 /var/www/BookStack/app/Exceptions/Handler.php(66): Illuminate\Foundation\Exceptions\Handler->render()
#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): BookStack\Exceptions\Handler->render()
#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(246): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#20 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#21 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
```

</p>
</details> 

On line 3 laravel is complaining about permissions, so I followed this routine -> [filesystem-permissions](https://www.bookstackapp.com/docs/admin/filesystem-permissions/)

After doing so, nothing happened. I search on similar error messages where people said to clear cache both in browser and application. 
I ended up clearing my browser cache and doing the following commands, 
```
php artisan cache:clear
php artisan config:clear
php artisan view:clear
```

Still, I had a white screen viewing nothing. Then I did what all sysadmins are tought NOT to do, and that is to give 777 to publicly faced directories. 

Then, everything worked! 
BUT, I'm not happy having **storage**, **bootstrap/cache** and **public/uploads** with permissions set to 777. 

My question now is, is this intentional? Or have I done something wrong along the upgrade? 

What I did:

- Snapshot of server
- Updating all packages and rebooting server
- Uninstalling php 7.4 and resetting PHP
- Installing php 8.2 from :remi repo
- Cloning a new version of BookStack, copying over .env.
- Giving all directories permissions regarding the official docs.
- Did the upgrade routine which is described here -> [updates](https://www.bookstackapp.com/docs/admin/updates/)

### Exact BookStack Version

v23.08.3

### Log Content

<details><summary>Details</summary>
<p>

```
[20-Sep-2023 14:15:07 Europe/Oslo] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190
Stack trace:
#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()
#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(185): Illuminate\Filesystem\Filesystem->put()
#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(62): Illuminate\View\Compilers\BladeCompiler->compile()
#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\View\View->getContents()
#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\View\View->renderContents()
#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()
#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()
#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\Http\Response->__construct()
#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\Routing\ResponseFactory->make()
#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(626): Illuminate\Routing\ResponseFactory->view()
#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse()
#16 /var/www/BookStack/app/Exceptions/Handler.php(66): Illuminate\Foundation\Exceptions\Handler->render()
#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): BookStack\Exceptions\Handler->render()
#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(246): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#20 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#21 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#22 {main}
  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 190
```

</p>
</details> 

### Hosting Environment

My Environment:
OS: Rocky Linux 8.x
Hypervisor: VMWare
PHP version: 8.2 - REMI repo
NGINX: nginx/1.14.1
Composer: 2.5.1 2022-12-22 15:33:54

**Comment by ssddanbrown** [comment] 2023-09-20 23:16
> so I followed this routine -> [filesystem-permissions](https://www.bookstackapp.com/docs/admin/filesystem-permissions/)

Did you change `www-data` to suit your operating system?
I don't think `www-data` is used by RHEL based systems. You'd have to check what nginx is running as.

**Comment by memetoec** [comment] 2023-09-21 11:58
Yes, I'm using nginx as user and group. 
My nginx.conf has nginx as system user defined. I have changed php-fpm to use nginx as user and group as well. 

![Skjermbilde_2023-09-21_kl__13_55_46](https://github.com/BookStackApp/BookStack/assets/9047962/8132183b-8a49-4879-a17c-935be50bc067)

As you can see, my folders and files have 777 (not the way I want it BUT only settings that work). User is nginx:nginx.

**Comment by ssddanbrown** [comment] 2023-09-21 15:06
If you're sure the user/group is aligned to webserver/php process owner, then the other thing it can often be on RHEL based systems is SELinux. You could try temporarily disabling SELinux to assess if that's the cause.

**Comment by memetoec** [comment] 2023-09-25 10:35
Hi! 

SELinux is disabled on this server, 
```
sestatus
SELinux status:                 disabled
```
![Skjermbilde_2023-09-25_kl__12_31_36](https://github.com/BookStackApp/BookStack/assets/9047962/fbd47857-4c1b-47f8-bbaf-ff06248b1a72)

It's not that either. What I think is weird is that the application was not responding until I set 777 on all public folders. 
What's more strange is that people are not able to upload files either, some users (not all) have problems upload images to articles.

**Comment by ssddanbrown** [comment] 2023-09-25 11:15
Outside of those two elements (file permissions and SELinux), I'm not sure what else it would be.
Can you upload an image then list out then `ls -al` that directory, to double check the user and group being used by BookStack when creating these? There could be something else involved due to the `php-fpm` process, rather than it just being nginx.

**Comment by memetoec** [comment] 2023-09-26 10:57
Hi! 

I did that earlier today, and got the following output:
![Skjermbilde_2023-09-26_kl__12_46_57](https://github.com/BookStackApp/BookStack/assets/9047962/e773c635-5721-4deb-a700-0fb85a98f7df)

I'll add our folder structure as well, so you can see if anything is not correct:
![Skjermbilde_2023-09-26_kl__12_48_11](https://github.com/BookStackApp/BookStack/assets/9047962/62f4e1f6-3847-4a54-aaaa-d0c8a955753a)

The only folder that is directly affected is the 2023-09 (I did the upgrade late last week)

I checked your documentation for PHP-packages and had all required packages installed. Here is the list of installed PHP-packages, 
![Skjermbilde_2023-09-26_kl__12_53_43](https://github.com/BookStackApp/BookStack/assets/9047962/327aab32-aea3-4dd6-a198-3c57ec9ce01a)

I have also checked some parameters in php.ini. I did adjust some thresholds to upload size and execution time, despite that those settings doesn't have anything to do with permissions on folder ^^

**Comment by ssddanbrown** [comment] 2023-09-26 13:24
Just as a test, do things stop working again if you set `755` permissions on that `2023-09` folder?
If not, try setting it for the whole, `public/uploads` folder again.
Then others, until it stops working.
I don't see why recursive `nginx:nginx` and `755` won't work for the required directories at this point.

One extra point, `nginx` would also need read+execute on all parent directories. If that's something that changed when you started setting `777`, that could be the cause.

**Comment by ssddanbrown** [comment] 2023-10-14 14:27
Since it's been a few weeks I'll close this off. If further insight can be provided or desired, feel free to comment and this can be re-opened if required.

**Closed as completed by ssddanbrown** 2023-10-14 14:27 UTC
Labels: :dog2: Support
