### ISSUE TITLE
Delete drafts

### ISSUE THREAD

**Issue by ayxos** [BookStackApp/BookStack#2170] opened 2020-07-02 14:49 UTC
**Describe the feature you'd like**
I am the Admin of the site, some users left drafts open which are visible on the left side but not available (link returns a 404)
As an admin I should be able to delete empty drafts or whatever non-published draft

**Describe the benefits this feature would bring to BookStack users**
keep the system clean and avoid empty drafts all over the platform

**Comment by ssddanbrown** [comment] 2020-07-04 16:24
Hi @ayxos,
This is a little concerning as you should not be able to see drafts at all.
Would you be able to confirm the following?:

- What BookStack version are you on (Found at the top of settings)?
- Have you attempted any modifications to the core code?
- What do these drafts look like? Are they a different color to normal pages? When you side "on the left side", where is that? On the homepage?

**Comment by DavidLeutgeb** [comment] 2020-07-22 11:08
Hi @ssddanbrown, 

I can confirm an unexpected behaviour of drafts. However I cant reproduce it at the moment so I describe it as well as I could. 

Bookstack version: 0.29.3
Code modifications: No
How the drafts look: Like drafts I create myself (purple color)
How many users use our bookstack instance: about 100

How I discovered the problem: 
One of my colleagues sent me an mail because he was unable to sort a book. Everytime he tried to save the new sort order he got an error with permission denied and falls to the application homepage (as defined in settings). So I got to the book and got the same error, so I started searching. 

What did I found: 
I found some two drafts in chapters, both of them not from me but visible to me (also in the purple draft color). When I clicked them I got a 404 error. Solution to delete the draft was to delete the whole chapter and recreate it. 

Also I can confirm that I can't reproduce this by asking a user to save a draft, this works a s expected. I come back to you when I see this problem the next time.

**Comment by jstapels** [comment] 2020-10-25 17:49
I'm having this same issue... as an admin, shouldn't I be able to see or delete someone's draft?
Is there a workaround to this issue?

**Comment by ssddanbrown** [comment] 2021-05-26 14:10
Since no-one has been able provide reproduction steps or confirmation they could reproduce this, I'm going to close this off but if you find you are able to re-create this scenario please open a new issue detailing the steps and I'll get right on it.

**Closed by ssddanbrown** 2021-05-26 14:10 UTC
