### ISSUE TITLE
[WYSIWYG] Saving Images on Draft

### ISSUE THREAD

**Issue by BabyLoves** [BookStackApp/BookStack#4370] opened 2023-07-07 15:06 UTC
### Describe the Bug

I was trying save the page/draft with image but not saved.
Error page:
![image](https://github.com/BookStackApp/BookStack/assets/65966239/f8e22bce-97c7-41d0-b3ec-a6a97801e4e4)

This error only ocurring in WYSIWYG editor
![image](https://github.com/BookStackApp/BookStack/assets/65966239/13ab101b-afc4-4668-9361-389fbe0b43f0)

### Steps to Reproduce

Create a draft(or page)
Upload the image to the content
Save

### Expected Behaviour

The page won't be saved

### Exact BookStack Version

23.02.3

### PHP Version

8.0

### Hosting Environment

Ubuntu 20.04 localmachine

**Comment by ssddanbrown** [comment] 2023-07-07 15:35
Hi @BabyLoves,
With that kind of error message, I think this could likely be something specific to your environment.
Maybe something at a webserver level.
I'd start by checking the error logs for the webserver you're using in the hope of finding more detail regarding this scenario.

**Comment by BabyLoves** [comment] 2023-07-07 17:56
> Hi @BabyLoves, With that kind of error message, I think this could likely be something specific to your environment. Maybe something at a webserver level. I'd start by checking the error logs for the webserver you're using in the hope of finding more detail regarding this scenario.

I'm using the Bookstack with no modifications only following the Installation scripts and its ocurred with me, any idea about it?

**Comment by ssddanbrown** [comment] 2023-07-08 10:29
Please can you check the error logs for the webserver you're using in the hope of finding more detail regarding this scenario?

You can usually do this via `sudo tail /var/log/apache2/error.log` right after reproducing the error.

**Comment by ssddanbrown** [comment] 2023-07-18 10:15
Since there's been no further follow-up I'll close this off.

**Closed as completed by ssddanbrown** 2023-07-18 10:15 UTC
Labels: :bug: Bug
