### ISSUE TITLE
Page permalink visibility

### ISSUE THREAD

**Issue by milneauk** [BookStackApp/BookStack#3641] opened 2022-08-11 10:08 UTC
### Describe the feature you'd like

Would it be possible to add a more visible way to display a page permalink?

I suggested having a toggle in the settings to display this information at the bottom of the page (#3520) but @c0shea rightly suggested about having another button on the right-hand side of the page to copy the permalink to the clipboard. 

### Describe the benefits this would bring to existing BookStack users

We have noticed users are copying the URL from the browser address bar but we know this isn't a concrete solution as links may break when pages are moved around or renamed. The correct method has been pointed out to our users but we know this is still the "normal" practice. 

Having something to attract users to the page permalink would encourage them to use that over the address bar.

### Can the goal of this request already be achieved via other means?

Users currently have to highlight a portion of the page content to get the UID/permalink but I think there should be an option to display this on the page automatically from the settings or a button on the page to copy to the clipboard as suggested above by @c0shea.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment] 2022-08-11 10:22
Thanks for the request but this is essentially a duplicate of #2917 so please see my response there and I'm going to close this off as a duplicate.

**Closed as completed by ssddanbrown** 2022-08-11 10:22 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
