### ISSUE TITLE
Problem upgrading to v22.09

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#3712] opened 2022-09-09 08:19 UTC
### Describe the Bug

When upgrading to v22.09 from 22.07.3, I received this error:

```bash
From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
Updating 1fdf854e..2ac9efae
error: Your local changes to the following files would be overwritten by merge:
        app/Config/app.php
Please commit your changes or stash them before you merge.
Aborting
```
I assume this was because my app.php file was different to the one it was being updated with (my app.php has a custom entry for file upload size)? 

I renamed the app.php file and re-ran

```bash
git pull origin release 
composer install --no-dev
php artisan migrate
```
and all seems to have updated correctly - I reverted app.php to my original version after doing this. Adding these comments in case anyone else has a similar problem.

### Steps to Reproduce

Upgrade using the command above

### Expected Behaviour

The upgrade process to complete without an error

### Browser Details

Firefox 104.0.2 64 bit on Ubuntu 22.04 LTS

### Exact BookStack Version

v22.0.7

### PHP Version

8.0.22

### Hosting Environment

Ubuntu 22.04 LTS on HP server

**Comment by ssddanbrown** [comment] 2022-09-09 14:55
Hi @techauthoruk,
This would be expected behaviour in that scenario.
Editing of the `app/` files is not supported and will cause upgrade conflicts. 
I believe there's a warning at the top of the edit file to advise against editing.

If you let me know exactly what line you've altered, I should be able to provide the officially support way of performing the config change made here.

**Comment by techauthoruk** [comment] 2022-09-11 12:52
Hi @ssddanbrown 

I use a bash script file to backup all my BookStack files and databases and then perform the upgrade to the latest version, which may well be the reason I didn't see any warnings or other prompts...maybe I should look at updating my script to give some sort of prompt!

The line changed in my app.php file was:

```bash
    // The limit for all uploaded files, including images and attachments in MB.
    'upload_limit' => env('FILE_UPLOAD_SIZE_LIMIT', 2048),
```

I think the original entry here for file upload size was 50, but I had to change this as even though my Apache and php upload limits were set at 2048 in their respective .ini files (and having code suggested in your support notes in the custom head section within BookStack), I couldn't upload large files until I changed this value. The error may be mine in that I missed some other changes I should have made, but all works fine with this entry in app.php. I'm no expert in this!

**Comment by ssddanbrown** [comment] 2022-09-11 13:50
Hi @techauthoruk,
The proper way to change that option would be by adding:

```shell
FILE_UPLOAD_SIZE_LIMIT=2048
```

to your `.env` file, found in the root folder of your BookStack install.
This is documented in our docs here: https://www.bookstackapp.com/docs/admin/upload-config/#bookstack

> and having code suggested in your support notes in the custom head section within BookStack

That was an old mechanism that was replaced with the above.
This change can be found in our update notes here: https://www.bookstackapp.com/docs/admin/updates/#updating-to-v2111-or-higher  ("Updating to v21.11 or higher" section)

**Comment by techauthoruk** [comment] 2022-09-11 14:16
Ah @ssddanbrown 

Fair comment, although as a non-technical user, it's a bit of a stretch to expect me to check all the revision/update notes to see what the changes have been :D - remember, many of us are user-admins with a limited degree of technical prowess!

I will remove the code in the custom head section & revert the app.php file to the default 50Mb setting to avoid future issues (I assume that this is the correct action to take?). I will test for uploads and then see what happens on the next app update

**Comment by techauthoruk** [comment] 2022-09-11 14:42
mmm...doing this has (seemingly) removed all my shelf/book custom images! Not what I was expecting and I don't have time to investigate this further today.

**Comment by techauthoruk** [comment] 2022-09-11 14:51
Wow!!!!!!

Making these (seemingly small) changes have resulted in not only losing all my custom book images, but also when I try to log in producing an error message that says "The image '...\image filename hidden.png' cannot be displayed because it contains errors"

Why? What has happened to cause this? What have I done to do this and does it mean I need to upload ALL my custom images and reassign them?

**Comment by ssddanbrown** [comment] 2022-09-11 16:47
> it's a bit of a stretch to expect me to check all the revision/update notes to see what the changes have been :D 

Always worth checking the official updates page before updates though, I ensure any potentially breaking changes or security notices are listed there for each version change.

> I will remove the code in the custom head section & revert the app.php file to the default 50Mb setting to avoid future issues (I assume that this is the correct action to take?).

Yes, The latest release version of the file [can be found here](https://github.com/BookStackApp/BookStack/blob/release/app/Config/app.php).

> Why? What has happened to cause this? 

I don't know, Changing the mentioned files alone (`.env`, `app.php`) should not cause this unless there are maybe formatting issues.

- Can you confirm the output of running `git status` in your BookStack install directory?
- Can you confirm the exact change made to the `.env` file.
- Can you confirm if you have a `STORAGE_TYPE` option set in your `.env` fille.
- Can you confirm what the current error message looks like? Does the error show with BookStack branding? Or is it a blank black and white page?

> does it mean I need to upload ALL my custom images and reassign them?

No, changing config options alone should not delete/break existing images unless something else has been ran in an attempt to fix things. I'd expect them to re-show once configuration issues have been resolved.

**Comment by techauthoruk** [comment] 2022-09-13 16:01
@ssddanbrown 

Dan

Don't know what happened, but reverting the configs made no difference. I ended up restoring my install from a backup in its entirety, and all is now working as it should. Something obviously got corrupted, but thank you daily backups!

I have made the changes to the .env file and /Config/app.php is now in line with the structure you suggested.

Mark

**Comment by ssddanbrown** [comment] 2022-09-13 22:29
Good to hear things are back working. Will therefore close this off.

**Closed as completed by ssddanbrown** 2022-09-13 22:29 UTC
Labels: :bug: Bug
