### ISSUE TITLE
Selectable tags when searching

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3724] opened 2022-09-14 02:07 UTC
### Describe the feature you'd like

When you use the global search bar you should be able to select available tags in the advanced search area. Currently, you have to KNOW the exact name of a tag to utilize that section.

### Describe the benefits this would bring to existing BookStack users

Easier advanced searching.

### Can the goal of this request already be achieved via other means?

Kind of? Navigate to <url>/tags and click the tag you want, copy it, redo the search then paste the tag into the advanced search

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

#2829 is basically asking the same thing.

**Comment by merrime-n** [comment] 2022-09-14 08:27
I guess I have the same issue. I think it would be better if we could just search for any part of the tag name. Currently, we need to type the exact tag name to add it. My issue is [here](https://github.com/BookStackApp/BookStack/issues/3720)

**Comment by ssddanbrown** [comment] 2022-09-14 09:23
Hi @Mailstorm-ctrl,

> https://github.com/BookStackApp/BookStack/issues/2829 is basically asking the same thing.

Was there a specific differentiator in raising this additional issue then? Just want to ensure I'm not missing anything before closing this as a duplicate.

In regards to other means of achievement, you could start a tag search by clicking the name or value of the tag, then tweaking your search from there.

**Comment by Mailstorm-ctrl** [comment] 2022-09-15 00:11
> Hi @Mailstorm-ctrl,
> 
> > #2829 is basically asking the same thing.
> 
> Was there a specific differentiator in raising this additional issue then? Just want to ensure I'm not missing anything before closing this as a duplicate.
> 
> In regards to other means of achievement, you could start a tag search by clicking the name or value of the tag, then tweaking your search from there.

There sure is a reason...I don't know how github works and wasn't sure if liking the request brought it back up on your radar :)

**Comment by ssddanbrown** [comment] 2022-09-15 10:19
Okay, thanks for confirming, I'll therefore close this off as a duplicate of #2829

**Closed as completed by ssddanbrown** 2022-09-15 10:19 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
