### ISSUE TITLE
Feature request: default language for new registrations

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#1031] opened 2018-09-27 12:50 UTC
**Describe the feature you'd like**
Allow to choose default language for new users in settings similarly to other preselected options.

**Describe the benefits this feature would bring to BookStack users**
Default is English, default should be whatever admin thinks most of the users speak and set the language to.

**Additional context**
-

**Comment by ssddanbrown** [comment] 2018-09-27 17:56
Hi @nekromoff,
This should already be possible. Please see documentation here and let me know if that works:
https://www.bookstackapp.com/docs/admin/language-config/

**Comment by ssddanbrown** [comment] 2019-05-18 10:15
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Closed by ssddanbrown** 2019-05-18 10:15 UTC
Labels: :dog2: Support

**Comment by kekcsi** [comment] 2024-10-18 21:31
Hi, reopening the discussion because I experience that newly registered users have the preferred language on their profiles set to English initially, regardless of the APP_LANG or browser preference. Unregistered visitors see the default that is set in the linked documentation but once they register they are switched to English.

**Comment by ssddanbrown** [comment] 2024-10-19 11:16
@kekcsi Please open a new issue for that if you're sure that's the case, detailing exact route taken for registration. Having a quick look at the code it should default to system language for new users via the registration form, but if you open a new issue I'll spend some time to confirm that once the exact registration route is confirmed. Also, confirm on that issue what version of BookStack you're using.

**Comment by kekcsi** [comment] 2024-10-19 18:44
@ssddanbrown Thanks for the investigation, I'll double check my deployment. It was dockerized and not all images had all the environment variables set.
