### ISSUE TITLE
Table-Button in Editor-Modus

### ISSUE THREAD

**Issue by micha141076** [BookStackApp/BookStack#3779] opened 2022-10-12 13:22 UTC
### Describe the Bug

Missing function  in Edit-Table-Button

### Steps to Reproduce

When I click on the Button.

### Expected Behaviour

Hello,
when I logg me in bookstack and edit a page, my table-button has not the correkt function.
see the picture. Is this correct?

BR
micha

### Screenshots or Additional Context

this is my view:
![bookstack](https://user-images.githubusercontent.com/3964766/195353210-369120fc-0205-4f08-9d57-175cdf6c8836.png)

This is an other user:
![bookstack2](https://user-images.githubusercontent.com/3964766/195353577-b8e3e49f-523a-46f4-8426-e3f7243b3cdd.png)

### Exact BookStack Version

22.09.1

### Hosting Environment

Ubuntu

**Comment by ssddanbrown** [comment] 2022-10-12 14:02
Hi @micha141076,

- Do you see the same behavior [on our demo site](https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site)?
- Do you see the same behavior when using a different browser and/or using incognito/private mode?
- Can you confirm the exact version of web browser you're using and the operating system you're using that browser on.

**Comment by micha141076** [comment] 2022-10-13 12:01
Hi,
here my answers.

- the same problem
- the same problem
- Firefox, Chrome, Edge. all the same problem (incl. cach-cleaning). But only on my PC. On another PCit´s OK (I tested it 1h ago)

Have you an idea? Windows (both PC have the same windows-version)

**Comment by ssddanbrown** [comment] 2022-10-13 16:42
@micha141076 Just to confirm, did you try in a private/incognito browser, where all plugins should be disabled by default. If you allow plugins while in private/incognito mode, please disable them temporarily before testing.

**Comment by micha141076** [comment] 2022-10-18 15:46
Hi. Since it's not my PC, I'll check your suggestion again.

**Comment by ssddanbrown** [comment] 2022-11-04 11:41
I'm going to go ahead and close this off but if the cause can be explained/pin-pointed feel free to re-comment on this for it to be re-opened.

**Closed as completed by ssddanbrown** 2022-11-04 11:41 UTC
Labels: :bug: Bug
