### ISSUE TITLE
[Feature Request]: Support Onlyoffice integration as documenta backend or at least for viewing attachements

### ISSUE THREAD

**Issue by Kris33** [BookStackApp/BookStack#3129] opened 2021-12-29 16:49 UTC
### Describe the feature you'd like

It would be really good if onlyoffice document server was supported to view and edit attachements inside of bookstack even better if it was used for the edition backend (along with standard editor and Markdown editor)

### Describe the benefits this feature would bring to BookStack users

it would allow for user to edit attachements directly instead of downloading, editing, reuploading also it seems only office editor is better suited for complex documents edition.

**Comment by ssddanbrown** [comment] 2021-12-30 15:45
Thanks for the request although I'd consider this a duplicate of #3064 so I will therefore look to close this off as out of scope unless there's anything specifically new/different to discuss as part of this request.

**Comment by ssddanbrown** [comment] 2022-01-06 14:25
As per last comment, will close this off as out of scope.

**Closed by ssddanbrown** 2022-01-06 14:25 UTC
Labels: :moon: Out of scope, :hammer: Feature Request
