### ISSUE TITLE
the user style not work

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1842] opened 2020-01-14 02:54 UTC
the user styles specified in the settings do not work on the settings page. On other pages, styles work. Application Version - Latest DEV
http://localhost/settings

**Comment by james-geiger** [comment] 2020-01-14 03:26
Hi @Statium — This is by design.  The “Custom HTML Head” allows you to inject specific styles and JavaScript into the head of each page other than the settings page.  If you were to inject a script that broke the site or caused the browser to crash, you are still able to remove that script because it isn’t loaded on the settings page.

**Comment by ssddanbrown** [comment] 2020-01-19 16:29
Thank you @james-geiger for responding to this one. In addition, this is explained via text under that setting. 

Will therefore close this since it has been answered.

**Closed by ssddanbrown** 2020-01-19 16:29 UTC
Labels: :computer: Front-End, :question: Question
