### ISSUE TITLE
Upload image via URL. [Feature Request]: 

### ISSUE THREAD

**Issue by Abe-Telo** [BookStackApp/BookStack#3144] opened 2022-01-05 15:51 UTC
### Describe the feature you'd like

When uploading a image i need to first download the image. and then upload it manually, If we can upload the image via URL it can save us time. 

further more when we have a **img src** already imported, we should be able to right click on it and save it locally into our host converting the image as a uploaded  image. 

### Describe the benefits this feature would bring to BookStack users

1. Saving us time to download and reupload. 
2. In Firefox you can copy past content from other websites in HTML format. But image wont be uploaded locally unless downloaded and reuploading it.  Saving time is what everyone wants espechally if your dealling with alot of content. 

### Additional context

![image](https://user-images.githubusercontent.com/29134216/148246033-cde2b53f-f7cf-4d18-88fc-95f3c63fb284.png)

**Comment by ssddanbrown** [comment] 2022-01-05 15:54
Thanks for the request @Abe-Telo but I'd consider this a duplicate of #193 and will hence close this off.

**Closed by ssddanbrown** 2022-01-05 15:54 UTC
Labels: :hammer: Feature Request
