### ISSUE TITLE
<br></br> is used as newline in code blocks in markdown export

### ISSUE THREAD

**Issue by Szwendacz99** [BookStackApp/BookStack#3327] opened 2022-03-13 15:27 UTC
### Describe the Bug

When exporting page to markdown, new lines in code blocks are made with` <br></br>` tag, and it is obviously not being interpreted in any markdown viewer, so every code block end up as single line object with `<br></br>` tags inside

### Steps to Reproduce

1. Create multi-line code block on a page
2. export page as markdown

### Expected Behaviour

Proper newline character is used inside code blocks.

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/68295743/158066807-3592132c-043e-4df7-9c5f-f341110ec6d2.png)

### Exact BookStack Version

v22.02.3

### PHP Version

8.0

### Hosting Environment

Ubuntu-based docker containers

**Comment by ssddanbrown** [comment] 2022-03-23 15:15
This has now been addressed in dd7463259ad1f6384807616fe967e373003f3d69 and will be a part of the next feature release.
This was caused by behaviour of the WYSIYG editor, it means that an affected page may have to be edited/re-saved for it to be "fixed" by this change. 

Thanks @Szwendacz99 for reporting.

**Closed as completed by ssddanbrown** 2022-03-23 15:15 UTC
Labels: :bug: Bug, :memo: WYSIWYG Editor
