### ISSUE TITLE
Installation Script stops at 5/9 on Ubuntu 22.04

### ISSUE THREAD

**Issue by flashbong111** [BookStackApp/BookStack#4435] opened 2023-08-11 14:32 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I run the installation script and it stops at "5/9 Installing PHP dependencies using composer..."
I already tried it twice with a new server, no error or anything. It just redirects me to the command line...

This is very depressing...

### Exact BookStack Version

NA

### Log Content

NA

### PHP Version

NA

### Hosting Environment

Ubuntu 22.04

**Comment by Des2B** [comment] 2023-08-11 18:11
Can confirm this same issue on my end as well, this is what I'm finding in the installation logs.

![image](https://github.com/BookStackApp/BookStack/assets/142047293/3ba64293-5fab-430a-98f1-5acc4cb4f4a4)

**Comment by ssddanbrown** [comment] 2023-08-12 13:12
Hi both, I've just double checked this, by spinning up a fresh LXC Ubuntu 22.04 container, fully updating it to the latest packages, then running the install script. This is an x86_64 container system.
I was not able to reproduce this error, and whole install process completed without issue.

To both of you:
- Are you able to describe the environment at all? Is this running on a specific architecture or via a specific service?
- Do you have anything notable on the networking side of things? Any proxies or similar controls in play?

**Comment by Des2B** [comment] 2023-08-15 12:43
So for myself, I'm using VMWare 7.0.0 and have a Ubuntu 22.04 LTS with the latest updated installed. 

I have a firewall in place but no proxies, I suppose it's possible the firewall is blocking that traffic but past that I'm not sure.

**Comment by ssddanbrown** [comment] 2023-08-15 13:45
Thanks @Des2B, Have heard of some dodgy behaviour in VMware before, but that was related to MySQL not auto-starting, but that doesn't seem to be the same issue as your logs above.

Could try running the failing step manually to see if that also fails:

```bash
cd /var/www
sudo git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch bookstack
```

Also, have you tried running the script again since the error? (on a fresh instance). I'm wondering if this was just some GitHub downtime or similar network issue that temporarily caused an error.

**Comment by flashbong111** [comment] 2023-08-15 14:39
Hello,

we always get stuck here:
[image: image (2).png]

As you can see, it gets a connection timed out at the php composer.
We have set a every proxy possible wget, apt, git, environment and and and.
Our Firewall is not showing us, what gets blocked, nothing appears in the
log.

My guess is this that the script or php composer ignores the proxies we set
before... :(

Am Di., 15. Aug. 2023 um 15:45 Uhr schrieb Dan Brown <
***@***.***>:

**Comment by flashbong111** [comment] 2023-08-15 14:40
The Image: 
![image (2)](https://github.com/BookStackApp/BookStack/assets/142030459/97e3e8f6-1c0a-4397-9929-a825eb33035f)

**Comment by ssddanbrown** [comment] 2023-08-15 16:41
Thanks @flashbong111 for the extra info.
To be honest, The script (and BookStack itself) is not built to specifically support proxies nor are proxies tested with the script.

Composer does have [some guidance for use with proxies](https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy) though if that helps.

**Comment by ssddanbrown** [comment] 2023-08-22 13:12
I'll go ahead and close this off since it looks to be specific to when proxies are used.

**Closed as completed by ssddanbrown** 2023-08-22 13:12 UTC
Labels: :dog2: Support
