### ISSUE TITLE
Searching text in a particular book - found words don't highlighted 

### ISSUE THREAD

**Issue by asegrenev** [BookStackApp/BookStack#3833] opened 2022-11-07 08:43 UTC
### Describe the Bug

In search results within book found words don't highlighted. In search within all bookstack documents everything is ok.

### Steps to Reproduce

1. Go to https://demo.bookstackapp.com/books/it-department book
2. Type "location" in "Search this book" at left side and press Enter
3. Found words "location" don't highlited.

### Expected Behaviour

Words "location" from "Steps to reproduce" highlighted as in search within all bookstack documents.

### Exact BookStack Version

v22.09

### Hosting Environment

BoockStack Demo

**Comment by ssddanbrown** [comment] 2022-11-07 10:06
Thanks for the request but I'm going to close this off as a duplicate of #3407.

**Closed as completed by ssddanbrown** 2022-11-07 10:06 UTC
Labels: :cat2::cat2: Possible duplicate
