### ISSUE TITLE
Visual Theme Error

### ISSUE THREAD

**Issue by Arkantium** [BookStackApp/BookStack#3497] opened 2022-06-11 13:38 UTC
### Describe the Bug

I try to create a custom code in Visual Theme but i have always an error:
![image](https://user-images.githubusercontent.com/7194804/173190237-89cbac90-a2b4-4519-b481-820ce55b1e0d.png)

i have try rename the classe: ThisClassNotExistInPHPOrInBookstack
i have the same error. Bug in the Visual Theme ?

### Steps to Reproduce

Read the screen :)

### Expected Behaviour

Functionnal :)

### Exact BookStack Version

22.04.2

### Hosting Environment

PHP 8.0.19

**Comment by ssddanbrown** [comment] 2022-06-11 21:30
Hi @Arkantium,

I am not able to reproduce this error in my environment.
This kind of thing could occur if the theme functions file was loaded in multiple times instead of just once. 

Have you potentially altered the theme system core code or changed composer-based loading at all?

**Comment by Arkantium** [comment] 2022-06-11 23:07
Hi,

No modification for now :) just added the name in the .env 
I have try delete cache, optimize clear and reload composer but same...

**Comment by ssddanbrown** [comment] 2022-06-12 13:24
@Arkantium Okay, I just noticed the error shown in the screenshot appears to be on the command line.
What exactly are you doing when this error shows?

**Comment by Arkantium** [comment] 2022-06-12 16:23
php artisan optimize

**Comment by ssddanbrown** [comment] 2022-06-12 18:40
Ah, Okay. The optimize and cache commands are not something we specifically document or support.

This occurs because the cache commands start a secondary app instance which re-includes the theme functions file, which would then attempt to re-create any classes.

To work around this you can put you classes into separate files then `require_once` them into your `functions.php`.

**Comment by ssddanbrown** [comment] 2022-06-16 13:28
I'll therefore go ahead and close this off.

**Closed as completed by ssddanbrown** 2022-06-16 13:28 UTC
Labels: :bug: Bug
