### ISSUE TITLE
Arabic letters issue on export PDF

### ISSUE THREAD

**Issue by muath-ye** [BookStackApp/BookStack#5142] opened 2024-07-28 08:03 UTC
### Describe the Bug

The letters are not fixed in Arabic
![image](https://github.com/user-attachments/assets/f6123869-c4ea-4895-a732-1d5e6a40bdf9)

### Steps to Reproduce

Create a new boot
Write In Arabic
Export the book as PDF
You will see that the letters are not as you typed

### Expected Behaviour

It should be in normal Arabic strings

### Screenshots or Additional Context

Exported PDF with damaged Arabic letters
![image](https://github.com/user-attachments/assets/90a5b590-b7b4-48f3-927d-799826b96344)

Arabic string on the view 
![image](https://github.com/user-attachments/assets/bbaee6b2-ee4a-407d-83a7-00bf7ac5281c)

### Browser Details

Microsoft Edge Version 127.0.2651.74 Windows 11 Version 23H2

### Exact BookStack Version

v24.05.3

**Comment by ssddanbrown** [comment] 2024-07-28 10:17
Thanks for raising @muath-ye, but I'd consider this a duplicate of #4644 so I'll therefore close this off.
You may find better results for page-level export using the browser's "Print to PDF" functionality when viewing the page.

**Closed as completed by ssddanbrown** 2024-07-28 10:17 UTC
Labels: :bug: Bug, :cat2::cat2: Possible duplicate
