### ISSUE TITLE
[Feature/Enhancement] Possibility to publish the book online

### ISSUE THREAD

**Issue by xabispacebiker** [BookStackApp/BookStack#687] opened 2018-01-30 14:06 UTC
### For Feature Requests

Desired Feature: Add the functionality to publish the book online and make it visible to the public (or even better using the permission feature to set it as private, public or by invitation). 

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*:
* PHP Version:
* MySQL Version:

**Comment by yoginth** [comment] 2018-01-30 14:15
Other than **Invitation** everything is **available** @xabispacebiker :nerd_face:

**Comment by xabispacebiker** [comment] 2018-01-30 14:44
How can I publish? I read the documentation and it can only be exported as HTML, PDF or PLAIN TEXT. I must be missing something. On General Settings I set the Public View as disabled, but then in the book permission, I set permissions as follows:

![captura de pantalla 2018-01-30 a las 15 41 31](https://user-images.githubusercontent.com/1733884/35572185-63bd44b8-05d4-11e8-8e11-7f1930f9cc73.jpg)

Then I logout and try to access the book using the URL but I get to the login page.

**Comment by domainzero** [comment] 2018-01-31 00:17
@xabispacebiker 
You'll have to enable "Allow public viewing?" in the general settings to be able to access a page without logging in. You can set the permissions within the books, but public viewing doesn't work unless it's enabled.

**Comment by xabispacebiker** [comment] 2018-01-31 09:12
I understand, but what if I want to set a book not listed in the frontpage, but if I send the link to someone he can read it ?

**Comment by domainzero** [comment] 2018-01-31 15:29
Nope. Currently if "Allow public viewing" isn't set to "on" you will always be greeted with the login gate.

**Comment by ssddanbrown** [comment] 2018-02-01 23:04
Thanks @xabispacebiker for your suggestion. I believe this is essentially a duplicate of #288 so I'll therefore close this. Let me know if I've got that wrong and I'll re-open.

The good advice above by @domainzero is your best bet but, as discovered, BookStack will still list visible content on the homepage or in the books area.

**Closed by ssddanbrown** 2018-02-01 23:04 UTC

**Comment by xabispacebiker** [comment] 2018-02-06 22:51
Yep, I read #288 issue and that's exactly what I mean, so you can keep this one closed. Thanks
