### ISSUE TITLE
Draft error

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2235] opened 2020-08-27 07:17 UTC
version 0.29.3

When another user creates a draft and edits it, the draft appears in the workbook, but an error is displayed when trying to navigate. Also in the chapter this draft is not displayed.
![image](https://user-images.githubusercontent.com/4026090/91409529-f8628f00-e85e-11ea-9ad6-5b65615325f7.png)

![image](https://user-images.githubusercontent.com/4026090/91409557-00223380-e85f-11ea-8868-de4a8ebfd62f.png)

![image](https://user-images.githubusercontent.com/4026090/91409680-2ea00e80-e85f-11ea-891f-7471b39d83d9.png)

**Comment by DavidLeutgeb** [comment] 2020-08-28 05:37
This is related to: #2170

**Comment by ssddanbrown** [comment] 2020-09-05 17:02
Hi @Statium,
Thanks for reporting.

I am unable to re-produce this in my own development environment. Purple drafts should not be visible to anyone but the creator.
Can you confirm if this is reproducible (The visibility of drafts visible to non-creators) and, if so, the exact steps you are following to produce that scenario.

**Comment by ssddanbrown** [comment] 2021-01-10 23:16
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Closed by ssddanbrown** 2021-01-10 23:16 UTC
Labels: :bug: Bug, :factory: Back-End
