### ISSUE TITLE
Publish "built" releases that include composer based dependencies.

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#2587] opened 2021-02-24 09:48 UTC
**Describe the feature you'd like**
Currently only the source code from the Github repository is published on a release.  This is a request to also publish a "fully built" version of BookStack.  By which I mean the composer based dependencies are already included (the result after running `composer install`).  The resulting archive should contain everything necessary to run BookStack.

**Describe the benefits this feature would bring to BookStack users**
This would benefit users who can not run composer (for whatever reason).  Specifically for my use case this would allow me to create a FreeBSD port and pre-built package that would let interested users install BookStack with a single command (ie. `pkg install -y bookstack`) using the operating system's package management system.

**Additional context**
As a security precaution, the FreeBSD port build infrastructure does not allow network access during an application's build step.  Therefore language level dependency management systems that can not operate in offline mode are unable to run.

**Comment by ssddanbrown** [comment] 2021-02-25 00:04
Thanks for the suggestion @tuaris and for explaining the use-case. 
I'm going to close this though as I'd consider this to essentially be a duplicate of #161. 

I've played about with implementing something a few times, but never spent enough time to get something formalised. The trouble is that if I go down that road I'd want to do it properly (Separate command line utility to properly organise the files, hash-verification of app files with hashes hosted on separate system).

**Closed by ssddanbrown** 2021-02-25 00:04 UTC
Labels: :cat2::cat2: Possible duplicate
