### ISSUE TITLE
book export PDF contents directory link does not work

### ISSUE THREAD

**Issue by Tusher43** [BookStackApp/BookStack#3442] opened 2022-05-17 19:26 UTC
### Describe the Bug

when you click on the hyperlinks in the contents directory on the first page of the PDF book export, they want to redirect you to an html page which is located in file://tmp/... and not to the corresponding page in the PDF book.

### Steps to Reproduce

1. export a book as PDF
2. click on any page in the exported PDF in the contents directory

### Expected Behaviour

that it jumps in the pdf to the corresponding page

### Screenshots or Additional Context

![Unbenannt](https://user-images.githubusercontent.com/63962141/168894042-820ee13a-1921-42e9-92d9-5c7bb02a5104.PNG)

### Exact BookStack Version

22.04.2

### Hosting Environment

as a Docker container from linuxserver

**Comment by ssddanbrown** [comment] 2022-05-17 22:39
Thanks for reporting @Tusher43, but I'm going to close this off as a duplicate of the existing open issue #2459.

**Closed as completed by ssddanbrown** 2022-05-17 22:39 UTC
Labels: :bug: Bug
