### ISSUE TITLE
Allow role to delete own pages and chapters in specific shelves/books

### ISSUE THREAD

**Issue by BEFRSE** [BookStackApp/BookStack#4386] opened 2023-07-18 05:55 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

we use bookstack across our company with multiple departments. We have one shelf with general information where everyone has access to. Also each department has their own shelf, which they manage on their own. The members of each department are in a corresponding AD-Group which we give access to the shelf. 

We now want to allow the users to delete the pages and chapters they created. However it seems like this is not possible or at least we didn't find a way to accomplish it. While it's possible to set granular permissions to a role (i.e. allow deleting own pages and chapters, but not books), there's only a general "Delete" permission an content level. If "Delete" is unchecked for a book permission, the members of that role can't delete anything inside the book. As soon as "Delete" is checked, they can delete not only their own pages and chapters; they now can delete everything, including the whole book itself. Regardless of what is checked in the role permission settings.

Is there really no way to allow a group to only fully manage own pages/chapters but not for the whole wiki, only for specific books? If so, what could be a possible workaround?

Thanks in advance.

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 20.04 LXC Container; installed using the official install script

**Comment by ssddanbrown** [comment] 2023-07-18 10:08
> Is there really no way to allow a group to only fully manage own pages/chapters but not for the whole wiki, only for specific books?

There are no "own" permission options outside the role permissions. If item-level permissions prevent inheritance, or if there's a more applicable/specific item-level role permission, then that will override any role-level permissions including "own" permissions.

>  If so, what could be a possible workaround?

Only to change the permission setup to avoid preventing role permission inheritance, or overrides to relevant roles.

---

Lightly related to #3964 and #1747.

**Comment by BEFRSE** [comment] 2023-07-18 10:14
Thank you. So in conclusion, with the current way the permission system is designed, what we are trying to accomplish is not possible, right? So we have to either allow the role to be able to delete everything inside the books (including the books themselves) or deny deleting everything at all, including pages/chapters they created.

**Comment by ssddanbrown** [comment] 2023-07-18 10:24
It's hard to say without knowing the functional requirements of your situation (this is not a request for that detail though).
You can always set permissions at a chapter/page level too.
Sometimes it's possible to invert your approach, and use permissions to block instead of allow (or vice-versa) to avoid overriding.
Or it may be possible to be targeted with item-level overrides as to not require prevention of inheritance.

**Comment by ssddanbrown** [comment] 2023-09-11 13:19
Since there's been no further discussion since my last message on this support thread I'll go ahead and close this off.

**Closed as completed by ssddanbrown** 2023-09-11 13:19 UTC
Labels: :dog2: Support

**Comment by m-ocean-it** [comment] 2024-03-29 05:11
Greetings! The issue is relevant for my organization, too. It's weird that permissions on the role-level make distinction between own and rest content while content-level overrides don't.

Also, @BEFRSE, I wonder if you've found a solution.
