### ISSUE TITLE
I can't upload Images or Files

### ISSUE THREAD

**Issue by n3yus** [BookStackApp/BookStack#4186] opened 2023-04-20 16:37 UTC
### Attempted Debugging

- [x] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hey, I have the problem, that i can't uploade any images or files. I also tried this command:
`chown www-data:www-data -R bootstrap/cache public/uploads storage && chmod -R 755 bootstrap/cache public/uploads storage`, but i didn't do anything. I got everytime the error code: 0.

![image](https://user-images.githubusercontent.com/81981815/233430645-d37ec5bf-7ca8-4d34-8986-a8e1bc6c884f.png)

### Exact BookStack Version

 v23.02.3

### Hosting Environment

Ubuntu v22.04.01-live-server

**Comment by ssddanbrown** [comment] 2023-04-20 20:16
Hi @neyusyt,
Can you confirm exactly how you installed BookStack, and if there are any other parts in play (Proxies/Cloudflare/Other HTTP Layers).

**Comment by NEYUS-GITHUB** [comment] 2023-04-21 05:25
@ssddanbrown i installed Bookstack with the official Start.sh in the Homepage. The Domain is hosted by cloudflare and i configuraded as a tunnel over a Ubuntu vm.

**Comment by ssddanbrown** [comment] 2023-04-21 10:20
@neyusyt We have no official `start.sh` on our homepage?

Either way, it's not clear where the error is coming from.
Assuming you've used our Ubuntu 22.04 install script, can you watch the `/var/log/apache2/access.log` file and confirm if you see lines added exactly when the error occurs.
If not, it's likely something in front of the BookStack machine webserver blocking the request. It's worth checking logs for the Cloudflare proxy if they provide it.

**Comment by n3yus** [comment] 2023-04-21 13:24
I can't open that file: `/var/log/apache2/access.log`, because this location doesn't exist. I can't the logs from Cloudflare Proxie. I searched a lot, but i cant find a log file.

**Comment by ssddanbrown** [comment] 2023-04-22 10:22
> I can't open that file: /var/log/apache2/access.log

How exactly did you install BookStack? You may need to look into these folders with superuser/root privileges.

**Comment by n3yus** [comment] 2023-04-27 16:36
@ssddanbrown I installed with this script: 
```
Download the script
wget https://raw.githubusercontent.com/BookStackApp/devops/main/scripts/installation-ubuntu-22.04.sh

Make it executable
chmod a+x installation-ubuntu-22.04.sh

Run the script with admin permissions
sudo ./installation-ubuntu-22.04.sh

edit .env file
nano /var/www/bookstack/.env
```

in the log file (`/var/log/apache2/access.log`) isn't anything suspects.

**Comment by ssddanbrown** [comment] 2023-04-27 17:22
> in the log file (/var/log/apache2/access.log) isn't anything suspects.

But do you see any lines logged at exactly the same time you reproduce the error?

**Comment by n3yus** [comment] 2023-04-27 18:16
@ssddanbrown No it doesn't logged anything

**Comment by ssddanbrown** [comment] 2023-04-27 21:05
@neyusyt Okay, that often means that it's an issue before the request is hitting the webserver.
Could be an issue around that cloudflare proxy. 

Other things to try:
- If possible, try without having the cloudflare proxy involved to rule that out.
- Try a much smaller file image file size to see if that works.
- Look at the request and response in the network tab of the browser developer tools to see if there's more information provided there (Request would likely show as a red line within the table, after reproducing the error).

**Comment by ssddanbrown** [comment] 2023-05-14 18:31
Since there's been no further follow up I'll close this off.

**Closed as completed by ssddanbrown** 2023-05-14 18:31 UTC
Labels: :dog2: Support

**Comment by alexanderisora** [comment] 2024-05-20 15:47
@ssddanbrown hello Dan. I was having the same problem.

I was able to fix the issue by deactivating Cloudflare proxy. I still want to use Cloudflare for 2 reasons:
1) SSL certificate (the Bookstack installation guide does not provide information about installing SSL)
2) Cloudflare gives many features for my website for free and it is a common practice to use it.

What can I do to enable Cloudflare? Thanks!

**Comment by ssddanbrown** [comment] 2024-05-20 16:32
@alexanderisora Please open a new support issue specific to your scenario & environment.
Information here may be now irrelevant or outdated.
