### ISSUE TITLE
search cannot handle dots (.) correctly

### ISSUE THREAD

**Issue by stothew** [BookStackApp/BookStack#2843] opened 2021-07-12 14:45 UTC
**Description:** 
if you search for something with a dot in it there is no result.

Hi there,
first of all, I love BookStack so far. But at the moment I do network documentation and cannot search for any IP Address because of the dots breakdown. 
Sorry for dig the old stuff, but is this still a wanted behavior?
Masking them is not a good solution. 
greets

**old issue:**
[https://github.com/BookStackApp/BookStack/issues/724](https://github.com/BookStackApp/BookStack/issues/724)

**Comment by ssddanbrown** [comment] 2021-07-12 19:47
Thanks for reporting.
I'm going to close this in favour of centralising some of these similar requests into a single issue as the cause is all the same.

Merging into #2095.

**Closed by ssddanbrown** 2021-07-12 19:47 UTC
