### ISSUE TITLE
GuzzleHttp\Exception\ClientException Client error: `POST https://login.microsoftonline.com/common/oauth2/token` resulted in a `401 Unauthorized` response

### ISSUE THREAD

**Issue by amahmou** [BookStackApp/BookStack#2099] opened 2020-05-05 19:25 UTC
Hi, 

i can t login with Microsoft AZURE ( qith MFA activated ) on my Bookstack 

**Steps To Reproduce**
1. Go to 'Login with Microsoft AZURE'
2. See error
LOG : 
https://flareapp.io/share/47qVaa5W#F57

**Comment by ssddanbrown** [comment] 2020-06-29 22:29
Hi @amahmou,
Sorry for my late reply. 
In the error message, it looks like microsoft is providing the message "Invalid client secret".

Can you double check the value of the secret that you have configured in your BookStack `.env` file? 
Does it contain any special characters or spaces?

**Comment by danielslyman** [comment] 2020-07-24 16:08
I have the same issue unfortunately, and yes, my secret do have special characters. Any way to fix this?

Thank,
Daniel

**Comment by danielslyman** [comment] 2020-07-24 16:18
uzzleHttp\Exception\ClientException
Client error: `POST https://login.microsoftonline.com/common/oauth2/token` resulted in a `401 Unauthorized` response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 2e46836e-e (truncated...)

**Comment by danielslyman** [comment] 2020-07-24 16:25
This may help:
https://stackoverflow.com/questions/41133573/microsoft-graph-rest-api-invalid-client-secret

**Comment by danielslyman** [comment] 2020-07-27 08:47
@ssddanbrown - could you please please help? This would be perfect for our organisation but we need this integration to make it workable for us.

**Comment by ssddanbrown** [comment] 2020-07-28 12:22
@danielslyman Can you try wrapping the secret in quotes within the `.env` file? So like:

```bash
AZURE_APP_SECRET="my-secret-key"
```

Otherwise, can you rengerate the key in azure?

Otherwise, please can you confirm your BookStack version & confirm if you have MFA active in azure.

**Comment by danielslyman** [comment] 2020-07-28 16:03
I can confirm that wrapping the secret in quotes rather than brackets does the trick! Thanks so much for helping :)

**Comment by danielslyman** [comment] 2020-07-28 16:59
Follow-up:

What would be the easiest way to hide the regular login form? Are those css classes/ids used elsewhere or can I simply do a display: none; ?

Thanks,
Daniel

**Comment by ssddanbrown** [comment] 2020-07-28 17:27
@danielslyman Awesome, Glad that worked. Will therefore close this off.

For the login form, you could use the action of the form itself, like so:

```html
<style>
form[action$="/login"], form[action$="/login"] + hr {
    display: none;
}
</style>
```

**Closed by ssddanbrown** 2020-07-28 17:27 UTC
Labels: :dog2: Support, :door: Authentication

**Comment by danielslyman** [comment] 2020-08-01 09:51
> @danielslyman Awesome, Glad that worked. Will therefore close this off.
> 
> For the login form, you could use the action of the form itself, like so:
> 
> ```
> <style>
> form[action$="/login"], form[action$="/login"] + hr {
>     display: none;
> }
> </style>
> ```

I can confirm this works perfectly, should remove the confusion for staff. I also opted for the snippet below, removing the + hr to retain the line separator - looks more pleasing to me.

<style>
form[action$="/login"], form[action$="/login"]  {
    display: none;
}
</style>


Thank you so much!
