### ISSUE TITLE
The '+' signs are not visible on the document page

### ISSUE THREAD

**Issue by alabastrowa** [BookStackApp/BookStack#4293] opened 2023-06-08 13:01 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

I've been using bookstack for a long time. Recently, I came across a problem where after saving the document on the page, the '+' sign is not visible. The sign is visible when I edit the document and the search engine sees it because when I enter '+' in the search field, the system will indicate the document that contains it.

Have any of you encountered this problem? I am asking for help in solving it or a hint in which files I can look for a solution to the problem.
I attach photos with a graphic description of the problem. 

Regards!
![search results](https://github.com/BookStackApp/BookStack/assets/97252754/0078def6-2a07-43c7-a537-fb145f90bcac)
![page](https://github.com/BookStackApp/BookStack/assets/97252754/96cb430c-cf91-419f-9a9e-b072708d66ad)
![edit page](https://github.com/BookStackApp/BookStack/assets/97252754/3e502e6b-b93b-4c37-8a3b-290c23974962)

### Exact BookStack Version

v21.12.1

### PHP Version

7.3

### Hosting Environment

Debian 10.

**Comment by ssddanbrown** [comment] 2023-06-08 16:50
Hi @alabastrowa,
This is not something I can reproduce [on our demo instance](https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site) which runs the latest version.
I'd guess this issue is only relevant to an older version of BookStack and has since been addressed, or it's an issue specific to your environment.

If you upgrade to use the latest version, and the issue persists, I can help in diagnosing the potential issue further but I otherwise don't support older versions.

**Comment by alabastrowa** [comment] 2023-06-08 20:42
Hi,
Thanks for the answer. And is it possible for me to test install the bookstack version that I have, i.e. v21.12.1 without any modifications? I would like to compare the files on the new machine with what I have at home to find differences.
Unfortunately, I cannot find v21.12.1 online. Maybe you own it and it would be possible for you to share it with me?

Regards.

**Comment by ssddanbrown** [comment] 2023-06-08 20:50
@alabastrowa I'm not sure I understand. Are you trying to see if your version has modifications? Is so, and you followed our general install guidance originally, your instance should be managed via git. You could run `git status` to show any changes that have been made to core app files.

Otherwise, you can get a download of the `v21.12.1` files from the bottom of [this release page](https://github.com/BookStackApp/BookStack/releases/tag/v21.12.1), if that's what you're asking for.
Note: You should not install from a ZIP or plain files, you should manage the codebase via `git` otherwise updates will be difficult.

**Comment by alabastrowa** [comment] 2023-06-09 10:13
So how well do I understand the following files in the source code (zip) will allow me to install bookstack v21.12.1?

**Comment by ssddanbrown** [comment] 2023-06-09 20:12
Sorry, I still don't really understand. 
I do **not** advise installing/updating via ZIPs of source code. Unless using container-based options, installs should be managed via `git` as per our official documentation/guidance.

**Comment by ssddanbrown** [comment] 2023-06-20 12:50
Since there's been no further follow-up, I'll go ahead and close this off.

**Closed as completed by ssddanbrown** 2023-06-20 12:50 UTC
Labels: :dog2: Support
