### ISSUE TITLE
Save Draft Error

### ISSUE THREAD

**Issue by ospouh** [BookStackApp/BookStack#5254] opened 2024-10-10 19:27 UTC
### Describe the Bug

On a fresh installation with CloudLinux,  save-draft gives error 404

![image](https://github.com/user-attachments/assets/85c6f96d-5fe6-46b3-b375-df96b96a0bf7)

### Steps to Reproduce

Create a new page
press ctrl + s
error appears in console

### Expected Behaviour

draft to save successfully

### Screenshots or Additional Context

![image](https://github.com/user-attachments/assets/541fb630-d7a7-4754-8019-1c7fb46e4737)

### Browser Details

Chrome

### Exact BookStack Version

24.10

**Comment by ssddanbrown** [comment] 2024-10-10 19:49
Hi @ospouh,

- Are there some specific steps you followed to install BookStack on CloudLinux?
- Can you share your apache config for BookStack?
- Does the URL of the shown request exactly match the full base URL used to access the site homepage (including protocol) followed by `/ajax/page/<number>/save-draft`?

**Comment by ospouh** [comment] 2024-10-11 13:48
Hi @ssddanbrown 

i believe i might have discoverd the problem and it might be from mod_security
Request:	PUT /ajax/page/612/save-draft

it looks like modsecurity by default blocked PUT and Delete Methods causing the API to fail

**Comment by ssddanbrown** [comment] 2024-10-14 10:10
@ospouh Good to hear you found the cause, I'll therefore close this off.
Note that, depending on configuration, other parts of BookStack may trigger mod security (commonly around using specific words/text in page/description content).

**Closed as completed by ssddanbrown** 2024-10-14 10:10 UTC
Labels: :bug: Bug
