### ISSUE TITLE
LDAP AD Primary Group and Roles

### ISSUE THREAD

**Issue by JamHeHe** [BookStackApp/BookStack#4064] opened 2023-02-24 14:51 UTC
### Describe the Bug

I've associated our Domain Admin group to the Admin role in BookStack. I have one user who had the Domain Admin group set as the primary group for that user. In BookStack that user would not get associated to the Admin Role until I set the user's primary group to a different group.

### Steps to Reproduce

1. Setup LDAP for AD
2. Associate Domain Admin Group to Admin Role
3. Set user's primary group to Domain Admin in AD
4. Login as user and see that Admin Role is not associated appropriately

### Expected Behaviour

Admin access in BookStack regardless of Primary Group setup in AD.

### Exact BookStack Version

23.01.1

### PHP Version

8.1.2-1

### Hosting Environment

Ubuntu 22.04 LTS

**Comment by ssddanbrown** [comment] 2023-02-24 15:54
Hi @JamHeHe,

I can't really help from an active directory point of view. 
I don't really know how steps 2 or 3 of your reproduction steps are performed or what they would actually result in.

All that BookStack cares about is that groups are provided on the `LDAP_GROUP_ATTRIBUTE` of the user fetched from the LDAP system upon login, and that group sync has been configured correctly. 

I'm going to re-label this as a support issue since it's not clear there's any bug in BookStack.

**Comment by JamHeHe** [comment] 2023-02-24 16:15
Understood, and thanks. I agree that's it quite possibly not BookStack's
issue at all. I partially just wanted to get it posted somewhere to help
someone who may see a similar issue in the future and save them some time
and trouble, but couldn't find a forum or anything I could just post it in.

Thanks for all your work on BookStack!

**Comment by ssddanbrown** [comment] 2023-02-24 16:23
@JamHeHe Ah, okay and thanks!

I'll therefore close this off but if you need any additional help, from a BookStack specific perspective, or you do find a proven issue with BookStack's handling, feel free to still comment or open a new issue.

**Closed as completed by ssddanbrown** 2023-02-24 16:23 UTC
Labels: :dog2: Support
