### ISSUE TITLE
Terms & Conditions in Footer (or some where else)

### ISSUE THREAD

**Issue by wojosc** [BookStackApp/BookStack#2592] opened 2021-02-25 10:29 UTC
Hi @ssddanbrown thank you for creating great software. I love using it.

In Germany (and other places I'm sure) there are legal requirements for website that we include legal terms & conditions so a visiter can find information about the host of the content.

My tech guys have found a solution in which they jus created a page with the content and added a link to the top bar as shown in the following picture:
![image](https://user-images.githubusercontent.com/22279621/109140227-a989a980-775c-11eb-840f-7b01d1735cd8.png)

Am I missing the option to set this up some where or is this not included in your software at this time?

Kind Regards
Wolfram

**Comment by ssddanbrown** [comment] 2021-02-25 21:53
Thanks for the request and feedback @wojosc.

> Am I missing the option to set this up some where or is this not included in your software at this time?

You're not missing anything, It's not possible in the current release but it has been merged as part of the current release cycle so will be part of the next feature release. Please see the following issue for more detail: https://github.com/BookStackApp/BookStack/issues/854#issuecomment-770304122

Since this is effectively a duplicate of #854 I'm going to close off this issue.

**Closed by ssddanbrown** 2021-02-25 21:53 UTC
Labels: :cat2::cat2: Possible duplicate

**Comment by wojosc** [comment] 2021-02-25 21:55
That will cover that more than sufficient. Thanks!
