### ISSUE TITLE
Comments : Author's name does not appear if too long

### ISSUE THREAD

**Issue by gblondet117** [BookStackApp/BookStack#4489] opened 2023-08-31 14:55 UTC
### Describe the Bug

Hello,

we have a user with a long name (26 letters). If he writes a comment on a page, his name does not appear on the top of the comment.
He changed his name with a shorter version (4 letters), and the name appears.

I don't know what is the exact limit, but with me (14 letters), it works.

PS : thank you very much for your work @ssddanbrown, we will plan to update bookstack to get the new notification system, it looks promising.

### Steps to Reproduce

1. Change your name in your profile with a long name.
2. Write a comment in a page.
3. Check if the name is shown on the head of the comment.
4. Retry with a shorter name.

### Expected Behaviour

The name should be shown, or at least with "..." at the end if it is too long.

### Browser Details

Brave or Firefox

### Exact BookStack Version

23.06.2

### Hosting Environment

Debian 12

**Comment by Bajszi97** [comment] 2023-09-11 16:49
I was able to reproduce the bug. The username is disappearing because the method getShortName() in the User Model returns an empty string if the username is too long, even after being split into parts.

A possible solution could be to return the first n-2 characters of the user's name, followed by '...' so that 'Userwithlongname' would become 'Userwi...'' in the default 8-letter case.

I would gladly make these changes if it's an acceptable solution and if I receive some guidance on how and where to push the changes. This would be my very first contribution to an open-source project.

**Comment by ssddanbrown** [comment] 2023-09-11 17:22
@Bajszi97 I'd be happy with that solution, as long as it's done as a last resort (after the existing attempt to split on spaces). Feel free to change within the `getShortName` method.

Happy to support you in your first open source contribution.
You'd follow the general "fork -> push changes to branch on fork > then create a pull request" flow of GitHub.
[This page covers the process](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) pretty well.
For BookStack, work should be done on the development branch. [Details of that and our development processes here](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/development.md).

Just let me know if you need further specific guidance.
I have assigned this to the next feature release, so if there's not much evidence of progress coming up to release I may query, and push things along myself depending on where things are at.

**Comment by ssddanbrown** [comment] 2023-09-13 09:21
Thanks to @Bajszi97 in #4533, this has now been addressed, and will be part of the next feature release.
Thanks @gblondet117 for raising.

**Closed as completed by ssddanbrown** 2023-09-13 09:21 UTC
Labels: :bug: Bug, :mag: Pending Validation
