### ISSUE TITLE
Error 500 when opening the gallery

### ISSUE THREAD

**Issue by awesome-michael** [BookStackApp/BookStack#2920] opened 2021-09-10 09:44 UTC
**Describe the bug**
When I try to insert an image on a page I get an error 500 from the server

**Steps To Reproduce**
1. Edit a page
2. Click on 'Insert an image'
3. See error `GET https://example.com/images/gallery?page=1&uploaded_to=142 500` in the browser console

**Expected behavior**
Gallery shows images that were uploaded

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.08.2
 - PHP Version: 7.4.23
 - Hosting Method (Nginx/Apache/Docker): Docker Image from here: https://hub.docker.com/r/linuxserver/bookstack

**Additional context**
I tried to debug the error but can't find anything related in the error logs at storage/logs/laravel.log and even setting the APP_DEBUG=true in the .env file didn't reveal any information on the error (I think the setting didn't change anything at all).

**Comment by ssddanbrown** [comment] 2021-09-11 22:25
Hi @awesome-michael,

- Are you able to add and remove attachments okay on your instance? 
- Do you have any web development experience/skills? (Just for me when thinking of next steps to help debug.)

**Comment by awesome-michael** [comment] 2021-09-12 16:40
Hi @ssddanbrown,

- Yes, adding and removing attachments works without problems, I also noticed that I can upload images and they show up in the "insert image" menu under the book or page tab. But the "all" tab still generates the error 500
- Yes I have development experience. I just can't get the app to log the error properly (or I'm not able to find the log) so I have no idea where to start debugging.

**Comment by ssddanbrown** [comment] 2021-09-13 13:32
@awesome-michael Something to try below. I suspect this is either due to query parameters not being passed as expected (Can occur when there's a slight proxy/webserver misconfiguration) or a particular image is causing trouble when a thumbnail is attempting to be generated.

- Could you take a screenshot of what's visible when you access the `https://example.com/images/gallery?page=1&uploaded_to=142` URL directly (But on your instance)? Just want to understand the level at which this is generated, hoping the error screen can provide some clues.
- Does the search system work okay? Or does it show the same results no matter the search term?

**Comment by awesome-michael** [comment] 2021-09-17 06:58
- When accessing the URL directly the browser just shows the error 500.. no additional error message
- The search works just fine, no errors
![error500](https://user-images.githubusercontent.com/37796947/133738584-554ba5c4-3c20-4c62-9cf4-a683ff7e1296.jpg)

**Comment by ssddanbrown** [comment] 2021-09-17 21:40
Hi @awesome-michael,
This is not an error being handled at a BookStack level, but more likely at a webserver level. You'll need to check your webserver's error logs. Since you're using a docker setup keep in mind that you'll likely have mulitple web-servers at play (One inside and one outside the container).

**Comment by ssddanbrown** [comment] 2021-09-29 17:09
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Closed by ssddanbrown** 2021-09-29 17:09 UTC

**Comment by badsmoke** [comment] 2023-08-21 18:38
we now have the same problem

this error message appears in the console


browser console log:

````
GET https://wiki.domain.com/subdir/images/gallery?page=1&uploaded_to=474 500

app.js?version=v23.06.2:18 Uncaught (in promise) Error
    at No (app.js?version=v23.06.2:18:1440)
    at async tn.loadGallery (app.js?version=v23.06.2:19:76647)
````


but it has definitely worked before.

bookstack runs behind an nginx and a subdir


thank you

**Comment by al-cheb** [comment] 2023-08-21 21:00
@ssddanbrown, @badsmoke 
In my case I have uploaded a high resolution png(16000x16000) file ~ 8mb and after that I got the 500 error.

Steps to reproduce:
1. Upload image https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F9clb0corsmr81.png
2. Check that the file has been uploaded
```
www-data@bookstack-579844c674-rbwbg:~/bookstack$ ls -lah public/uploads/images/gallery/2023-08/9clb0corsmr81.png 
-rw-r--r-- 1 www-data www-data 6.9M Aug 21 20:51 public/uploads/images/gallery/2023-08/9clb0corsmr81.png
```
3. Image Select returns 500
4. Remove the local file
```
www-data@bookstack-579844c674-rbwbg:~/bookstack$ rm public/uploads/images/gallery/2023-08/9clb0corsmr81.png
```
5. Image Select returns 200

I know this case is very rare but it's difficult to debug such kind behavior and easy to block the Image Selector .

**Comment by ssddanbrown** [comment] 2023-08-21 21:16
Yeah, large images can lead to memory being exhausted when attempting to resize.
Maybe we should force fail upon upload in these scenarios with applicable warning, will have to test how easy it is to catch since it's an out-of-memory situation.

**Comment by al-cheb** [comment] 2023-08-21 21:37
Yeah, it would be great if we have a warning on upload and replace a preview icon if a file can't be properly displayed to make it easy to find .

**Comment by ssddanbrown** [comment] 2023-08-21 22:09
@al-cheb I'd probably just prevent the upload entirely (with a better warning/error message) if it can't be resized, rather than add control to set a custom preview icon. We also resize to make the image used within content reasonable. I don't want to end up where users can easily upload and use massive multi-MB in content. Can always resort to attachments instead if a massive image really does need to be uploaded.

**Comment by ssddanbrown** [comment] 2023-08-21 22:14
I've opened up #4454 as an intent to improve things as discussed above, which is assigned to a future maintenance release.

**Comment by badsmoke** [comment] 2023-08-22 05:42
you guys are great, I write just before going to sleep and when I wake up you have already taken care of it :-D

i just checked, the files are all about 2.7mb in size, when i delete them the gallery loads again.

when uploading again, comes the error 

`POST https://wiki.domain.com/images/gallery?uploaded_to=474 500`

I also see no cpu or ram load when uploading

**Comment by ssddanbrown** [comment] 2023-08-22 12:33
@badsmoke 

> I also see no cpu or ram load when uploading

It's probably hard to observe since the default PHP RAM limit is often small and this will only spike for a very quick moment.

The PHP option `memory_limit` defaults to 128MB in most cases, increasing this option (usually via a relevant `php.ini` file) can help handle much larger images.

**Comment by badsmoke** [comment] 2023-08-28 08:25
thank you, a increasing has solved the problem
