### ISSUE TITLE
after upgrade, clicking 'Edit Profile' throws an error - ReflectionException (-1) Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist

### ISSUE THREAD

**Issue by lynchpatrickj** [BookStackApp/BookStack#994] opened 2018-08-31 02:56 UTC
**Describe the bug**

Following upgrade from 0.19 to the latest 0.23.2 version, I noticed that clicking on the Edit Profile option throws an error in the browser:

ReflectionException (-1)
Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist

Tried clearing the artisan cache but it errors out the same way:

> plynch@bookstack:/var/www/bookstack$ sudo php artisan cache:clear
> 
>                                                                         
>   [ReflectionException]                                                 
>   Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist  
>                                                                         

This worked previously. Apologies if this is completely obvious - don't know my way around these dependencies and not sure what to do next.

**Steps To Reproduce**

1. Log into bookstack via remote browser
2. Click on the logged-in user icon in the top-right corner
3. Click 'Edit Profile'

**Expected behavior**
I expect to see the Edit Profile settings.

**Screenshots**

Log info below:

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): 

**Additional context**

ReflectionException thrown with message "Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist"

Stacktrace:
#87 ReflectionException in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
#86 ReflectionClass:__construct in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
#85 Illuminate\Container\Container:build in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
#84 Illuminate\Container\Container:resolve in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:586
#83 Illuminate\Container\Container:make in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:732
#82 Illuminate\Foundation\Application:make in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:387
#81 Illuminate\Events\Dispatcher:createClassCallable in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:368
#80 Illuminate\Events\Dispatcher:Illuminate\Events\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
#79 Illuminate\Events\Dispatcher:dispatch in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:465
#78 event in /var/www/bookstack/vendor/socialiteproviders/manager/src/ServiceProvider.php:18
#77 SocialiteProviders\Manager\ServiceProvider:boot in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
#76 call_user_func_array in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
#75 Illuminate\Container\BoundMethod:Illuminate\Container\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
#74 Illuminate\Container\BoundMethod:callBoundMethod in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
#73 Illuminate\Container\BoundMethod:call in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
#72 Illuminate\Container\Container:call in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:792
#71 Illuminate\Foundation\Application:bootProvider in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:595
#70 Illuminate\Foundation\Application:register in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:706
#69 Illuminate\Foundation\Application:registerDeferredProvider in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:686
#68 Illuminate\Foundation\Application:loadDeferredProvider in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:729
#67 Illuminate\Foundation\Application:make in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:885
#66 Illuminate\Container\Container:resolveClass in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:813
#65 Illuminate\Container\Container:resolveDependencies in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:780
#64 Illuminate\Container\Container:build in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
#63 Illuminate\Container\Container:resolve in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php:586
#62 Illuminate\Container\Container:make in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:732
#61 Illuminate\Foundation\Application:make in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:79
#60 Illuminate\Routing\ControllerDispatcher:transformDependency in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:46
#59 Illuminate\Routing\ControllerDispatcher:resolveMethodDependencies in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:27
#58 Illuminate\Routing\ControllerDispatcher:resolveClassMethodDependencies in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:41
#57 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#56 Illuminate\Routing\Route:runController in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#55 Illuminate\Routing\Route:run in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
#54 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#53 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/app/Http/Controllers/Controller.php:44
#52 BookStack\Http\Controllers\Controller:BookStack\Http\Controllers\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:131
#51 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#50 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/app/Http/Middleware/Authenticate.php:48
#49 BookStack\Http\Middleware\Authenticate:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#48 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/app/Http/Middleware/Localization.php:28
#46 BookStack\Http\Middleware\Localization:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#43 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
#40 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#37 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#34 Illuminate\Session\Middleware\StartSession:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#28 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#25 Illuminate\Pipeline\Pipeline:then in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
#24 Illuminate\Routing\Router:runRouteWithinStack in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
#23 Illuminate\Routing\Router:runRoute in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
#22 Illuminate\Routing\Router:dispatchToRoute in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
#21 Illuminate\Routing\Router:dispatch in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
#18 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/fideloper/proxy/src/TrustProxies.php:56
#15 Fideloper\Proxy\TrustProxies:handle in /var/www/bookstack/app/Http/Middleware/TrustProxies.php:45
#14 BookStack\Http\Middleware\TrustProxies:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/bookstack/public/index.php:53

----

nvironment & details:
GET Data empty
POST Data empty
Files empty
Cookies
remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d	
"eyJpdiI6IlFPWVVjVUFXWEpoSncxOFdWQnhTTFE9PSIsInZhbHVlIjoiUjlibHFwc3pMMmF1SENoVFhcL2twWUdlNks5OG1iNnJkZHpvbk5tRUVZVjdvMVBcL2xqTHROR0VzcGRnZzlma0p0aDIra1wvK2lnYVk0 ▶"
XSRF-TOKEN	
"eyJpdiI6IkUrRWJNeTJNcjNvZDhlSElLNU1oQ3c9PSIsInZhbHVlIjoiWDVYTjArajZPaEduVzQways1RlVQM3QzNngzSDZsKzBUUkxWQUZINlBxa0hYU2ZXU2t1VXJzckR3Vnh2N29ueUZqZ0xrRlRUWG5SN2FC ▶"
laravel_session	
"eyJpdiI6Imd6Rk5tV1NXaFhMVkZ4Z3N4d2R4OVE9PSIsInZhbHVlIjoiOHUzRk9HMkZBdmNEZ2hTXC9ucGxabitZNFNXMWp4V1dGaXBSQjBxQjVhZ1BpY1lFcGhGTlBjbVJSbWdack5yTGo2TjFJS2hDSXJJU1JF ▶"
Session empty
Server/Request Data
USER	
"www-data"
HOME	
"/var/www"
HTTP_COOKIE	
"remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IlFPWVVjVUFXWEpoSncxOFdWQnhTTFE9PSIsInZhbHVlIjoiUjlibHFwc3pMMmF1SENoVFhcL2twWUdlNks5OG1iNnJkZHpvbk ▶"
HTTP_ACCEPT_LANGUAGE	
"en-US,en;q=0.9"
HTTP_ACCEPT_ENCODING	
"gzip, deflate"
HTTP_REFERER	
"http://bookstack/books/competition-guide/page/healthcare"
HTTP_ACCEPT	
"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
HTTP_USER_AGENT	
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
HTTP_DNT	
"1"
HTTP_UPGRADE_INSECURE_REQUESTS	
"1"
HTTP_CONNECTION	
"keep-alive"
HTTP_HOST	
"bookstack"
REDIRECT_STATUS	
"200"
SERVER_NAME	
"perplexed"
SERVER_PORT	
"80"
SERVER_ADDR	
"192.168.56.101"
REMOTE_PORT	
"57292"
REMOTE_ADDR	
"192.168.56.1"
SERVER_SOFTWARE	
"nginx/1.10.3"
GATEWAY_INTERFACE	
"CGI/1.1"
REQUEST_SCHEME	
"http"
SERVER_PROTOCOL	
"HTTP/1.1"
DOCUMENT_ROOT	
"/var/www/bookstack/public"
DOCUMENT_URI	
"/index.php"
REQUEST_URI	
"/settings/users/3"
SCRIPT_NAME	
"/index.php"
CONTENT_LENGTH	
""
CONTENT_TYPE	
""
REQUEST_METHOD	
"GET"
QUERY_STRING	
""
SCRIPT_FILENAME	
"/var/www/bookstack/public/index.php"
PATH_INFO	
""
FCGI_ROLE	
"RESPONDER"
PHP_SELF	
"/index.php"
REQUEST_TIME_FLOAT	
1535683678.6638
REQUEST_TIME	
1535683678
APP_ENV	
"production"
APP_DEBUG	
"true"
APP_KEY	
"base64:IoEEgDkwNET2kAnxEisXgLTBFgWL2CxRUoWP8eRHYkM="
DB_HOST	
"localhost"
DB_DATABASE	
"bookstack"
DB_USERNAME	
"bookstack"
DB_PASSWORD	
"ZprAWN5d1n9cc"
CACHE_DRIVER	
"file"
SESSION_DRIVER	
"file"
QUEUE_DRIVER	
"sync"
MEMCACHED_SERVERS	
"127.0.0.1:11211:100"
STORAGE_TYPE	
"local"
STORAGE_S3_KEY	
"false"
STORAGE_S3_SECRET	
"false"
STORAGE_S3_REGION	
"false"
STORAGE_S3_BUCKET	
"false"
STORAGE_URL	
"false"
AUTH_METHOD	
"standard"
GITHUB_APP_ID	
"false"
GITHUB_APP_SECRET	
"false"
GOOGLE_APP_ID	
"false"
GOOGLE_APP_SECRET	
"false"
OKTA_BASE_URL	
"false"
OKTA_KEY	
"false"
OKTA_SECRET	
"false"
DISABLE_EXTERNAL_SERVICES	
"false"
LDAP_SERVER	
"false"
LDAP_BASE_DN	
"false"
LDAP_DN	
"false"
LDAP_PASS	
"false"
LDAP_USER_FILTER	
"false"
LDAP_VERSION	
"false"
MAIL_DRIVER	
"smtp"
MAIL_HOST	
"localhost"
MAIL_PORT	
"1025"
MAIL_USERNAME	
"null"
MAIL_PASSWORD	
"null"
MAIL_ENCRYPTION	
"null"
Environment Variables
APP_ENV	
"production"
APP_DEBUG	
"true"
APP_KEY	
"base64:IoEEgDkwNET2kAnxEisXgLTBFgWL2CxRUoWP8eRHYkM="
DB_HOST	
"localhost"
DB_DATABASE	
"bookstack"
DB_USERNAME	
"bookstack"
DB_PASSWORD	
"ZprAWN5d1n9cc"
CACHE_DRIVER	
"file"
SESSION_DRIVER	
"file"
QUEUE_DRIVER	
"sync"
MEMCACHED_SERVERS	
"127.0.0.1:11211:100"
STORAGE_TYPE	
"local"
STORAGE_S3_KEY	
"false"
STORAGE_S3_SECRET	
"false"
STORAGE_S3_REGION	
"false"
STORAGE_S3_BUCKET	
"false"
STORAGE_URL	
"false"
AUTH_METHOD	
"standard"
GITHUB_APP_ID	
"false"
GITHUB_APP_SECRET	
"false"
GOOGLE_APP_ID	
"false"
GOOGLE_APP_SECRET	
"false"
OKTA_BASE_URL	
"false"
OKTA_KEY	
"false"
OKTA_SECRET	
"false"
DISABLE_EXTERNAL_SERVICES	
"false"
LDAP_SERVER	
"false"
LDAP_BASE_DN	
"false"
LDAP_DN	
"false"
LDAP_PASS	
"false"
LDAP_USER_FILTER	
"false"
LDAP_VERSION	
"false"
MAIL_DRIVER	
"smtp"
MAIL_HOST	
"localhost"
MAIL_PORT	
"1025"
MAIL_USERNAME	
"null"
MAIL_PASSWORD	
"null"
MAIL_ENCRYPTION	
"null"
Registered Handlers
0. Whoops\Handler\PrettyPageHandler

remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d | "eyJpdiI6IlFPWVVjVUFXWEpoSncxOFdWQnhTTFE9PSIsInZhbHVlIjoiUjlibHFwc3pMMmF1SENoVFhcL2twWUdlNks5OG1iNnJkZHpvbk5tRUVZVjdvMVBcL2xqTHROR0VzcGRnZzlma0p0aDIra1wvK2lnYVk0 ▶"
-- | --
XSRF-TOKEN | "eyJpdiI6IkUrRWJNeTJNcjNvZDhlSElLNU1oQ3c9PSIsInZhbHVlIjoiWDVYTjArajZPaEduVzQways1RlVQM3QzNngzSDZsKzBUUkxWQUZINlBxa0hYU2ZXU2t1VXJzckR3Vnh2N29ueUZqZ0xrRlRUWG5SN2FC ▶"
laravel_session | "eyJpdiI6Imd6Rk5tV1NXaFhMVkZ4Z3N4d2R4OVE9PSIsInZhbHVlIjoiOHUzRk9HMkZBdmNEZ2hTXC9ucGxabitZNFNXMWp4V1dGaXBSQjBxQjVhZ1BpY1lFcGhGTlBjbVJSbWdack5yTGo2TjFJS2hDSXJJU1JF ▶"

**Comment by ssddanbrown** [comment] 2018-08-31 13:40
Hi @lynchpatrickj,
Did you run a `composer install` on upgrade or does that throw any error when ran?

**Comment by lynchpatrickj** [comment] 2018-08-31 15:01
I did not install composer again after upgrading.

On Aug 31, 2018 9:40 AM, "Dan Brown" <notifications@github.com> wrote:

Hi @lynchpatrickj <https://github.com/lynchpatrickj>,
Did you run a composer install on upgrade or does that throw any error when
ran?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BookStackApp/BookStack/issues/994#issuecomment-417667538>,
or mute the thread

**Comment by ssddanbrown** [comment] 2018-09-01 09:08
Do you get any errors when you run `composer install`? 
Are you running this command on the same machine you host BookStack on?

**Comment by lynchpatrickj** [comment] 2018-09-02 04:04
yes, I am. It says composer is not installed; 
![image](https://user-images.githubusercontent.com/9791585/44952081-b9ea9300-ae43-11e8-9edb-fb74d21844e0.png)

**Comment by lynchpatrickj** [comment] 2018-09-02 04:11
Install attempt:

```
plynch@bookstack:/var/www/bookstack$ sudo apt-get -f install composer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 composer : Depends: php-symfony-console (>= 2.5) but it is not going to be installed
            Depends: php-symfony-filesystem (>= 2.5) but it is not going to be installed
            Depends: php-symfony-finder (>= 2.4) but it is not going to be installed
            Depends: php-symfony-process (>= 2.4) but it is not going to be installed
            Depends: php-json-schema (>= 1.6) but it is not going to be installed
            Depends: php-json-schema (< 2~~) but it is not going to be installed
            Depends: php-composer-spdx-licenses (>= 1.0) but it is not going to be installed
            Depends: php-composer-spdx-licenses (< 2~~) but it is not going to be installed
            Depends: php-composer-semver (>= 1.0) but it is not going to be installed
            Depends: php-composer-semver (< 2~~) but it is not going to be installed
            Depends: jsonlint (>= 1.4) but it is not going to be installed
            Depends: jsonlint (< 2~~) but it is not going to be installed
            Depends: php-cli-prompt (>= 1.0) but it is not going to be installed
            Depends: php-cli-prompt (< 2~~) but it is not going to be installed
            Recommends: mercurial but it is not going to be installed
 linux-generic-hwe-16.04 : Depends: linux-image-generic-hwe-16.04 (= 4.13.0.36.55) but 4.13.0.32.52 is to be installed
                           Depends: linux-headers-generic-hwe-16.04 (= 4.13.0.36.55) but 4.13.0.32.52 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

```

**Comment by ssddanbrown** [comment] 2018-09-02 06:44
Hi @lynchpatrickj,
Try the follow command:
```
php composer.phar install
```

**Comment by lynchpatrickj** [comment] 2018-09-02 14:28
That worked, thanks!

**Comment by lommes** [comment] 2018-09-05 04:57
Since the problem is solved I'm closing this ticket.

**Closed by lommes** 2018-09-05 04:57 UTC
