### ISSUE TITLE
Page navigation does not work on mobile devices

### ISSUE THREAD

**Issue by cw1998** [BookStackApp/BookStack#1454] opened 2019-05-18 19:50 UTC
**Describe the bug**
When viewing a page on a mobile device, page navigation in the "Info" tab does not work as it does on a desktop device.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Open a page with a number of headings so that it has a structure.
2. Tap on the "Info" tab
3. Tap on any element of the page navigation section

**Expected behaviour**
I would expect to be brought back to the content tab to the desired bookmark.

**Screenshots**
N/A

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.26.0
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Docker

**Additional context**
When going directly to a link containing an anchor on the end, you are brought to the correct place on mobile so you can get around this bug by clicking on the desired heading in page navigation, then refreshing the tab.

**Comment by ssddanbrown** [comment] 2019-05-25 14:39
Thanks for reporting @cw1998, totally forgot about the page nav on mobile when implementing the new tabbed layout.

Fix applied, will be in next patch release.

**Closed** 2019-05-25 14:38 UTC
Labels: :bug: Bug, :computer: Front-End

**Comment by Zciwobukaj** [comment] 2019-07-01 02:52
Hi, when do you plan to release the next patch ?
I really need this feature...

Thanks :)

**Comment by ssddanbrown** [comment] 2019-07-01 13:52
@Zciwobukaj The patch was released over a month ago, On the 27th of May.

**Comment by Zciwobukaj** [comment] 2019-07-01 20:03
I don't understand : I raise duplicate of this issue at the end of May, with v0.26.2.  
Now we still are with 0.26.2 and it's still impossible to edit page on iOS. Or I miss something ?


De: Dan Brown <notifications@github.com>(mailto:notifications@github.com)
Répondre: BookStackApp/BookStack <reply@reply.github.com>(mailto:reply@reply.github.com)
Date: 1 juillet 2019 at 15:52:18
À: BookStackApp/BookStack <bookstack@noreply.github.com>(mailto:bookstack@noreply.github.com)
CC: Zciwobukaj <accounts@jakubowicz.me>(mailto:accounts@jakubowicz.me), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Sujet: Re: [BookStackApp/BookStack] Page navigation does not work on mobile devices (#1454)

**Comment by ssddanbrown** [comment] 2019-07-01 21:06
@Zciwobukaj This issue, that you are commenting on, was fixed in v0.26.2.  The issue that you describe sounds more like issue #1058, Which will be fixed as part of v0.27.0. That release does not have a confirmed release date but I'd expect it to be some time mid to late July depending on how much time I get.

**Comment by Zciwobukaj** [comment] 2019-07-03 15:18
Nice news ! Thanks :)

De: Dan Brown <notifications@github.com>(mailto:notifications@github.com)
Répondre: BookStackApp/BookStack <reply@reply.github.com>(mailto:reply@reply.github.com)
Date: 1 juillet 2019 at 23:07:05
À: BookStackApp/BookStack <bookstack@noreply.github.com>(mailto:bookstack@noreply.github.com)
CC: Zciwobukaj <accounts@jakubowicz.me>(mailto:accounts@jakubowicz.me), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Sujet: Re: [BookStackApp/BookStack] Page navigation does not work on mobile devices (#1454)
