### ISSUE TITLE
Cover images selected in create dialog aren't stored

### ISSUE THREAD

**Issue by alexschroth** [BookStackApp/BookStack#1897] opened 2020-02-14 09:47 UTC
**Describe the bug**

Cover images, that are selected while you create a shelf or a book, do not appear after closing the dialog, i.e. if you visit the shelves / books section, cover images are not shown.

Workaround: Open the edit dialog after you've created the book / shelf and upload the image (again).

**Steps To Reproduce**

1. Go to 'Shelves'
2. Click on 'New Shelf'
3. Add a title and upload a cover image
4. Click on 'SAVE SHELF'
5. Go to 'Shelves'

**Expected behavior**

Previously uploaded cover image is shown.

**Configuration**

 - Exact BookStack Version (Found in settings): 0.28.0
 - PHP Version: 7.3.11
 - Hosting Method (Nginx/Apache/Docker): nginx (+ php-fpm)

**Comment by sunnybeats** [comment] 2020-02-14 10:03
Same thing,
I was able to reproduce the bug like described.

**Comment by TBK** [comment] 2020-02-14 16:39
Which browser + version + OS do you use?

**Comment by alexschroth** [comment] 2020-02-14 17:48
> Which browser + version + OS do you use?

Safari 13 on macOS 10.15.3

**Comment by TBK** [comment] 2020-02-14 19:23
The issue is https://github.com/BookStackApp/BookStack/blob/33ef1cd4fa2e4f8b988658d0d244b2dd67ba09a2/app/Http/Controllers/BookshelfController.php#L93

which should be
```
$this->bookshelfRepo->updateCoverImage($shelf, $request->file('image', null)
```

I will provide a PR.

**Comment by sunnybeats** [comment] 2020-02-15 08:12
I changed my 

BookStack/app/Http/Controllers/BookshelfController.php

To the changes you have written and it seems to work 👌🏻

**Comment by ssddanbrown** [comment] 2020-02-15 18:43
Patch now applied in master therefore I'll close this. The fix will be in the next bugfix release.

---

@sunnybeats Beware that editing core BookStack files will likely cause conflicts when you next update. Reverting changes before updating is usually best.

**Closed by ssddanbrown** 2020-02-15 18:43 UTC
Labels: :bug: Bug, :factory: Back-End

**Comment by sunnybeats** [comment] 2020-02-16 09:20
Thanks, i copied back the file i have backuped before. So its like before the changes kow.

So i wait for the update now.
Thank you for this great app and this great suppord!

**Comment by ssddanbrown** [comment] 2020-02-16 09:28
@sunnybeats I deployed the update last night so you should be able to just update to get the fix.

**Comment by sunnybeats** [comment] 2020-02-16 10:23
@ssddanbrown 
Updated and its working!
Thanks
