### ISSUE TITLE
Login by name

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1498] opened 2019-06-19 13:11 UTC
I don't know if this has already been discussed anywhere here, but is there a reason why one has to login by email and not by name? Many tools use the same form field ("put in your name or your email address") which is much more convenient.

**Comment by ssddanbrown** [comment] 2019-06-22 12:36
Yeah, There are a few reasons:

- Having one system is easier to maintain (Especially since I bet people would then want this to be togglable).
- Names in BookStack are non-unique, for display, whereas email addresses are unique.
- Although convenient for some, multiple options can cause confusion for others.
- Using email to login reinforces the fact that the account is tied to that email, in the event of needing to reset the password. 

To be honest, I can't think of any platforms I use where you can use name to login. Many allow login via username or email but BookStack does not really store a username (Unless LDAP is in use).

**Comment by Hambern** [comment] 2019-10-28 17:50
I understand the reasoning here. But I'm a teacher and want to publish materials for them om my wiki. Just for them, not public, protected by a password. So I want to create a "student" account and have them login with the name "student" with a password.

**Comment by rmoe88** [comment] 2020-04-17 17:57
I would like to bump this feature request.  For the home-user it would be very helpful, so I don't have to have the family have to remember multiple login methods for the local network services I have going, and they could just remember their one user-pass.

**Comment by NextBlaubeere** [comment] 2020-10-12 08:37
+1 for a simple username + password login.

**Comment by johnroyer** [comment] 2021-01-09 05:23
> Names in BookStack are non-unique

I hope display name can be unique. Some feature will need unique name.

For example, somebody need to notify the page editor `JohnDoe`, they might type `@JohnDoe` in comment. But if display name is not unique, notification can not be done. More then one person will be notified.

**Comment by ezzra** [comment] 2021-01-09 13:17
I dont know @ssddanbrown `s plans here, but there are solutions in other tools, where you can have a unique username and a display name and you can use both to @mention someone

**Comment by horstepipe** [comment] 2021-10-16 20:40
I‘d like to see this, too.
Are there any workarounds to achieve that? I just want to host a simple wiki with predefined usernames and passwords which I give to my users, so there is no mail validity needed at all.
When using ldap there still is a need of an email address I guess?

**Comment by flemmingss** [comment] 2023-04-12 14:11
Old topic, but I support adding a way to just use "username".
I use my server to personal notes and have no mail configuration set up (so reset password or notifications to mail ect don't work here anyway "by design")

Also, some ideas and stuff:
Why not have a optinal email field and username field in the profile? Then I can login with both "user1" or "user1@random.domain".

Idea:
- For users not entering email just autogenerate username@no.mail.
- For users not entering username, just generate it by "what is before "@" in mail address"

**Comment by ssddanbrown** [comment] 2023-04-12 15:06
I've published a hack to add this kind of functionality within the hacks site:
https://www.bookstackapp.com/hacks/username-login/
This can be used to essentially get what's been asked for here. The logic is quite simple so could be tweaked to your own requirements. 

Otherwise, I'm going to close this off since it's not something I'd look to support an option for (And it would really need to be an option for forward-compatibility reasons), while being something I'm personally not fond of in terms of UX (At least when talking about dual-purpose email/username inputs), and since this has relatively low demand for a change to auth while having a possible workaround.

**Closed by ssddanbrown** 2023-04-12 15:06 UTC
Labels: :door: Authentication, :hammer: Feature Request
