### ISSUE TITLE
In dark mode, the text inside page editor is black against dark backgroud, making it hard to read.

### ISSUE THREAD

**Issue by mahenkpatel** [BookStackApp/BookStack#2201] opened 2020-07-28 05:15 UTC
**Describe the bug**

While editing or creating a new page the text in the text editor is black. Which makes it hard to read against the dark background when Dark mode is enabled on Bookstack.

It looks file in light mode

**Steps To Reproduce**
Just edit or create a new page with Dark mode enabled.

**Screenshots**

![bookstack_dark_mode](https://user-images.githubusercontent.com/17384364/88622001-6466a180-d0bf-11ea-91bc-94476ba14a6c.JPG)

**Expected behavior**
The text color should also be inverted to make it readable.

**Your Configuration**
 - BookStack v0.29.3 installed on Docker

**Comment by ssddanbrown** [comment] 2020-07-28 09:37
Hi @mahenkpatel,
This is unexpected, the text should default to a lighter color. Do you have any customizations set on your BookStack instance?
Are you able to reproduce this on the demo site?: https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site

**Comment by mahenkpatel** [comment] 2020-07-28 10:30
In the demo site, it looks fine. Looks like some issue with my installation, though I have not done any customization. Happening on mobile browser too so does not looks like an issue with browser. I am running linuxserver.io docker image. Will try with some other image.

Thanks for the quick reply.

**Comment by ssddanbrown** [comment] 2020-07-28 12:16
The linuxserver.io docker image should not cause this by itself really.

Looking again at the screenshot, it looks like maybe none of the internal styles are loading since the text block is much further to the left than expected.

I'd make sure  you're setting/passing the `APP_URL` option, configured to the base URL of your bookstack instance.

**Comment by mahenkpatel** [comment] 2020-07-28 12:42
Yup, that was it. Fixed after adding APP_URL and recreating the container. Did not know its that important.

Thanks

**Comment by ssddanbrown** [comment] 2020-07-28 15:08
Awesome, Yeah, APP_URL is particularly needed in reverse proxy setups like when using docker.
Will therefore close this off.

**Closed by ssddanbrown** 2020-07-28 15:08 UTC
Labels: :dog2: Support

**Comment by mrgrey916** [comment] 2024-08-03 18:38
Sorry to dig up an old thread. I'm new to Bookstack & Promox (where I have Bookstack installed using Turnkey's template). I'm also using my own domain via Cloudflare.

So, I have the same issue where when I setup Bookstack with my domain http://books.example.com, in dark mode when editing the cursor and text is black. But if I use my local IP address such as https://192.168.1.20 then the cursor and text is as expected and is 80% white or whatever the default is. Also if I don't put in the domain, I can't access Bookstack remotely, so as far as I understand, the domain has to be there for the Cloudfare "connection" to work.

Although I understand it's an issue where the style for dark mode isn't fully loading when I setup using my domain, since I'm pretty much a noob, I've not really got a clue how to update APP_URL, and what do I set that to, the domain or local IP address? When I view the docker-compose.yml file in vim, folder /var/www/bookstack/, it says localhost for APP_URL. Also FYI I have no .env listed in the bookstack folder, I mention this coz when I have looked for help it says to change APP_URL in .env.
