### ISSUE TITLE
Page Revisions: Compare two independently selected versions

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#3465] opened 2022-05-29 13:37 UTC
### Describe the feature you'd like

Currently version comparison covers only the version previous to the selected version. Request is to allow comparison between any two selected versions, similar to what we are familiar with e.g. on Wikipedia.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/3104762/170871564-395cc03b-78fc-41c4-acbc-f4eb8e1db584.png">

### Describe the benefits this would bring to existing BookStack users

Through the page creation/editing/revision process one often makes many minor changes in row, which are not necessarily of importance. Checking through those revision is cumbersome, if one has to compare one single revision after another, instead of comparing the overall editing result to e.g. the last days version.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment] 2022-05-29 14:06
Thanks for the request @Wookbert,
I'm going to close this off though as a duplicate of #1400 which has the same fundamental request.

**Closed as completed by ssddanbrown** 2022-05-29 14:06 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
