### ISSUE TITLE
Input after horizontal line not possible

### ISSUE THREAD

**Issue by Biepa** [BookStackApp/BookStack#2053] opened 2020-04-19 13:38 UTC
**Describe the bug**
When the Steps under "Steps do Reproduce" are done, no input is possible after a horizontal line.

**Steps To Reproduce**
1. Edit Page
2. go to the last line and insert a horizontal line
3. remove all content after the horizonal line (for example with "del"-key
4. save page
5. edit again and click on last line
6. cursors is directly under the horizontal line and the line is "marked" (don't know a better word)
7. no typing possible

**Expected behavior**
Accepting input after the horizontal line.

**Your Configuration (please complete the following information):**
Linuxserver.io docker containter with v 0.29

**Additional context**
Is reproducable on the demo page.

**Comment by ssddanbrown** [comment] 2020-04-26 10:00
Thanks for reporting @Biepa.

Am I correct in assuming you're using Firefox? 

Have done some testing and found this to be an reproducible in Firefox in both the page editor and in similar scenarios in raw html contenteditable blocks. Works fine in chrome, so appears to be due to how FireFox handles hr elements in contenteditable sections.

During my testing I found that I could still remove the line with a backspace to continue editing if wished, did you find the same?

We could add some logic listen to `Enter` press events when a rule is selected but that's getting into  level of event handling I'd prefer to avoid, especially with a review of the editors planned soon.

**Comment by Biepa** [comment] 2020-04-26 19:31
Yeah I'm using Firefox and yes i also could remove the line to continue editing.
If you say, there's a editor review coming, then it's ok for me to wait for it and then look again, if this has changed. So I'm okay with closing the issue for now.

Thanks for the fast reply, and your great work. I'm using Bookstack almost daily. :+1:

**Comment by ssddanbrown** [comment] 2020-04-26 19:36
No problem, Thanks for confirming @Biepa. Will therefore close this off.
If it becomes a massive annoyance for you then I could probably put together a little "Custom HTML Head Content" script to work-around for your instance. Just open a new issue or re-open this (If you have permission to) if you get to that stage.

**Closed by ssddanbrown** 2020-04-26 19:36 UTC
Labels: :bug: Bug, :computer: Front-End, :fountain: Upstream
