### ISSUE TITLE
SSO over ADFS Login

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#5285] opened 2024-10-24 07:41 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After customising the user accounts, you can log in via ADFS

Unfortunately there is still a problem where I do not know where the error is
After clicking on the ‘Login with SSO’ button, you are redirected to the Microsoft ADFS login form where you have to log in instead of logging in directly, the manual login works.

Where is the Bookstack instance running?
Docker container

How can the page be accessed?
In the local network with a reverse proxy (nginx)
the ADFS is also only accessible in the local network

### Exact BookStack Version

24.10

### Hosting Environment

Debian VM in a Docker Container

**Comment by ssddanbrown** [comment] 2024-10-24 08:42
Hi @reddexx,
Sorry, but I don't really understand what the issue is here.

> After customising the user accounts, you can log in via ADFS

- What do you mean by "customising the user accounts"?
- What type of authentication in BookStack are you configuring for this?

>  you are redirected to the Microsoft ADFS login form where you have to log in instead of logging in directly, the manual login works.

- What are your expectations here? 
- What is meant by "you have to log in instead of logging in directly"?

**Comment by reddexx** [comment] 2024-10-24 10:14
Hey @ssddanbrown 

What do you mean by "customising the user accounts"?
- https://github.com/BookStackApp/BookStack/issues/5270#issuecomment-2416483646

What type of authentication in BookStack are you configuring for this?
- SAML2

That we can use SSO (SAML2 over ADFS)

What is meant by "you have to log in instead of logging in directly"?
![image](https://github.com/user-attachments/assets/aba04e86-267b-4530-8383-b752e94af24a)
after submit this button coming to ADFS Login
![image](https://github.com/user-attachments/assets/2ba06bfb-3709-4f32-be7c-815c8ffbe014)

**Comment by ssddanbrown** [comment] 2024-10-24 10:53
Okay, so you're being redirect to your ADFS system for SAML2 login.
That's what I'd expect from BookStack, and any behavior while on the ADFS login screen will be down to the functionality of the auth (ADFS) system.

Are you already logged into ADFS, and therefore expecting the ADFS login to not show?
If so, then that's not really something due to BookStack behaviour as far as I'm aware. 
I am not familiar enough with ADFS to know or suggestion settings/configuration for this.

**Comment by reddexx** [comment] 2024-10-24 11:14
No, I have specifically cancelled my registration.
I tried to log in to a fresh session

Could it be due to the reverse proxy?

**Comment by ssddanbrown** [comment] 2024-10-24 11:20
> No, I have specifically cancelled my registration.
> I tried to log in to a fresh session

Oh, then I'd expect a login to show on the auth provider side (ADFS in this case).
Therefore I still don't understand what the issue is here, everything seems as expected.

**Comment by reddexx** [comment] 2024-10-24 14:13
I don't think that's how it should work.
I have set up several applications SSO only with Bookstack it is a little strange

I'm still checking a few things

**Comment by ssddanbrown** [comment] 2024-11-07 14:25
Since there's been no further progress here I'll go ahead and close this off, especially as I still don't see any indication of there being something unexpected, configurable or unexpected on the BookStack side of things.

**Closed as completed by ssddanbrown** 2024-11-07 14:25 UTC
Labels: :dog2: Support

**Comment by reddexx** [comment] 2024-11-07 22:31
sorry for the late feedback
I am still testing with another instance (Moodle) where the reverse proxy is used, only at the moment there is a lot of stress.😅

**Comment by awittendorff** [comment] 2025-05-19 08:22
@reddexx are you thinking of Windows Integrated Authentication with ADFS? So you don't have to type username/password on ADFS form? 
Try setting the following in the .env file: SAML2_IDP_AUTHNCONTEXT=false
