### ISSUE TITLE
After upgrade to v23.02 Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".

### ISSUE THREAD

**Issue by stepanov1975** [BookStackApp/BookStack#4067] opened 2023-02-26 12:16 UTC
### Describe the Bug

I updated to  v23.02 according to the update instructions. I originally used installation-ubuntu-20.04.sh script.
After upgrade when trying to access Bookstack i am getting the error:
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2".

### Steps to Reproduce

1. Install PHP 8.2 using instructions from Updating to v23.02 or higher
2. Run usual update commands

### Expected Behaviour

Expected successful update

### Browser Details

Google chrome

### Exact BookStack Version

v23.02

### PHP Version

8.2

### Hosting Environment

Ubuntu 20.04.5 LTS using official installation-ubuntu-20.04.sh script

**Comment by ssddanbrown** [comment] 2023-02-26 13:07
Hi @stepanov1975,

- Did you get any errors during the installation of PHP 8.2?
- What is the current output of running `php -v`?
- Have you tried re-logging into. or restarting, the system?

**Comment by stepanov1975** [comment] 2023-02-26 13:13
Hi @ssddanbrown 
There was no errors during the installation of PHP 8.2
php -v
```
HP 8.2.3 (cli) (built: Feb 14 2023 16:57:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies
```
I restarted the system. Can not log in because I see only the error. Nothing else.
phpinfo shows apache still using php 7.4 (/etc/php/7.4/fpm)
```
root@xxx:/home/ubadmin# a2enmod php8.2
Considering dependency mpm_prefork for php8.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php8.2:
Module php8.2 already enabled
```

**Comment by ssddanbrown** [comment] 2023-02-26 13:18
Strange, since your PHP version output is 8.2. 

- Can you screenshot the full error upon `composer install --no-dev`? I would have expected more detail. Just want to confirm exactly what you see.
- Could you confirm your composer version? `composer -V`?
- Whats the exact full ouput of running `git status` from your BookStack install directory?

**Comment by stepanov1975** [comment] 2023-02-26 13:26
There are no errors when running composer ```install --no-dev```. Screenshot attached
![Screenshot_1](https://user-images.githubusercontent.com/9785479/221413177-fe3cd71c-e578-41c6-86d7-9dcfcfb74d0b.png)
 
composer -V ```Composer version 2.5.4 2023-02-15 13:10:06```
git status
```
Refresh index: 100% (1704/1704), done.
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   storage/clockwork/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.env.bak
	public/phpinfo.php

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by stepanov1975** [comment] 2023-02-26 14:05
Ok! After a lot of digging, what helped is ```sudo apt purge '^php7.4.*'```

**Comment by nderambure** [comment] 2023-02-27 22:53
Hello,

I'm on Debian 11, still with PHP 7.4.33 and the same error appears.
No problem for pushing users to update PHP, I will do with Debian 12, but meanwhile, there was no info about incompatibility in changelog so I broke my install (but got a backup).
Would have been cool if we have been told about this, but thx anyway for this great app.

**Comment by ssddanbrown** [comment] 2023-02-27 23:00
> there was no info about incompatibility in changelog so I broke my install 

@nderambure What changelog are you referring to here? Warnings for this were in the GitHub release notes, Our Blogpost, our version-specific update notes and it was mentioned in the release video.

**Comment by nderambure** [comment] 2023-02-27 23:06
Oh ! My bad, I just did read the changelog... for 23.02.1, thought there was only one release between mine and new.
Sorry for that...
You can delete my comments ;)

**Comment by ssddanbrown** [comment] 2023-03-06 11:23
Since the issue is solved for the original issue creator I'll close this off.

**Closed as completed by ssddanbrown** 2023-03-06 11:23 UTC
Labels: :bug: Bug
