### ISSUE TITLE
Role changes by admin require password user

### ISSUE THREAD

**Issue by stonemaker01** [BookStackApp/BookStack#2276] opened 2020-09-24 08:33 UTC
While i was upgrading users roles, i was forced to confirm the password. As admin i should not hold users passwords. Upgrading an user with new role, should be done without confirming the password. 
Actually, the settings page does not ask for the password, but wont allow me to safe the changes, without this confirmation. 
Anybody an idea how to solve?

**Comment by ssddanbrown** [comment] 2020-09-26 10:07
Hi @stonemaker01,
Are you sure this is the case? The functionality is there in the event an admin needs to force change a password.
You should be able to change other details and leave the password fields empty to update the record without password change.
I have just tested this and it seems to work as expected.

**Comment by stonemaker01** [comment] 2020-09-26 11:20
Hello sir,
I have done the change again reversed, and same issue appeared. Confirm the
password of that particular user.
I was suprised myself too.




Op za 26 sep. 2020 12:07 schreef Dan Brown <notifications@github.com>:

**Comment by ssddanbrown** [comment] 2020-09-26 11:44
Okay, Before you press "Save" or "Update" when making changes to a profile, Is there any content within either of the password inputs? Or are they empty?

**Comment by stonemaker01** [comment] 2020-09-26 11:46
It is empty.



Op za 26 sep. 2020 13:44 schreef Dan Brown <notifications@github.com>:

**Comment by ssddanbrown** [comment] 2020-09-26 11:47
Okay, Strange.

And on the settings page, What version of BookStack is shown?

**Comment by stonemaker01** [comment] 2020-09-26 11:49
That is 0.30.0
I have not tried the same route in previous version.


Op za 26 sep. 2020 13:47 schreef Dan Brown <notifications@github.com>:

**Comment by stonemaker01** [comment] 2020-09-30 13:02
Hi. I noticed a difference:
Once an useraccount has a password dashed in the first block, any
adjustment in the user settings must be confirmed by a password in the
second block.
When there is no password in the first block, i can change anything in the
settings of the account.

There is somewhere an dependence build in, when passwords are set manually.

Op za 26 sep. 2020 13:47 schreef Dan Brown <notifications@github.com>:

**Comment by ssddanbrown** [comment] 2020-09-30 19:46
@stonemaker01 Yes, that is intentional, The second input is a confirmation block that is required to match the first input. This logic will only run if a new value is provided in the first input, otherwise the system will assume no changes need to be made to passwords at all.

**Comment by ssddanbrown** [comment] 2021-01-15 22:27
Since the issue was not confirmed here I'll close this off.

**Closed by ssddanbrown** 2021-01-15 22:27 UTC
