### ISSUE TITLE
[Feature Request]: Wanted Pages

### ISSUE THREAD

**Issue by robertfshort** [BookStackApp/BookStack#3281] opened 2022-02-24 15:32 UTC
### Describe the feature you'd like

Sometimes when I an building a page I know that there is going to be a link to some other page that isn't created yet. It would be helpful to have a way to created a wanted pages annotation in a page, maybe with a title, then at some later time when I am ready to make said new page, click that annotation and have it bring up a new page which when saved updates the original annotation with the link to the new page.

### Describe the benefits this feature would bring to BookStack users

ease of use.

### Additional context

Some competitor wikis have this feature already.

**Comment by ssddanbrown** [comment] 2022-02-24 16:05
Somewhat related to #550 and #441.
May close this off as a duplicate of fundamental request.

It would help if more detail could be provided for the "Benefits". 
"Ease of use" is really quite opinionated and does not provide any information as to how this request would  benefit the wider BookStack audience. 
The reason this field is important is to better understand what the core request here solves/achieves so that we're not fixed upon the specific implementation requested, to give opportunity to explore alternative implementations.

In regards to the additional context, I won't let competitor/similar platforms dictate what's in BookStack. Inclusion should instead be focused on benefit to the BookStack audience balanced against feasibility of maintenance & support.

**Comment by ssddanbrown** [comment] 2022-03-03 12:07
As per above, will therefore close this off.

**Closed as completed by ssddanbrown** 2022-03-03 12:07 UTC
Labels: :hammer: Feature Request

**Comment by poseidogithub** [comment] 2025-09-21 20:52
It’s a pity this hasn’t been implemented yet. The “red link” concept from Wikipedia would be very useful in BookStack.

When writing content, I often realize that a section or concept deserves its own dedicated page with more details. Right now, I need to stop, create that page, and then come back to the procedure I was working on.

If BookStack allowed creating placeholder links (like Wikipedia’s red links), I could simply mark those future pages while writing. Later, either myself or another team member could come back and expand those links into proper pages.

This would make the writing workflow smoother and help teams like mine—where we use BookStack for staff procedures—capture ideas for further documentation without interrupting the current writing process. (or even allow others to come back and finish the job
