### ISSUE TITLE
Page version number increases even if no changes were made prior to saving

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#1737] opened 2019-10-22 22:33 UTC
**Describe the bug**
If you open a page, go into edit mode and save the page without actually making any change, BookStack creates a new version which is of course absolutely identical to the existing/prior version.

**Expected behavior**
When clicking onto „Save page“, BookStack should leave edit mode and a dialogue should show up reading "No changes were made, thus no new version created.“

**Comment by mflagler** [comment] 2020-02-20 21:55
Why not just hit the back button instead of the save button? If you have made changes, it will prompt you before actually going back.

**Comment by ssddanbrown** [comment] 2021-02-11 23:43
Thanks for reporting @Wookbert, Did not see that #1846 was a duplicate of this.
There were some checks in place to prevent unrequired revisions but they were not working as intended. This has now been patched in 5323cb52245c4ec7f8735173e3057e321ff6327f, to be part of the next feature release.

**Closed by ssddanbrown** 2021-02-11 23:43 UTC
Labels: :bug: Bug
