### ISSUE TITLE
[Bug Report]: PDF Generation - Images In Table Not Formatting Correctly

### ISSUE THREAD

**Issue by zshannonmec** [BookStackApp/BookStack#3190] opened 2022-01-21 20:27 UTC
### Describe the Bug

Images that are added to tables within Bookstack pages seem to not size properly when exported as PDF. Instead of mirroring the HTML view the images are overlapping and giant in size making it illegible.

### Steps to Reproduce

1. Create a table on a page
2. Insert pictures into table cells
3. Save page
4. Export page as PDF

### Expected Behaviour

Pictures should be formatted in the same way they are in HTML.

### Screenshots or Additional Context

 I've attached two sample images. One of what it should look like (HTML/Editor) and what is produced by the export (PDF).

HTML / Editor Example
![ImagesInTable-Bookstack-EditorPreview](https://user-images.githubusercontent.com/98187884/150595579-8bc561a4-a1fe-4745-9246-bb06e2baa112.png)

Export (PDF) Example
![ImagesInTable-Bookstack-PDFPreview](https://user-images.githubusercontent.com/98187884/150595580-afe756f1-3d54-4c8f-bea2-6ebcd3a0e11b.png)

### Exact BookStack Version

v21.12.2

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04.3 LTS - Installed using official installation script

**Comment by ssddanbrown** [comment] 2022-01-24 17:39
Thanks for reporting @zshannonmec, Can confirm this issue.

The sizing of linked images within tables, for PDF export, is pretty complex. The cause of the images escaping the container were a side-effect of a patch to fix another image issue (#3120).

I've made some changes for the next patch release, in 8b5747eae2f5aaeb8c0ac07a4f9e883de8c53470. These changes won't likely fix the issue though, but will instead probably cause images to be super small within their container which, although not ideal, is probably preferable since you could still click through and view and they won't be majorly overlapping.

I've tested the development branch of the DOMPDF library we use for PDF generation, and it appears the image sizing logic will soon be smarter to achieve the desired result. We just need to wait for their next stable release.

**Comment by zshannonmec** [comment] 2022-01-24 19:43
Hi Dan,

Sounds great. I really appreciate you looking into this, and yes even as an interim solution, keeping the overall table/page formatting in tact is definitely preferable. 👍

**Comment by ssddanbrown** [comment] 2022-02-24 14:33
I've now bumped our used version of DomPDF to the 1.2 which provides much better image-in-table support from my testing.
Will be part of the next feature release.

**Closed** 2022-02-24 14:32 UTC
Labels: :bug: Bug, :truck: Export System
