### ISSUE TITLE
Highlighting of Search results

### ISSUE THREAD

**Issue by plohmeier** [BookStackApp/BookStack#1891] opened 2020-02-12 19:20 UTC
Like this app very much and was looking to see if there had been in requests to have highlighted search results or a way to configure this.  It would be a great feature I think if it is not already there somewhere.  

Thanks

**Comment by lishuai199502** [comment] 2020-03-24 08:08
+1

**Comment by mattpera** [comment] 2020-04-30 11:44
+1 !
And thank you for this great app!

**Comment by jdrese** [comment] 2020-11-03 09:31
I would argue that this is quite important.
When having lots of books search will only return those, then entering the documents require you to use the Search engine from the browser to find the words you might be locking for. This requires then 2 search actions to get what you need.

Clicking on a search result should try to frame the first result on the resulting page and highlight the rest of the matching words in the book/document.

**Comment by niklasgrewe** [comment] 2020-11-07 11:49
+1
thank you so much for your hard work. The app gets better and better

**Comment by BenAdamsonWecorp** [comment] 2020-11-13 15:34
Is this a duplicate of [#997](https://github.com/BookStackApp/BookStack/issues/997)?

**Comment by ssddanbrown** [comment] 2021-11-13 15:47
Highlighting (via boldening) of terms within search results has been added as part of #3043 and will be part of the next release.
Please note, this is somewhat of an estimation of what might have contributed to the match.
Will therefore close this off.

**Closed by ssddanbrown** 2021-11-13 15:47 UTC
Labels: :hammer_and_wrench: Enhancement, :factory: Back-End

**Comment by zylan1** [comment] 2025-07-03 10:28
Hi, it sounds like you may have misunderstood this bug. It's not about hilighting the text in the search results. 

Clicking on the actual search result should try to frame the first result on the resulting page and highlight the rest of the matching words in the book/document, to prevent the user from then having to use their browser search to find the terms in the page, as it might not be obvious where they are in longer documents.
