### ISSUE TITLE
How to change the App Namespace to Our Own?

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#620] opened 2017-12-17 15:28 UTC
### For Feature Requests

Desired Feature: none

How to Change the App's Namespace(in code) from `BookStack` to our own?

**Comment by ssddanbrown** [comment] 2017-12-17 18:57
You could do a find/replace or I think Laravel even has a helper command for this but that will break upon updating going forward.

The question is why would you want to do this?

**Comment by yoginth** [comment] 2017-12-18 09:50
For optimizing the app, can find and replace work?

**Comment by ssddanbrown** [comment] 2017-12-20 20:16
@yoginth Yeah, Find and replace should work as long as you go careful but again, It will break upon update.

In what way will it optimize the app?

**Comment by yoginth** [comment] 2017-12-21 02:57
not optimizing but for better understanding, my dev team can't understand the code so we are changing it! **Find and replace not working!**

**Comment by yoginth** [comment] 2017-12-21 02:58
Lot of them asking what is bookstack? in the code!

**Comment by ssddanbrown** [comment] 2017-12-24 14:32
Just to confirm, Are you talking about the namespace in the PHP files or are you referencing some kind of other 'Namespace'?

**Comment by yoginth** [comment] 2017-12-24 14:33
Changing the Namespace name!

`<?php namespace BookStack;` to
`<?php namespace MyNamespaceName;`

**Comment by ssddanbrown** [comment] 2017-12-24 14:49
Okay, Then a careful find and replace in pretty much any text editor should do the job.

Note that the namespace is used in the DataBase on polymorphic models (activity, views, tags, comments, SearchTerms, EntityPermissions & more..) so you'd likely have to do some database updates if it's on an existing instance. 

To be honest, This change won't be worth it unless you're looking to fork the code forever.

**Comment by yoginth** [comment] 2017-12-24 14:51
No, it's not working :cry: and I'm customizing the bookstack for production purpose!

**Comment by ssddanbrown** [comment] 2017-12-24 15:03
Any clues into what's not working? What errors are you seeing? Are you having trouble with the find + replace? Are you doing this on a live instance?

**Comment by yoginth** [comment] 2017-12-24 15:05
HTTP 500 Error in Browser! I'm doing it in development instance and my live instance is here! https://docspen.ga

**Comment by ssddanbrown** [comment] 2017-12-24 15:17
If the error is BookStack branded (Has footer and header on the page) or is not the default webserver error you can [follow these docs](https://www.bookstackapp.com/docs/admin/debugging/) to get more information on the issue.

If the issue is a basic webserver issue you'll need to dive into the logs for your webserver or php to find the issue.

Since changing the namespace provides no functional value to this project (And is more likely just to cause issues) it is not a feature I think is worth supporting and therefore I am going to close this request.

**Closed by ssddanbrown** 2017-12-24 15:17 UTC
