### ISSUE TITLE
Bookstack Login issue

### ISSUE THREAD

**Issue by sachinvishwakarma26** [BookStackApp/BookStack#4246] opened 2023-05-17 14:06 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi Team,

We have configured all perquisites for bookstack on Amazon linux. we aren't getting login screen its showing only blank screen. Please advise.

Please find the below attached screenshot.

![image](https://github.com/BookStackApp/BookStack/assets/43565381/1f284ce0-9413-4650-aa24-7ace2e047ff2)

### Exact BookStack Version

v22.11.1

### PHP Version

7.4

### Hosting Environment

Amazon Linux

**Comment by ssddanbrown** [comment] 2023-05-17 17:01
Please follow our debugging guidance to get error detail from logs:
https://www.bookstackapp.com/docs/admin/debugging/

That page includes a section about white screen upon access.

**Comment by sachinvishwakarma26** [comment] 2023-05-18 10:56
@ssddanbrown  Thanks for providing troubleshooting blog. In our case we running bookstack on Amazon Linux 2 and our webserver user is Nginx. Can you please let us know the path to change the permissions.

**Comment by sachinvishwakarma26** [comment] 2023-05-19 10:06
@ssddanbrown Please provide the troubleshooting steps

**Comment by ssddanbrown** [comment] 2023-05-20 07:24
I have a page regarding the setting file permission here:
https://www.bookstackapp.com/docs/admin/filesystem-permissions/

You will need to adapt any example commands to suit your system/setup as they likely won't be correct by default.

**Comment by sachinvishwakarma26** [comment] 2023-05-23 13:20
@ssddanbrown, 

We have tried changing file permissions following above link. But still we are getting blank white screen.
Please find the below attached snapshot for reference.

<img width="524" alt="image" src="https://github.com/BookStackApp/BookStack/assets/43565381/ed5dbe1c-4df9-4dbd-ab7b-c79a676444f8">

**Comment by ssddanbrown** [comment] 2023-05-23 13:32
@sachinvishwakarma26 View your webserver (nginx) error log, as touched on within the debugging page I linked above. That should show exactly what the issue is and what file (if it is a permission error) has permission issues.

**Comment by sachinvishwakarma26** [comment] 2023-05-25 13:59
@ssddanbrown

We have tried changing permissions but still we are getting same problem.

Note: We have created one more server for bookstack its working fine without any issues.

Could you please help us to fix this issue.

**Comment by sachinvishwakarma26** [comment] 2023-05-25 14:20
@ssddanbrown ,

We are getting this kind of error 

[error] 836#836: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
Stack trace:

**Comment by ssddanbrown** [comment] 2023-05-25 15:37
@sachinvishwakarma26 That looks like you have not configured database details in the `.env` file. The information shown indicates you may not have even copied the `.env.example` to `.env` as per step 3 of the [manual installation steps](https://www.bookstackapp.com/docs/admin/installation/#manual-installation). Please do that then fill the `.env` file with the correct details for your system.

**Comment by sachinvishwakarma26** [comment] 2023-05-25 17:04
@ssddanbrown,

Thanks for your valuable help it worked. Now we need to redirect our bookstack endpoint to Azure DNS. Please advise here

**Comment by ssddanbrown** [comment] 2023-05-26 09:41
> Now we need to redirect our bookstack endpoint to Azure DNS.

What exactly do you mean by that?
What are you looking to functionally achieve?

**Comment by ssddanbrown** [comment] 2023-06-07 09:10
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.

**Closed as completed by ssddanbrown** 2023-06-07 09:10 UTC
Labels: :dog2: Support

**Comment by sachinvishwakarma26** [comment] 2024-12-17 12:56
@ssddanbrown,

Hope you're good.

Kindly confirm bookstack app will support for RHEL9 version. If its supporting can we get installation steps link?

Thanks,
Sachin

**Comment by ssddanbrown** [comment] 2024-12-17 13:57
@sachinvishwakarma26 We don't specifically assure for support, or test for any platforms outside of our Ubuntu scripts. Should be fine though as long as you meet the requirements.

That said, I produced a guide earlier this year for a support customer, so here's a version of that:

[2024-07-RHEL9-install.pdf](https://github.com/user-attachments/files/18166477/2024-07-RHEL9-install.pdf)
