### ISSUE TITLE
Allows to see all diagram tabs on pages without entring in edit mode.

### ISSUE THREAD

**Issue by 1vicente** [BookStackApp/BookStack#2294] opened 2020-09-30 14:55 UTC
**Describe the feature you'd like**
Allows to see all diagram tabs on pages without entring in edit mode.

Today pages only shows the first  diagram tab.

Example: In my Bookstack, there is a page that have describes about some processes and  one diagram with 6 tabs on it, but only the first tab is showing on page and on this page, I want to refer this diagram mora than once, but with another tab.

My suggest is that make possible to pages are able to show all diagrams tabs or that possible to choose the tab that will be shown.

**Describe the benefits this feature would bring to BookStack users**
Don't need to entry in edit mode to see all tabs diagrams.

**Additional context**
Examples of visualization page with multi tabs diagram:
![image](https://user-images.githubusercontent.com/13755048/94701238-cbe4db80-0312-11eb-9288-4ea34f384adc.png)

**Comment by ssddanbrown** [comment] 2020-09-30 19:43
Hi @1vicente,

With the core content that gets stored on a BookStack page I try to keep it as standard/plain as possible to prevent unnecessary lock-in to the platform for users. Currently we store these drawings as png, with a copy of the diagram embedded within, for such portability and ease-of-managment. Therefore I would not look to include this functionality directly within the platform since we'd need to rely on this particular format.

That said, I think there may be a way this can be done right now. Within the drawing editor you can go: File > Embed > Iframe > (Adjust Settings) > Create. You should be then able to copy some HTML `<iframe>` code.

Exit out the editor, On your BookStack page there's an insert media button (Next to drawing button). Click that then go to the embed tab and insert the drawing code then press okay then save the page. This should insert a "Viewer" box for that particular drawing with buttons to change page. This does rely on diagrams.net being live and, although you can edit from the viewer, you might need to do some additional management for updating the drawing.

**Comment by ssddanbrown** [comment] 2020-10-12 22:32
Since a potential workaround has been posted above, and since I've confirmed my stance on a more integrated solution, I'll close this off.

**Closed by ssddanbrown** 2020-10-12 22:32 UTC
