### ISSUE TITLE
Can't add / edit code block inside list

### ISSUE THREAD

**Issue by Kudja** [BookStackApp/BookStack#1622] opened 2019-09-03 18:08 UTC
**Describe the bug**
On Edit Page when inside any list Code Block format not available.
If I manually copy some code block inside the list, I can't edit it after this.

**Steps To Reproduce**
1. Go to 'Edit Page'
2. Click on 'Numbered list'
3. Type something
4. Open 'Formats' 
4. See error - 'Code Block' not available to select in the menu dropdown

**Expected behavior**
Can add code block inside any lists

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.27.2
 - Browser: Google Chrome 76.0.3809.132

**Comment by ssddanbrown** [comment] 2019-09-03 20:25
Potential related to, and a duplicate of, #534.

**Comment by ssddanbrown** [comment] 2020-09-30 19:49
Closing in favour of #534

**Closed by ssddanbrown** 2020-09-30 19:49 UTC
Labels: :cat2::cat2: Possible duplicate
