### ISSUE TITLE
Inherit parent permissions (Books and Shelves)

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3680] opened 2022-08-28 15:16 UTC
### Describe the feature you'd like

Basically [#1932](https://github.com/BookStackApp/BookStack/issues/1932) but expanded.

It would be really nice if you could specify when creating a page in a shelf to inherit the permissions of the shelf it's being made in.

For example, you have two roles.

`ROLE 1`
`ROLE 2`

You also have 2 shelves.

`SHELF 1`
`SHELF 2`

You configured it so that only `ROLE 1` can view `SHELF 1` and only `ROLE 2` can view `SHELF 2`. Now you want to make a book in `SHELF 2` but don't want `ROLE 1` seeing it. What it appears you need to do is make the book and either update the permissions of the book or go to the shelf permissions and copy the permissions to the books within the shelf (Or create a webhook and run a command on the bookstack instance).

This would be fine but, in a company setting this is something that can easily get missed or the user making the book doesn't have access to change permissions of the shelf or doesn't know the permission system well.

It would be nice if there was a checkbox you could set that would automatically inherit the permissions of the shelf the book is being made in. Even more nicer is if this could be set as the default option in bookstack settings. This would make it so proper access is granted to those who need it and denied for those who don't without taking extra steps.

### Describe the benefits this would bring to existing BookStack users

Better access control of books for use in corporate environments + easier to use for end users.

### Can the goal of this request already be achieved via other means?

Yes. You can create a webhook on book create that will execute `php artisan bookstack:copy-shelf-permissions --all` on the bookstack instance. But it seems hacky for something that could be built into the UI. Also not sure how well that will scale if there are multiple pages being made in a short time.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

I want to pitch this (Bookstack) to a company I work for. But I know this would be an area of concern and I image it is for other companies. Business don't like hacky solutions because "Well now we have to manage that too in addition to this".

**Comment by ssddanbrown** [comment] 2022-08-29 13:07
Thanks for the request @Mailstorm-ctrl, But I feel the core fundamental request here may already be covered by #1596

**Comment by ssddanbrown** [comment] 2022-09-05 12:13
Will therefore go ahead and close this off as a duplicate of #1596

**Closed as completed by ssddanbrown** 2022-09-05 12:13 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
