### ISSUE TITLE
Insertion of Footnotes/References/Citations

### ISSUE THREAD

**Issue by btalin** [BookStackApp/BookStack#4176] opened 2023-04-15 07:56 UTC
### Describe the feature you'd like

I was looking for a while to find something like BookStack to write my extensive book project, manage it and also collaborate. But I couldn't find any functionality to add official citation/references into the text or footnotes and I found it really a pitty as also the scientific community would love to use such a tool as it makes it way easier to organize information.

### Describe the benefits this would bring to existing BookStack users

Many book-writers but also scientific writers are using citations and references for claims/data etc. and I didn't find a way or issue or functionality that would do that in bookstack, but would make it immensely more useful.

### Can the goal of this request already be achieved via other means?

Maybe, there is bibify and other repositories that make it possible, but I guess this needs to be integrated somehow but I am not a programmer.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment] 2023-04-17 15:33
Thanks for this request but I'm going to close this off as a duplicate of #2637 which I believe already covers the core request here.

**Closed as completed by ssddanbrown** 2023-04-17 15:33 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
