### ISSUE TITLE
ability to spoof a user as admin

### ISSUE THREAD

**Issue by eoli3n** [BookStackApp/BookStack#4220] opened 2023-05-05 12:14 UTC
### Describe the feature you'd like

When connected as bookstack_admin user, I want to be able to see what a user see.

### Describe the benefits this would bring to existing BookStack users

Security, by checking the scope of a user inside bookstack.

### Can the goal of this request already be achieved via other means?

By stealing the user password ?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment] 2023-05-05 12:47
Thanks for the request, but I'm going to close this off as a duplicate of #3739.

**Closed as completed by ssddanbrown** 2023-05-05 12:47 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
