### ISSUE TITLE
Includes of a page will not be reused if the page will included on another page

### ISSUE THREAD

**Issue by jasonF1000** [BookStackApp/BookStack#4133] opened 2023-03-27 08:08 UTC
### Describe the Bug

If i have a page with includes from another page and i try to reuse this page also as an include on another Page. The includes from the page will not be resolved. Only showing the include tags.
Also i another way of explanation:
Page A includes a section of Page B -> it works the include will be resolved.
Page C includes now Page A -> Page A is resolved but the include of Page B will not be resolved on Page C

i hope this was clear

### Steps to Reproduce

1. reuse page b on page a
2. reuse page a on page c 
3. you will see that the page b content will not be resolved on page c

### Expected Behaviour

the expected behaviour ist that the resolving of the content works also if i reuse a page which already have includes from another page.

### Screenshots or Additional Context

![content-reuse-issue](https://user-images.githubusercontent.com/116643854/227880080-ce7d6d02-c153-4f93-b8d3-2cb9bb8a977c.png)

### Exact BookStack Version

 v23.02.1

### Hosting Environment

as Container on a kubenetes Cluster.
Application is working fine only a content reuse issue

**Comment by ssddanbrown** [comment] 2023-03-27 10:04
Thanks for raising, but this is not a bug, but the include feature has been built to only include a single level.
A request for nested includes is already open in #2845 so I'll close this off.

**Closed as completed by ssddanbrown** 2023-03-27 10:04 UTC
Labels: :bug: Bug
