### ISSUE TITLE
Copy / Paste image in TinyMCE / BookStack

### ISSUE THREAD

**Issue by Arkantium** [BookStackApp/BookStack#3487] opened 2022-06-09 07:25 UTC
### Describe the feature you'd like

Hi !

It's possible to modify the TinyMCE for copy / past word file with image directly ? Actually we have to copy / past and after that add all image... 

### Describe the benefits this would bring to existing BookStack users

Convert all word file directly with just text adjustement

### Can the goal of this request already be achieved via other means?

Copy word file after that we have to save all image in the word for upload to BookStack & place all image in the bookstack book... Take long time for long file...

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundemental request
https://github.com/BookStackApp/BookStack/issues/449
But it's closed and i thinks copy / past with image is a good tool for community

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment] 2022-06-10 12:01
Hi @Arkantium,

I'm a bit confused by this. I does sound like you request is fundamentally the same as #449. That issue is still open, it is not closed. Does your request differ at all?

**Comment by ssddanbrown** [comment] 2022-06-16 13:26
I'll go ahead and close this off as a duplicate of #449

**Closed as completed by ssddanbrown** 2022-06-16 13:26 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
