### ISSUE TITLE
Text can overlay images on DOMPDF exports

### ISSUE THREAD

**Issue by mmteyrek** [BookStackApp/BookStack#1608] opened 2019-08-29 21:18 UTC
**Describe the bug**
Export pdf with an image

**Steps To Reproduce**
write an page with an embded image , export pdf.

**Expected behavior**
pdf correctly exported

**Screenshots**
Page 
![image](https://user-images.githubusercontent.com/17122420/63977085-21690c00-cab3-11e9-93a6-47d11deec4e0.png)

pdf

![image](https://user-images.githubusercontent.com/17122420/63977113-2fb72800-cab3-11e9-818d-01c061fa17cc.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version : BookStack v0.26.4
 - PHP Version: 7.3.5
 - Hosting Method : Apache

**Comment by JtheBAB** [comment] 2019-08-30 04:26
Hi

Have you tried to switch to this?

https://www.bookstackapp.com/docs/admin/pdf-rendering/

**Comment by mmteyrek** [comment] 2019-08-30 11:36
Hi,
I will use a Shared Hosting, so I don't think I will able to do it.
Anyway thank you for your help.

**Comment by ivanivkovic** [comment] 2020-01-20 15:55
Had the same issue, confirmed this helped. https://www.bookstackapp.com/docs/admin/pdf-rendering/

Thanks.

**Comment by ES-Six** [comment] 2020-03-16 20:24
Thanks,

I confirm this works : https://www.bookstackapp.com/docs/admin/pdf-rendering

If you get fail to convert PDF after setting wkhtmltopdf in .env and installing wkhtmltopdf with apt-get command : you will need a headless version (with patched QT libraries).

I found an easy way to install it on debian so I share here how to do it :

https://stackoverflow.com/a/38336153

**Comment by ssddanbrown** [comment] 2022-01-30 17:08
Just come across this while looking through the issue list. Tried testing on my dev instance use a variety of text and image combinations but could not reproduce. Think this may have been addressed in the meantime so will therefore close but feel free to raise again if it can be reproduced following specific steps.

**Closed by ssddanbrown** 2022-01-30 17:08 UTC
Labels: :bug: Bug, :factory: Back-End, :truck: Export System
