### ISSUE TITLE
could not send email when register

### ISSUE THREAD

**Issue by junlicn** [BookStackApp/BookStack#765] opened 2018-03-26 06:26 UTC
### For Feature Requests

Desired Feature:  after setting email,  could receive mail. 

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*:
* PHP Version:
* MySQL Version:

##### Current Behavior
after register, wait a long while, then hit could not send mail.  
But I could not see any log about detail.  I hav tried   app_debug = true,  /var/log/access.log error.log

![image](https://user-images.githubusercontent.com/14213863/37889985-6658223a-3101-11e8-8ad6-183319c294b2.png)

##### Steps to Reproduce

my email setting have tested on mail client.

# Mail settings
MAIL_DRIVER=smtp
MAIL_HOST=smtp.139.com
MAIL_PORT=25
MAIL_USERNAME=13691114805@139.com
MAIL_PASSWORD=XXXXX
MAIL_ENCRYPTION=null

**Comment by Abijeet** [comment] 2018-03-26 17:13
Hi @junlicn,

The logs will be available under - `{bookstack_dir}/storage/logs/laravel.log`.

Please post what you see there.

In addition please mention the BookStack version that you are using.

**Comment by NickZengXL** [comment] 2018-04-11 08:37
I hit this issue too, is there any way to solve it?

I use docker-compose to start up bookstack.

**Comment by nicobubulle** [comment] 2018-05-25 07:33
### For Bug Reports
* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.21.0
* PHP Version: PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
* MySQL Version: mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Nginx + PHP-FPM

##### Expected Behavior
Receive a mail on register

##### Current Behavior
After registration, I have this message:
Email confirmation required but the system could not send the email. Contact the admin to ensure email is set up correctly.

##### Steps to Reproduce
Mail configuration in .env (this account works in owncloud configuration):
MAIL_DRIVER=smtp
MAIL_HOST=SSL0.OVH.NET
MAIL_PORT=465
MAIL_USERNAME=contact@XXXXXX
MAIL_PASSWORD=XXXXXXXXX
MAIL_ENCRYPTION=tls

Tried to put them in config/mail.php too

Turn app_debug = true but no relevant message and {bookstack}/storage/logs/laravel.log remain empty...

Thanks for your help

**Comment by lolownia** [comment] 2018-05-29 09:32
We have the same problem. But do not get any logs. Can you tell me how to enable SMTP debugging?

**Comment by auswade** [comment] 2018-08-06 03:16
hello,

I'm experiencing this issue on my installation as well, please see the details below:
I installed using the script from Ubuntu 16.04, latest release of BookStack.

The /storage/logs folder has no files inside.


Thanks,
Wade

**Comment by timeandtimeago** [comment] 2018-08-14 04:39
Having the same issue

**Comment by zenjabba** [comment] 2018-09-30 16:58
having same issue. No logs are being generated when used within docker.

**Comment by Sygan** [comment] 2018-10-11 23:52
I had this issue as well so I dig around. Basically afer setting all of the information according to this: https://stackoverflow.com/a/38197222 everything works on my deployment.

**Comment by ssddanbrown** [comment] 2018-11-09 22:33
For everyone experiencing this issue, Please provide the following information to help with debugging:

* How are you hosting BookStack (Docker/Nginx/Apache etc...)?
* What is your PHP version?
* Have you set any mail settings in the `.env` file?
* How did you install BookStack (Scipt / Manual / Docker file)?

**Comment by DaBlitzStein** [comment] 2019-04-19 19:08
Nothing works. I checked the data and tested on another software. Tried everything including laravel common workarounds. 

There is a bug in smtp mail sending.

**Comment by ssddanbrown** [comment] 2019-04-20 09:54
I've going to close this issue for the following reasons:
* We have not heard from the original poster.
* Some people subscribed to this have resolved their issues.
* Everyone else probably has slightly different issues instead of one common bug being prevalent. 

If you are still experiencing issues, Please open a new issue with answers to the following:

- How are you hosting BookStack (Docker/Nginx/Apache etc...)?
- What version of BookStack are you on (Shown in settings)?
- What is your PHP version?
- Have you set any mail settings in the .env file?
- How did you install BookStack (Script / Manual / Docker file)?
- What errors, if any, are you seeing?
- When following the debug instructions, do you see anything in your log file?
- Have you been making edits to the `config/mail.php` file?

Simply saying "nothing works and I've tried everything" does not provide us any insight into being able to help your situation.

**Closed by ssddanbrown** 2019-04-20 09:54 UTC

**Comment by DaBlitzStein** [comment] 2019-05-19 15:24
Answers in order.

- APACHE 2
- Latest, updated at day
- 7.2 
- of course 
- script ubuntu 18.04 server
- no logs, no debug. Only "cannot send email" as a popup.
- yes, tried all these solutions. 

Maybe you have to change your attitude because it is obvius if I said i tried everything is because anything i tried worked, and i have 20 years of experience on this environment.

Thank you.

**Comment by ssddanbrown** [comment] 2019-05-19 15:58
@DaBlitzStein Please could you open this in a new issue, as per my comment above. 

> Maybe you have to change your attitude

Apologies if you did not like my previous response, I did not mean to emit any kind of attitude. Your previous comment was simply lacking any detail whatsoever, even when I've clearly asked for specific details above, meaning that anyone here, that would kindly take their free time to look into your issue, will have to go to much greater lengths to solving this for you since they'll have very little to go on.

> because it is obvius if I said i tried everything is because anything i tried worked, and i have 20 years of experience on this environment.

"Tried Everything" is a bit of a useless statement though because It will only include the paths that you know of. I have no prior idea of your experience or expertise. If you had truly "Tried Everything" you would have resolved the issue since there are other BookStack users with mail settings that work fine.

---

I'll lock this conversation as I can't see this getting any more productive here.
