### ISSUE TITLE
Missing RTL support in many text inputs such as comments and shelve name

### ISSUE THREAD

**Issue by Aimranekds** [BookStackApp/BookStack#2731] opened 2021-05-04 20:40 UTC
**Missing RTL Support**
We can't write properly in comments using Right-to-left languages (e.g. Arabic...)
Currently, comments start from left to right even if the language is RTL, and we can't mix tow languages have different text direction such as English with Arabic, the result is a mess.
In Page Navigation view, the same problem with text direction when we mix tow languages have different text direction.
I experienced the same problem inside the editor, just i can't format my text without mess due to missing RTL support.
Also Shelves, Books and Chapters names have the same problem with RTL.
**Expected behavior**
The ability to mix tow languages have different text direction without mess in any text input.

**Additional context**
I report it as a Bug because the comment feature for example is useless currently for any RTL user.

**Comment by ssddanbrown** [comment] 2021-05-04 22:32
Hi @Aimranekds,
Sorry, It might be my lack of experience with RTL languages but I'm not full understanding the issue or the expected behaviour. When I'm using arabic the text inputs for various things, including shelves and comments, are RTL as per the whole interface as seen below:

![Screenshot from 2021-05-04 23-29-16](https://user-images.githubusercontent.com/8343178/117077780-a26cb200-ad30-11eb-8e1b-8eed0b91d023.png)

Do you see something differently? Or is this supposed to be presenting in a different way?

**Comment by Aimranekds** [comment] 2021-05-05 16:31
Thank you @ssddanbrown for explaining the problem i faced. It turns out that I have to change the whole website language to mix different languages have different text direction.
I didn't know that fact (it's nice that the website view supports RTL), but many times i prefer to keep the website view language in English with the ability to write properly in Arabic at the same time as the case in few other websites (if that possible i will appreciate it as an extra support for RTL).
But for now the current setting is enough for my purpose.
Thank you again 👍🏼

**Comment by ssddanbrown** [comment] 2021-05-05 21:35
@Aimranekds Thanks for confirming, Will therefore close this off.

I probably won't add RTL inputs within an LTR interface due to the complexity it'll add, unless there's a major requirement for that. If it's only you using the instance, or if this would be desired by everyone, you could add something like this to the "Custom HTML Head Content" setting:

```html
<style>
input, textarea { direction: rtl; }
</style>
```

**Closed by ssddanbrown** 2021-05-05 21:35 UTC
