### ISSUE TITLE
Add Shelf to search on a book

### ISSUE THREAD

**Issue by SniperVegeta** [BookStackApp/BookStack#5199] opened 2024-09-10 12:34 UTC
### Describe the feature you'd like

I would like to add the shelf where the book stands, like the pages.

![image](https://github.com/user-attachments/assets/1b6a149c-6106-4319-be83-911048480e34)

### Describe the benefits this would bring to existing BookStack users

If i have the "same" book name on different shelfs i can visual see what shelf its belongs to.

### Can the goal of this request already be achieved via other means?

Not that i known off.

As i can see details on a page / i hope its an easy hack to implement this on a book.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment] 2024-09-14 12:14
Thanks for the request @SniperVegeta but I'm not keen on showing shlves in this way since books do not belong to a specific shelve in the same way as chapters/pages to books, and since a book can be on multiples shelves.

I'm going to close this off as a duplicate of existing issues #4773 & #4080.

**Closed as completed by ssddanbrown** 2024-09-14 12:14 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request
