### ISSUE TITLE
An Error Occurred An unknown error occurred while adding new user

### ISSUE THREAD

**Issue by shinobi31337** [BookStackApp/BookStack#3669] opened 2022-08-23 09:05 UTC
### Describe the Bug

When was trying to add new user by the link https://www.bookstack.fbi.ie/settings/users got the error message:

An Error Occurred An unknown error occurred while adding new user

### Steps to Reproduce

1. go to https://www.bookstack.fbi.ie/settings/
2. click to Users
3. Enter user details
4. click save

### Expected Behaviour

An Error Occurred An unknown error occurred while adding new user

### Browser Details

Chrome Dev 104.0.5112.81 on Linux

### Exact BookStack Version

22.04.2

### PHP Version

7.4.30

### Hosting Environment

AlmaLinux release 8.6 (Sky Tiger)

**Comment by ssddanbrown** [comment] 2022-08-23 09:21
Hi @shinobi31337,
Please check your error log file to find the cause of the error:
https://www.bookstackapp.com/docs/admin/debugging/

**Comment by shinobi31337** [comment] 2022-08-23 12:25
Hi ssddandbrown,

the nginx error log is showing:

<details>

```
2022/08/18 14:33:59 [error] 2273#2273: *13816 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: cspNonce in /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php:53
Stack trace:
#0 /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php(53): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/bookst...')
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Il...PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: cspNonce in /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php:53

2022/08/18 14:34:30 [error] 2278#2278: *13932 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: cspNonce in /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php:53
Stack trace:
#0 /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php(53): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/bookst...')
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Il...PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined variable: cspNonce in /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php:53
Stack trace:
#0 /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php(53): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/bookst...')
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
```

</details>

Laravel log: https://pastebin.com/K75bzf3c

With Regards,
Andrei.

**Comment by ssddanbrown** [comment] 2022-08-23 15:07
This looks to just be down to invalid email configuration.
Please configure your SMTP details within you `.env` file. There's the ability to send a test email within the "Settings > Maintenance" section of BookStack for rapid testing & validation.

**Comment by shinobi31337** [comment] 2022-08-23 17:53
we fixed it, thanks! it was unclear in the log files though.

**Comment by ssddanbrown** [comment] 2022-08-23 17:54
Good to hear, will therefore close this off.

**Closed as completed by ssddanbrown** 2022-08-23 17:54 UTC
Labels: :bug: Bug

**Comment by mosesmbadi** [comment] 2023-04-04 13:53
@shinobi31337 How did you fix the error?

**Comment by shinobi31337** [comment] 2023-04-05 09:32
@mosesmbadi just added smtp details to .env file and it fixed the issue.
