### ISSUE TITLE
Attachments not uploading

### ISSUE THREAD

**Issue by mcblum** [BookStackApp/BookStack#313] opened 2017-02-15 18:36 UTC
### For Bug Reports

* BookStack Version: Latest (as of Feb 15, 2017)
* PHP Version: 7
* MySQL Version: 5.6? Whatever was installed with the Ubuntu script.

##### Expected Behavior
I would be able to upload an attachment. 

##### Actual Behavior
I'm trying to upload an attachment which is, in this case, a pdf. I get a `422 unprocessable` back from the API with the following response:
```{"validation":{"file":["validation.uploaded"]}}```

**Comment by mcblum** [comment] 2017-02-15 18:36
Thank you for making Bookstack! It's really awesome.

**Comment by mayrmartin** [comment] 2017-02-20 19:39
Hey, are the folder permissions set the right way?⁠⁠⁠⁠

**Comment by ssddanbrown** [comment] 2017-02-23 18:45
Hi @mcblum, Sorry you're seeing this issue and sorry for my late reply.
As mayrmartin has mentioned can you check the permissions of the `storage/uploads` folder  (And all folders inside). Also, Could you confirm where you are seeing that validation message as that's not one I recognise at all.

**Comment by christophert** [comment] 2017-05-04 02:04
I would check your server's upload limit. PHP has a default upload size limit of 2MB and if you're using NGINX it sets a default limit of 1MB.

**Comment by ssddanbrown** [comment] 2017-09-23 09:02
Closing due to duration since last response. If you still face issues please open a new issue or feel free to continue to comment on this one.

**Closed by ssddanbrown** 2017-09-23 09:02 UTC
Labels: Type: Instance Issue / Support

**Comment by crainsaw** [comment] 2019-07-18 11:55
As @christophert pointed out that is caused by the upload size limit. In my wamp configuration it was enough to change two values in the php.ini file:
```
; Maximum allowed size for uploaded files.
upload_max_filesize = 10M

; Must be greater than or equal to upload_max_filesize
post_max_size = 10M
```
