### ISSUE TITLE
Support S3 v4 signatures for buckets secured with KMS customer managed keys

### ISSUE THREAD

**Issue by zonywhoop** [BookStackApp/BookStack#4209] opened 2023-04-30 03:10 UTC
### Describe the feature you'd like

When using a customer managed key for KMS encryption of an S3 bucket all GET and HEAD requests must be signed using an AWS v4 signature. Because Bookstack does not do this, even public files are not accessible.  This feature is available in Laravel 9 already using the temporaryURL() method on the storage facade as noted here:
https://laravel.com/docs/10.x/filesystem#temporary-urls

### Describe the benefits this would bring to existing BookStack users

Allowing this method of file access also allows for use of files stored in private buckets which is requirement for many companies that are seeking high end compliances such as SOC2, HIPAA, or PCI.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Over 5 years

**Comment by ssddanbrown** [comment] 2023-04-30 08:28
Thanks for the request, I'm going to close this off though as a duplicate of #763 which is essentially already existing as an issue to support AWS signed URLs.

**Closed as completed by ssddanbrown** 2023-04-30 08:28 UTC
Labels: :cat2::cat2: Possible duplicate, :hammer: Feature Request

**Comment by zonywhoop** [comment] 2023-04-30 15:14
@ssddanbrown, I saw #763, and while similar, this change would implement a smaller subset (download only) of the features required there. I also may be able to knock this out and provide a PR in the next week or two. Happy to work that against #763 as a partial implementation.

**Comment by ssddanbrown** [comment] 2023-04-30 16:58
@zonywhoop I'm fairly sure the mention of "Upload" in #763 is matter of translation, and would more accurately be referred to as "storage" in that context.

To be honest, I don't think I'd accept a PR for this right now since the demand is so minor to be worth expanding the scope of support here.
