### ISSUE TITLE
Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'

### ISSUE THREAD

**Issue by namannj46** [BookStackApp/BookStack#4403] opened 2023-07-26 09:12 UTC
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have integrated Bookstack in our Website with using iframe. so bookstack is opening through iframe but when i tried to login on bookstack through google login it is showing the error.
**accounts.google.com is refused to connect**

When i inspect the code and check the error it is showing :
**Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'**

So please help how i can resolve this error on Bookstack

### Exact BookStack Version

v23.05.2

### Hosting Environment

ubuntu 22.04

**Comment by ssddanbrown** [comment] 2023-07-26 09:22
This is a security control that Google are setting, not really something that can be worked around from a BookStack point of view. Many websites will block use in an iFrame due to security concerns.

**Comment by namannj46** [comment] 2023-07-26 10:28
Can you suggest the possible way to do google login inside the iframe  ?

**Comment by ssddanbrown** [comment] 2023-07-26 11:15
No, not really anything with Google direct.
You could maybe find an alternative auth platform, which does not prevent (or can be hacked to allow) iframe use, that can use google as an upstream auth provider itself, then use that with BookStack.

These are not paths I'd suggest or can recommended further on though, these limits are in place for security, and iframes as a bunch of troubles (They can also complicate cookies and visuals).

**Comment by ssddanbrown** [comment] 2023-08-02 12:32
Since there's been no follow-up I'm going to close this.

**Closed as completed by ssddanbrown** 2023-08-02 12:32 UTC
Labels: :dog2: Support

**Comment by ForkInABlender** [comment] 2024-02-24 21:05
welp, then the html used isn't the problem then and the issue is not fixed.
